### PR TITLE
#1062 Fix M0-split JSON parameters

### LINKED ISSUE #1062: Correct JSON when splitting M0
### Description

When splitting an M0 image from an ASL volumes, then we have to remove certain ASL tags when creating the M0.json as not all ASL tags are supposed to be there. 

Test on `Siemens_PCASL_3DGRASE_VE11C_3` and also find out why there is the `T1` tag, why the PLD and labdur tags are wrong, and why the TotalAcquiredPairs tag is wrong after import to BIDS.

When we are removing the dummyScans, we should make sure to reduce and check the TotalAcquiredPairs as well. For example in Siemens_PCASL_2DEPI_VE11C_MB_1, we have 45 pairs (including 2 dummy scans and 2 m0scans). We remove correctly both in BIDS2Legacy, but we reduce the TotalAcquired pairs only to 44 and not to 43.

### Tasks

- [x] When splitting M0 from ASL, run the BIDS function that strips the unnecessary ASL tags from the M0.json. Test on `Siemens_PCASL_3DGRASE_VE11C_3`. Check T1 tag, PLD and labdurs lengths.
- [x] Check `TotalAcquiredPairs` tag and adjust for removing dummy scans after splitting in `Siemens_PCASL_3DGRASE_VE11C_3`. and in `Siemens_PCASL_2DEPI_VE11C_MB_1`.
- [x] Check totalPairs and dummy in `xASL_bids_BIDSifyASLJSON`, `xASL_bids_parseM0`, `xASL_bids_BIDSifyASLNII`, `xASL_bids_MergeNifti`.

### How to test

- [x] Update `Siemens_PCASL_multi_VE11C_1` flavor.
- [x] RUn flavors test.
- [x] Do final flavor updates.

### Release notes

Fix TotalAcquiredPairs calculation with dummy scans.

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

Close #1062

### CODE REVIEW

File: Functions/BIDS/xASL_bids_BIDSifyASLJSON.m [hunk 1]
```diff
@@ -542,13 +542,24 @@
 end
 
 % First count the number of controls, labels, and deltaMs
+% Check and exclude dummy scans first from ASLContext
```
Comment (HenkMutsaerts) [inline Functions/BIDS/xASL_bids_BIDSifyASLJSON.m:545]: Are we sure we also removed the dummy scans from the image volume, if we remove it from the ASLContext here? Or am I mixing things up

File: Functions/InputOutput/xASL_io_SplitASL.m [hunk 2]
```diff
@@ -95,6 +95,9 @@ function xASL_io_SplitASL(inPath, iM0, iDummy)
 	% Check if both cbf and deltam/control/label volumes exist
 	if sum(~cellfun(@isempty,regexpi(aslContext,'deltam|control|label'))) && ...
 	   sum(~cellfun(@isempty,regexpi(aslContext,'cbf')))
+		% In this case, ignore CBF
+		warning('ASLContext has both a CBF image and delteM/control/label scans. CBF is thus ignored and discarded.')
```
Comment (HenkMutsaerts) [inline Functions/InputOutput/xASL_io_SplitASL.m]: delteM -> deltaM

I would change this warning to:

"ASLContext has both a CBF image and more rawer ASL images (e.g., deltaM, control, label). CBF is thus discarded."

And similar to above: are we sure that we sync our image volume changes with the ASLContext changes? They should probably always be done side-to-side to avoid making debugging difficult.

**Review by HenkMutsaerts — CHANGES_REQUESTED** [review]

File: Functions/BIDS/xASL_bids_BIDSifyASLJSON.m (hunk 1 above)
Comment (jan-petr) [reply Functions/BIDS/xASL_bids_BIDSifyASLJSON.m:545]: Yes. You are mixing things up :) Actually, a good comment. This part here is about counting controls/labels, so we are removing the dummy scans here only for the calculation so that we can calculate correctly TotalAcquiredPairs.

The real removal of dummy volumes are done in another function.

File: Functions/InputOutput/xASL_io_SplitASL.m (hunk 2 above)
Comment (jan-petr) [reply Functions/InputOutput/xASL_io_SplitASL.m]: Yes - changing the comment. 

About syncing - you are right, this should be done and we have a new issue for this in 1.12.0. In 1.11.0 in this commit, we are only fixing the JSON information, which was incorrect. In the follow-up issue, we will do proper ASLContext, StudyPar, ASL.json synchronization.

File: Functions/BIDS/xASL_bids_BIDSifyASLJSON.m (hunk 1 above)
Comment (HenkMutsaerts) [reply Functions/BIDS/xASL_bids_BIDSifyASLJSON.m:545]: OK but still we should link them in another issue right. And what is BIDS? TotalAcquiredPairs should normally be all volumes, including the dummy?

**Review by HenkMutsaerts — APPROVED** [review]

File: Functions/BIDS/xASL_bids_BIDSifyASLJSON.m (hunk 1 above)
Comment (jan-petr) [reply Functions/BIDS/xASL_bids_BIDSifyASLJSON.m:545]: Will be all solved in #1456
