### PR TITLE
Bug #1918 minor bugs

### LINKED ISSUE #1918: Testing-discovered bugs
### Description

Full testing of the develop branch uncovered some errors that crashed the pipeline.

### Tasks

- [x] Unit testing of JSON check has errors. Fixed in 64e426d6
- [x] Error in Philips_2DEPI_FLAIR_Segm_PWI4D_Quant_Parameters_LoQ SliceReadoutTime missing. Fixed in 6ce7c661
- [x] Error in Philips_2DEPI_Lesion_NoFLAIR_NoM0_HiQ CurrentMaskVascular in population module. Fixed in 4e0a88a4

### Release notes

Minor errors.

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

Close #1918

### CODE REVIEW

File: Modules/xASL_module_ASL.m [hunk 1]
```diff
@@ -606,6 +606,14 @@
 % First ensure that we don't use quantification parameters from other sequences
 x.Q = struct;
 
+% Load x.Q information from dataPar.json if available
```
Comment (HenkMutsaerts) [inline Modules/xASL_module_ASL.m]: So you say that we need this because of specific quantification settings; which are not part of BIDS rawdata. That is fine, but there is probably a reason that we cleaned x.Q two lines back; not to reuse the settings from other sequences.

So we either remove both 607 and this new part (and always use the x.Q from dataPar, loaded when loading dataPar at the start), or we need some way to make this session/subject specific (if we even need this)?

**Review by HenkMutsaerts — CHANGES_REQUESTED** [review]
Minor comment in xASL_module_ASL

File: Modules/xASL_module_ASL.m (hunk 1 above)
Comment (jan-petr) [reply Modules/xASL_module_ASL.m]: This is fully up to you. We need to load it somehow.

At the default location, it is really loaded only once at the start. So it can indeed accumulate and retain information. That's why you previously decided to clean it here. 

So I'm fine cleaning it at every subject and reloading x.Q here afterwards (i.e. the current solution).
I'm also fine not cleaning it and loading it only once (i.e. removing 607 and this new part). 

I don't think there's a good subject specific way without writing fully subject specific dataPar.json like we have for studyPar - which we can do in the future. So I wouldn't do this now as that would require considerable time.

**Review by HenkMutsaerts — APPROVED** [review]
