### PR TITLE
#2007 ut_master_exploreASL minor fix

### LINKED ISSUE #2007: Minor error in testing
### Description

Unit tests failed because incorrectly set.

### Release notes

Minor fix in unit tests.

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

Close #2007

### CODE REVIEW

File: Testing/UnitTests/xASL_ut_master_xASL_ExploreASL.m [hunk 1]
```diff
@@ -604,14 +604,14 @@
     if isfield(testContent,'x')
         if isfield(testContent.x,'S')
             if isfield(testContent.x.S,'Atlases')
-                if ~(numel(testContent.x.S.Atlases)==6)
+                if ~(numel(testContent.x.S.Atlases)==7)
```
Comment (HenkMutsaerts) [inline Testing/UnitTests/xASL_ut_master_xASL_ExploreASL.m:607]: Should we compare this with the number of atlas niftis inside the folders?

**Review by HenkMutsaerts — APPROVED** [review]
Minor question, you don't need to answer me :)

File: Testing/UnitTests/xASL_ut_master_xASL_ExploreASL.m (hunk 1 above)
Comment (jan-petr) [reply Testing/UnitTests/xASL_ut_master_xASL_ExploreASL.m:607]: No - this is not about the number of atlases available in the folders -> this is about double checking that the requested number of atlases (through input parameter) was correctly resolved. So fine like this and cannot be automated.
