### PR TITLE
Closes #978 Multi PLD quantification

### LINKED ISSUE #978: Fix multiPLD quantification
### Description

Fix several errors in multi-PLD quantification to make it work with general multi-PLD and Hadamard as well.

### Requirements

- [x] ASL module line 310 crashes for uneven number of volumes - we need to skip in case we have deltams
- [x] Make sure that multiple repetitions are treated correctly for multiPLD. ResampleASL line 265 - make averaging based on PLD vector and don't assume any specific PLD order.
- [x] Clean the code to make the multi-PLD uniquely for BASIL and remove the unused non-BASIL code.
- [x] Clear separation between multi-PLD and single-PLD calls of BASIL.
- [x] Make sure the correct PLDs are used for BASIL.
- [x] Correct all BASIL input and model parameters.
- [x] Configure BASIL for Look-Locker, multi-PLD, and Hadamard.
- [x] Output ATT maps from BASIL.
- [x] Full processing of ATT maps.

### How to test

Optional: insert description about how to test the code changes here

### Release notes

BASIL for multi-PLD, Look-Locker, and Hadamard. Correct BASIL configuration. Output ATT maps.

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

#978

### CODE REVIEW

File: Functions/xASL_quant_Basil.m [hunk 1]
```diff
@@ -59,21 +59,18 @@
     % FIXME would be good to have a brain mask at this point -> PM: if this would be a brainmask as well, we can skip creating a dummy input image here
     PWI(isnan(PWI)) = 0;
     
-    if size(PWI,4) == 1 
+    if (x.modules.asl.bTimeEncoded == 0) && (x.modules.asl.bMultiPLD == 0)
```
Comment (MichaelStritt) [inline Functions/xASL_quant_Basil.m:62]: Probably a stupid question, but we are sure that those sub-fields are always defined, right?

File: Modules/xASL_module_ASL.m [hunk 2]
```diff
@@ -187,6 +187,22 @@
 	x.Q.NumberEchoTimes = 1;
 end
 
+%% D6. DeltaM parsing - check if all/some volumes are deltams
```
Comment (MichaelStritt) [inline Modules/xASL_module_ASL.m:190]: We could add the D6 in the header description where the other sections are listed, too 😃

**Review by MichaelStritt — APPROVED** [review]
You nicely cleaned up the code. Especially the switch statements and the io of the functions seems a lot better now. All headers look fine. I added two minor comments. Would be good if someone with an FSL/BASIL installation (@BeatrizPadrela or @MDijsselhof) could test this though (either now or during the release testing).

File: Functions/xASL_quant_Basil.m (hunk 1 above)
Comment (jan-petr) [reply Functions/xASL_quant_Basil.m:62]: No - a very important question! Yes, they are always defined at the start of ASL_module, so that we don't have to check all the time if the field exist. These fields are not defined in dataPar, but rather derived at the start of the module from the data. Good that you check these things...

**Comment by jan-petr** [comment]
We have several flavors to test this with. I've tried them, but a re-test by others would be welcome:
These work nicely and give CBF and TT maps
- GE_PCASL_3Dspiral_25.0LX_eASLPLD3_1
- GE_PCASL_3Dspiral_25.0LX_eASLPLD7_1
- Philips_PCASL_2DEPI_5.6.1.2_Hadamard_1

These two crashes in FABBER as multi-TE is not yet supported - we will do that later
- Siemens_PCASL_3DGRASE_VD13A_Hadamard8FME_1
- Siemens_PCASL_3DGRASE_VD13A_Hadamard4FME_1

This one crashes badly, but the reason is that it doesn't have M0 and has BSup. And our BSup correction for M0 doesn't yet work for multi-PLD. I already created a future issue for that in 2.1.0
- Siemens_PCASL_3DGRASE_VB17A_multiPLD_1

This one used to crash because there are way too many volumes for motion correction. However, I have disabled motion correction for Look-Locker, so it should now run. And we will adapt the motion correction for Look-Locker in the future - an issue for that has been already created:
- Philips_PASL_2DEPI_5.4.0.2-LookLocker_1

@MichaelStritt Can you install FSL in WSL?
@BeatrizPadrela Can you test these yourself as well?
@MDijsselhof Can you test your testing set if it works?
@everybody: Any other ideas or testing data?

File: Modules/xASL_module_ASL.m (hunk 2 above)
Comment (jan-petr) [reply Modules/xASL_module_ASL.m:190]: Good point - added. I though about adding that already previously, and I knew that being lazy doesn't pay off and somebody will find out :D

File: Functions/xASL_quant_GetMeanControl.m [hunk 3]
```diff
@@ -36,29 +36,36 @@
...
-		% Find all dynamics with that PLD
-		imMeanControl = imMeanControl(:,:,:,Initial_PLD==idealPLD);
 	end
+	
+	% Sort the unique PLDs and pick the ideal PLD
+	idealPLD = sort(unique(Initial_PLD),'ascend');
+	
+	if (isfield(x.Q,'LookLocker') && x.Q.LookLocker) || x.modules.asl.bDeltaM
+		% For Look-Locker, get the middle one
+		idealPLD = idealPLD(round(numel(idealPLD)/2));
```
Comment (HenkMutsaerts) [inline Functions/xASL_quant_GetMeanControl.m:56]: We discussed with @MDijsselhof that it would be most comparable with single PLD to use the PLD closest to the white paper PLD (let's say closest to a PLD of 2000 ms).

Plus, this would decrease the variance between multiPLD types

File: Functions/xASL_quant_MultiPLD.m [hunk 4]
```diff
@@ -263,21 +221,19 @@
...
 
 %% 6    Print parameters used
 fprintf('%s\n',' model with parameters:');
 
 if x.Q.ApplyQuantification(3)
     switch lower(x.Q.LabelingType)
         case 'pasl'
-            fprintf('%s',['TI1 = ' num2str(x.Q.LabelingDuration) ' ms, ']);
-            fprintf('%s',['TI (ms) = ' num2str(x.Q.Initial_PLD')]);  % transpose for multiPLD
+            fprintf('%s\n',['TI1 = ' num2str(unique(x.Q.LabelingDuration(:)')) ' ms,']);
```
Comment (HenkMutsaerts) [inline Functions/xASL_quant_MultiPLD.m:232]: Perhaps nice to add to `xASL_num2str` that it will always do the `(:)'`.

File: Modules/SubModule_ASL/xASL_wrp_Quantify.m [hunk 5]
```diff
@@ -390,13 +390,14 @@ function xASL_wrp_Quantify(x, PWI_Path, OutputPath, M0Path, SliceGradientPath)
 
 %% ------------------------------------------------------------------------------------------------
 %% 8.   Perform Quantification
-if size(PWI,4) == 1 % single PLD quantification
+if (x.modules.asl.bTimeEncoded == 0) && (x.modules.asl.bMultiPLD == 0)% single PLD quantification
```
Comment (HenkMutsaerts) [inline Modules/SubModule_ASL/xASL_wrp_Quantify.m:393]: same as above

File: Modules/SubModule_ASL/xASL_wrp_Quantify.m [hunk 6]
```diff
@@ -390,13 +390,14 @@ function xASL_wrp_Quantify(x, PWI_Path, OutputPath, M0Path, SliceGradientPath)
...
     fprintf('%s\n',['Performing single PLD quantification']);
     [~, CBF] = xASL_quant_SinglePLD(PWI, M0_im, SliceGradient, x, x.Q.bUseBasilQuantification); % also runs BASIL, but only in native space!
+	ATT = [];
```
Comment (HenkMutsaerts) [inline Modules/SubModule_ASL/xASL_wrp_Quantify.m:396]: or `NaN`?

File: Modules/SubModule_ASL/xASL_wrp_Quantify.m [hunk 7]
```diff
@@ -421,6 +422,15 @@ function xASL_wrp_Quantify(x, PWI_Path, OutputPath, M0Path, SliceGradientPath)
 
 xASL_io_SaveNifti(PWI_Path, OutputPath, CBF, 32, 0);
 
+if ~isempty(ATT)
```
Comment (HenkMutsaerts) [inline Modules/SubModule_ASL/xASL_wrp_Quantify.m:425]: Perhaps nicer to have `pathOutput_CBF` and `pathOutput_ATT` from the start of this wrapper, this is a bit quick and dirty

File: Modules/SubModule_ASL/xASL_wrp_Quantify.m [hunk 8]
```diff
@@ -456,5 +466,8 @@ function xASL_wrp_Quantify(x, PWI_Path, OutputPath, M0Path, SliceGradientPath)
     end
     
     xASL_spm_deformations(x, {x.P.Path_CBF}, {x.P.Pop_Path_CBF}, [], [], AffineTransfPath, x.P.Path_y_ASL);
+	if xASL_exist(x.P.Path_TT,'file')
+		xASL_spm_deformations(x, {x.P.Path_TT}, {x.P.Pop_Path_TT}, [], [], AffineTransfPath, x.P.Path_y_ASL);
```
Comment (HenkMutsaerts) [inline Modules/SubModule_ASL/xASL_wrp_Quantify.m:470]: Should it be `Path_ATT` instead? `Path_TT` I used in the past for the FEAST output, we could clean this up in the future

File: Modules/SubModule_ASL/xASL_wrp_RealignASL.m [hunk 9]
```diff
@@ -61,21 +61,18 @@ function xASL_wrp_RealignASL(x,bSubtraction)
 PercExcl = NaN;
 MinimumtValue = NaN;
 
-if x.modules.asl.bMultiPLD || x.modules.asl.bMultiTE
+if x.modules.asl.bMultiPLD || x.modules.asl.bMultiTE || x.modules.asl.bDeltaM
```
Comment (HenkMutsaerts) [inline Modules/SubModule_ASL/xASL_wrp_RealignASL.m:64]: Not sure what `bDeltaM` is, but throughout ExploreASL it assumes that if `ASL4D` has only a single volume, this is a `deltaM` volume. Motion correction is disabled by default for a single volume.

BTW, why should ENABLE be disabled for DeltaM images? It should rather skip the subtraction.

Ah I think I now get it, you needed `bDeltaM` for GE eASL. But I would have created a separate issue for this then, because now parts of the pipeline use `bDeltaM` and other parts don't.

File: Modules/SubModule_ASL/xASL_wrp_ResampleASL.m [hunk 10]
```diff
@@ -220,6 +220,23 @@ function xASL_wrp_ResampleASL(x)
         % Apparently, subtraction was already done on the scanner/reconstruction
         fprintf('%s\n', PathPWI{iSpace});
         xASL_io_SaveNifti(PathASL{iSpace}, PathPWI{iSpace}, ASL_im, 32, false);
+	elseif x.modules.asl.bDeltaM
+		% We have subtraction images
```
Comment (HenkMutsaerts) [inline Modules/SubModule_ASL/xASL_wrp_ResampleASL.m:224]: Please be clear in the comments (like in a paper, otherwise the comments are not helpful!). You meant here that we don't have control-label images in the raw data, but only subtraction images, right?

(because otherwise, we always have subtraction images somewhere

File: Modules/SubModule_ASL/xASL_wrp_ResampleASL.m [hunk 11]
```diff
@@ -220,6 +220,23 @@ function xASL_wrp_ResampleASL(x)
         % Apparently, subtraction was already done on the scanner/reconstruction
         fprintf('%s\n', PathPWI{iSpace});
         xASL_io_SaveNifti(PathASL{iSpace}, PathPWI{iSpace}, ASL_im, 32, false);
+	elseif x.modules.asl.bDeltaM
+		% We have subtraction images 
+		
+		% For multi-PLD, save both PWI4D and PWI
```
Comment (HenkMutsaerts) [inline Modules/SubModule_ASL/xASL_wrp_ResampleASL.m:226]: Also for single PLD, we should save both! This should have been there already, why did you change this?

File: Modules/SubModule_ASL/xASL_wrp_ResampleASL.m [hunk 12]
```diff
@@ -249,20 +266,22 @@ function xASL_wrp_ResampleASL(x)
...
         % Average PWI - multiPLD
         if isfield(x.modules.asl,'bMultiPLD') && x.modules.asl.bMultiPLD 
-            % multiPLD PWI
-            nRepeatsPLD = size(ASL_im,4)/length(x.Q.Initial_PLD); % we still need to create a single Repeats in X struct
-			PWI = zeros(size(ASL_im,1), size(ASL_im,2), size(ASL_im,3), length(x.Q.Initial_PLD)); % preallocate PWI
-            for nPLD = 1:length(x.Q.Initial_PLD)
-                iStartRepeatsPLD = 1 + (nPLD-1) * nRepeatsPLD; % Location of the first repeat for a given single PLD
-                iEndRepeatsPLD = nPLD * nRepeatsPLD; % Location of the last repeat for a given single PLD
-                PWI(:,:,:,nPLD) = xASL_stat_MeanNan(ASL_im(:,:,:,iStartRepeatsPLD:iEndRepeatsPLD), 4); % Averaged PWI4D 
+			% Skip every second PLD due to the subtraction
```
Comment (HenkMutsaerts) [inline Modules/SubModule_ASL/xASL_wrp_ResampleASL.m:275]: what do you mean by this? this is confusing to me. You probably meant:

% Skip every other value because x.Q.Initial_PLD was stored for both control and label images and we need it now for the pairwise subtractions only

File: Modules/SubModule_ASL/xASL_wrp_ResampleASL.m [hunk 13]
```diff
@@ -249,20 +266,22 @@ function xASL_wrp_ResampleASL(x)
...
+			subtractedPLD = x.Q.Initial_PLD(1:2:end);
```
Comment (HenkMutsaerts) [inline Modules/SubModule_ASL/xASL_wrp_ResampleASL.m:276]: Confusing as well, you have not "subtracted PLDs". Plus, these are still initial PLDs right?

So how about `Initial_PLD_PWI` ?

File: Modules/SubModule_ASL/xASL_wrp_ResampleASL.m [hunk 14]
```diff
@@ -249,20 +266,22 @@ function xASL_wrp_ResampleASL(x)
...
+        
+			% After averaging across PLDs, we'll obtain these unique PLDs
```
Comment (HenkMutsaerts) [inline Modules/SubModule_ASL/xASL_wrp_ResampleASL.m:278]: Again here, please make the comment and the variable name clearer

File: Modules/xASL_module_ASL.m [hunk 15]
```diff
@@ -41,6 +41,7 @@
 % - D3. Multi-PLD parsing
 % - D4. TimeEncoded parsing
 % - D5. Multi-TE parsing
+% - D6. DeltaM parsing - check if all/some volumes are deltams
```
Comment (HenkMutsaerts) [inline Modules/xASL_module_ASL.m:44]: Nice, but then this should include that if we have a single volume only, we assume it is a `deltaM`

File: Modules/xASL_module_ASL.m [hunk 16]
```diff
@@ -187,6 +188,22 @@
 	x.Q.NumberEchoTimes = 1;
 end
 
+%% D6. DeltaM parsing - check if all/some volumes are deltams
+% If TSV file exist
+[pathDir, pathASL4D] = fileparts(x.P.Path_ASL4D);
+pathASL4Dcontext = fullfile(pathDir, [pathASL4D '_aslcontext.tsv']);
```
Comment (HenkMutsaerts) [inline Modules/xASL_module_ASL.m:194]: perhaps good to use the same file naming as the rest, so this would be `x.P.Path_ASL4Dcontext`. Even better if you can add this in the general file used for creating all paths (`xASL_ini_FileSystem`), so you don't have to repeat this in different places

File: Modules/xASL_module_ASL.m [hunk 17]
```diff
@@ -187,6 +188,22 @@
...
+% We don't have a subtraction image by default
```
Comment (HenkMutsaerts) [inline Modules/xASL_module_ASL.m:195]: Unless there is only a single volume

File: Modules/xASL_module_ASL.m [hunk 18]
```diff
@@ -187,6 +188,22 @@
...
+x.modules.asl.bDeltaM = 0;
+if xASL_exist(pathASL4Dcontext,'file')
+	% Load TSV file
+	aslContext = xASL_tsvRead(pathASL4Dcontext);
+	bidsPar = xASL_bids_Config;
+	% Check for presence of deltaM subtraction volumes
+	if numel(regexpi(strjoin(aslContext(2:end)),bidsPar.stringDeltaM)) > 0
```
Comment (HenkMutsaerts) [inline Modules/xASL_module_ASL.m:202]: Can we not find a better name for `stringDeltaM`? Is this supposed to contain a string with all `deltaM` volumes? Why not logic?

And if you have at least 1 deltaM (according to this `if` statement), does this mean that we assume that all `ASL4D` volumes are `deltaM`? In that case I would add a warning (unless vendor is GE perhaps)

**Review by HenkMutsaerts — CHANGES_REQUESTED** [review]
In general, this issue contains multiple issues, making it harder to review this.

`xASL_wrp_Resample` already saved both `PWI` and `PWI4D`, and it should still do this, irregardless of the number of PLDs. At the end of the quantification wrapper we delete PWI4D as it can take up quite some space. And for BASIL we always provide PWI4D, regardless the number of PLDs. (at least, this is how it should be and how I programmed this)

File: Functions/xASL_bids_parms2BIDS.m [hunk 19]
```diff
@@ -54,7 +54,7 @@
                           500        20000            10000         5000               5000                 5000            400               5000      500  5000       400                10000];% Maximum in ms   
 					  
 % Fields that are entered under the subfield 'Q' for xASL on the output
-xASLqFields = {'LabelingType' 'Initial_PLD' 'BackGrSupprPulses' 'LabelingDuration' 'SliceReadoutTime' 'NumberOfAverages' 'BloodT1'...
+xASLqFields = {'LabelingType' 'Initial_PLD' 'BackGrSupprPulses' 'LookLocker' 'LabelingDuration' 'SliceReadoutTime' 'NumberOfAverages' 'BloodT1'...
```
[the remark this answers is not in the document]
Comment (jan-petr) [reply Functions/xASL_bids_parms2BIDS.m:57]: Reference added. LookLocker is a BIDS field and is directly a data property. Makes no sense to change it to `bLookLocker`.

File: Functions/xASL_quant_Basil.m [hunk 20]
```diff
@@ -1,7 +1,7 @@
-function [CBF_nocalib, resultFSL] = xASL_quant_Basil(PWI, x)
+function [CBF_nocalib, ATT_map, resultFSL] = xASL_quant_Basil(PWI, x)
```
[the remark this answers is not in the document]
Comment (jan-petr) [reply Functions/xASL_quant_Basil.m:1]: Not sure what you talk about. `isvar` is not used in the function. We only check existence of ATT_map output from BASIL. That cannot be initialized, but has to be checked.

File: Functions/xASL_quant_Basil.m (hunk 1 above)
Comment (jan-petr) [reply Functions/xASL_quant_Basil.m:62]: Currently, we have multiPLD and TimeEncoded as two different things. I'm fine to redefine this and change this as TimeEncoded sub-case of multiPLD. But lets discuss this - note that these are internal parameters.

The second point. Makes sense to always save as PWI4D, but I didn't write this if-statement. Shall we completely remove it then?

File: Functions/xASL_quant_GetMeanControl.m [hunk 21]
```diff
@@ -36,29 +36,36 @@
...
     imMeanControl = imASLTimeSeries(:,:,:,1:blockSize:end);
-else
-	% Create mean control in native space (works also for multi-PLD)
-	imMeanControl = xASL_quant_GetControlLabelOrder(imASLTimeSeries);
 	
-	% For multi-PLD, we need to select one PLD
-	if isfield(x.modules.asl,'bMultiPLD') && x.modules.asl.bMultiPLD
+elseif isfield(x.modules.asl,'bMultiPLD') && x.modules.asl.bMultiPLD
+	% Create mean control in native space
+	if x.modules.asl.bDeltaM
```
[the remark this answers is not in the document]
Comment (jan-petr) [reply Functions/xASL_quant_GetMeanControl.m:42]: We should probably rename to `bContainsDeltaM`.
Yes, of course, it is automatically detected option. But we have the automatic detection centralized and then use this variable, instead of re-detecting at each point. 
Previously, this was wrong as it detected this as having a single volume - which is not with multi-PLD not an effective thing to do.

File: Functions/xASL_quant_MultiPLD.m [hunk 22]
```diff
@@ -56,7 +57,11 @@
 end
 
 if nargin<5 || isempty(bUseBasilQuantification)
-    bUseBasilQuantification = false;
+    bUseBasilQuantification = true;
+end
+
+if bUseBasilQuantification == false
```
[the remark this answers is not in the document]
Comment (jan-petr) [reply Functions/xASL_quant_MultiPLD.m:63]: Fixed

File: Functions/xASL_quant_MultiPLD.m [hunk 23]
```diff
@@ -105,14 +106,10 @@
...
-				if max(SliceReadoutTime)>0 && length(SliceReadoutTime) > 1
-					x.Q.BasilSliceReadoutTime = SliceReadoutTime(2)-SliceReadoutTime(1);
-				else
-					x.Q.BasilSliceReadoutTime = 0;
-				end
+			if max(SliceReadoutTime)>0 && length(SliceReadoutTime) > 1
+				x.Q.BasilSliceReadoutTime = SliceReadoutTime(2)-SliceReadoutTime(1);
 			else
-				ScaleImage = ScaleImage.*(x.Q.Initial_PLD + SliceReadoutTime(imSliceNumber)); % effective/net PLD            
+				x.Q.BasilSliceReadoutTime = 0;
```
[the remark this answers is not in the document]
Comment (jan-petr) [reply Functions/xASL_quant_MultiPLD.m:112]: No it shouldn't. Cause BASIL wouldn't read it then correctly - most likely.

File: Functions/xASL_quant_MultiPLD.m [hunk 24]
```diff
@@ -121,48 +118,9 @@
...
-                error('Unknown x.Q.nCompartments');
-        end
-
-
-        %% 3    Scaling to physiological units
-        ScaleImage = ScaleImage.*60000.*100.*x.Q.Lambda;
-        % (For some reason, GE sometimes doesn't need the 1 gr->100 gr conversion)
-        % & old Siemens sequence also didn't need the 1 gr->100 gr conversion
-    end
+	[PWI, ATT] = xASL_quant_Basil(PWI, x);
```
[the remark this answers is not in the document]
Comment (jan-petr) [reply Functions/xASL_quant_MultiPLD.m:123]: Yes. Known issue. We indeed plan to merge those. #867

File: Functions/xASL_quant_Basil.m [hunk 25]
```diff
@@ -89,19 +86,29 @@
     fprintf('%s\n', 'The following warning (if mentioned above) can be ignored:');
     fprintf('%s\n', '/.../fsl/bin/basil: line 124: imcp: command not found');
     
-    pathBasilMean = xASL_adm_GetFileList(dirBasilOutput, '^mean_ftiss\.nii$', 'FPListRec');
-    pathBasilMean = pathBasilMean{end}; % we assume the latest iteration (alphabetically) is optimal. also converting cell to char array
+    pathBasilCBF = xASL_adm_GetFileList(dirBasilOutput, '^mean_ftiss\.nii$', 'FPListRec');
+	if isempty(pathBasilCBF)
+		error('FSL BASIL failed');
```
[the remark this answers is not in the document]
Comment (jan-petr) [reply Functions/xASL_quant_Basil.m:91]: Yes. In a future issue.

File: Functions/xASL_quant_Basil.m [hunk 26]
```diff
@@ -89,19 +86,29 @@
...
        
-    CBF_nocalib = xASL_io_Nifti2Im(pathBasilMean);
+    CBF_nocalib = xASL_io_Nifti2Im(pathBasilCBF);
         
+	pathBasilATT = xASL_adm_GetFileList(dirBasilOutput, '^mean_delttiss\.nii$', 'FPListRec');
+	if ~isempty(pathBasilATT)
+		pathBasilATT = pathBasilATT{end}; % we assume the latest iteration (alphabetically) is optimal. also converting cell to char array
+		ATT_map = xASL_io_Nifti2Im(pathBasilATT);
+	else
+		ATT_map = [];
```
[the remark this answers is not in the document]
Comment (jan-petr) [reply Functions/xASL_quant_Basil.m:102]: Yes. And if ATT map is not calculated (single-PLD case), then we don't have missing values, but missing entire variable. Hence []. Or not?

File: Functions/xASL_quant_Basil.m [hunk 27]
```diff
@@ -123,170 +130,193 @@
 
 
 
-function [BasilOptions] = xASL_quant_Basil_Options(pathBasilOptions, x, PWI, bMultiPLD)
+function [BasilOptions] = xASL_quant_Basil_Options(pathBasilOptions, x, PWI)
```
[the remark this answers is not in the document]
Comment (jan-petr) [reply Functions/xASL_quant_Basil.m:133]: Yes. I already divided and restructured it. Now adding section numbers.

File: Functions/xASL_quant_Basil.m [hunk 28]
```diff
@@ -123,170 +130,193 @@
...
+%% Basic acquisition parameters
+
+% Labelling type - PASL or pCASL
+switch lower(x.Q.LabelingType)
+	case 'pasl'
+		fprintf('Basil: PASL model\n');
+		TIs = (unique(x.Q.Initial_PLD))'/1000;
+
+		% Print all the TIs
+		if x.modules.asl.bTimeEncoded || x.modules.asl.bMultiPLD
```
[the remark this answers is not in the document]
Comment (jan-petr) [reply Functions/xASL_quant_Basil.m:158]: As above.

File: Functions/xASL_quant_Basil.m [hunk 29]
```diff
@@ -123,170 +130,193 @@
...
+			% Bolus duration not know. If multi-TI, then try to infer it
+			if length(TIs) > 1
+				fprintf(FIDoptionFile, '--infertau\n');
+				fprintf('Basil: Infer bolus duration component\n')
+			end
+		end
+		
+	case {'casl','pcasl'}
+		fprintf(FIDoptionFile, '--casl\n');
+		fprintf('Basil: CASL/PCASL model\n');
```
[the remark this answers is not in the document]
Comment (jan-petr) [reply Functions/xASL_quant_Basil.m:184]: Done.

File: Functions/xASL_quant_Basil.m [hunk 30]
```diff
@@ -123,170 +130,193 @@
...
+		[PLDs, ind] = unique(x.Q.Initial_PLD);
+		PLDs = PLDs'/1000;
+		if length(x.Q.LabelingDuration)>1
+			LDs = (x.Q.LabelingDuration(ind))'/1000;
+		else
+			LDs = ones(size(PLDs))*x.Q.LabelingDuration/1000;
+		end
+		% For Time-encoded, we skip the first volume
+		if x.modules.asl.bTimeEncoded
+			PLDs = PLDs(2:end);
```
[the remark this answers is not in the document]
Comment (jan-petr) [reply Functions/xASL_quant_Basil.m:196]: We have this twice - for PASL and PCASL. And for PCASL, we need to do this for LD as well. So doing it at one location for PASL and PCASL with PLD would mess it up for LD. So I would keep this. Unless you see it more than twice.

File: Functions/xASL_quant_Basil.m [hunk 31]
```diff
@@ -123,170 +130,193 @@
...
 
-    
-    %% ATT and arterial component inference only possible with multi-PLD
-    if ~bMultiPLD
-        fprintf('Basil: Single-delay data - cannot infer ATT or arterial component\n');
-        x.Q.BasilInferATT = 0;
-        x.Q.BasilInferArt = 0;
-    end
+if isfield(x.Q,'LookLocker') && x.Q.LookLocker && isfield(x.Q,'FlipAngle')
+	fprintf(option_file, '--FA=%f\n', x.Q.FlipAngle);
```
[the remark this answers is not in the document]
Comment (jan-petr) [reply Functions/xASL_quant_Basil.m:221]: `LookLocker` - see above. Warning added for missing FlipAngle.

File: Functions/xASL_quant_Basil.m [hunk 32]
```diff
@@ -123,170 +130,193 @@
...
-        fprintf('Basil: Variable arterial component arrival time');
-    end
+fprintf(FIDoptionFile, '--save-model-fit\n');
 
+switch lower(x.Q.LabelingType)
+	case 'pasl'
+		% Default initial ATT for PASL is 0.7
+		fprintf(FIDoptionFile, '--bat=0.7\n');
+	case {'pcasl','casl'}
+		% Default initial ATT for PCASL is 1.3
```
[the remark this answers is not in the document]
Comment (jan-petr) [reply Functions/xASL_quant_Basil.m:237]: No. This is standard arrival time. `--bat` option defines it's initial value for fitting. But not after crushing thing, but normal arrival time. At least I understand it like this from the manual.

File: Functions/xASL_quant_GetMeanControl.m [hunk 33]
```diff
@@ -36,29 +36,36 @@
```
[the remark this answers is not in the document]
Comment (jan-petr) [reply Functions/xASL_quant_GetMeanControl.m:36]: As above. We shall discuss this on Monday meeting.

File: Functions/xASL_quant_GetMeanControl.m (hunk 3 above)
Comment (jan-petr) [reply Functions/xASL_quant_GetMeanControl.m:56]: Agree. Done.

File: Functions/xASL_quant_MultiPLD.m (hunk 4 above)
Comment (jan-petr) [reply Functions/xASL_quant_MultiPLD.m:232]: I have tested `xASL_num2str` and it doesn't do the (:)' automatically. 

`xASL_num2str([1;2;3])

ans =

  3×1 char array

    '1'
    '2'
    '3'`

File: Modules/SubModule_ASL/xASL_wrp_Quantify.m (hunk 7 above)
Comment (jan-petr) [reply Modules/SubModule_ASL/xASL_wrp_Quantify.m:425]: Agree done.

File: Modules/SubModule_ASL/xASL_wrp_Quantify.m (hunk 8 above)
Comment (jan-petr) [reply Modules/SubModule_ASL/xASL_wrp_Quantify.m:470]: Up to you, I have used the previous notation. But I'm fine to rename this. Do you want to use ATT for both FEAST and non-FEAST?

File: Modules/SubModule_ASL/xASL_wrp_RealignASL.m (hunk 9 above)
Comment (jan-petr) [reply Modules/SubModule_ASL/xASL_wrp_RealignASL.m:64]: bDeltaM == bContainsDeltaM . It tries to distinguish sequences containing deltaM from those containing control/labels.

Yes, the assumption that single-volume ASL4D has a deltaM is wrong - that's why I had to change this. GE multi-PLD has multiple deltaMs.

ENABLE needs to be disabled for deltaM as either it is a single volume, or it is multi-PLD and you can't start removing certain PLDs. DeltaM == true when the original sequence already contains the subtractions.

Yes - you got it right. We perhaps need an extra issue to use bDeltaM everywhere. But I needed to do this here - cause I couldn't split the multi-PLD eASL implementation to two issues - that wouldn't be possible to test. I can use bDeltaM everywhere - in this issue, or in a different issue?

File: Modules/SubModule_ASL/xASL_wrp_ResampleASL.m (hunk 10 above)
Comment (jan-petr) [reply Modules/SubModule_ASL/xASL_wrp_ResampleASL.m:224]: Good point. Thanks ;)

File: Modules/SubModule_ASL/xASL_wrp_ResampleASL.m (hunk 11 above)
Comment (jan-petr) [reply Modules/SubModule_ASL/xASL_wrp_ResampleASL.m:226]: OK. Will do that. But it wasn't really me who changed that.

File: Modules/SubModule_ASL/xASL_wrp_ResampleASL.m (hunk 12 above)
Comment (jan-petr) [reply Modules/SubModule_ASL/xASL_wrp_ResampleASL.m:275]: Yes! Corrected.

File: Modules/SubModule_ASL/xASL_wrp_ResampleASL.m (hunk 13 above)
Comment (jan-petr) [reply Modules/SubModule_ASL/xASL_wrp_ResampleASL.m:276]: Good point. Modified.

File: Modules/SubModule_ASL/xASL_wrp_ResampleASL.m (hunk 14 above)
Comment (jan-petr) [reply Modules/SubModule_ASL/xASL_wrp_ResampleASL.m:278]: Good point. Modified.

File: Modules/xASL_module_ASL.m (hunk 15 above)
Comment (jan-petr) [reply Modules/xASL_module_ASL.m:44]: Good point!!! Will do that - see comments above.

File: Modules/xASL_module_ASL.m (hunk 16 above)
Comment (jan-petr) [reply Modules/xASL_module_ASL.m:194]: Good point. Will do.

File: Modules/xASL_module_ASL.m (hunk 17 above)
Comment (jan-petr) [reply Modules/xASL_module_ASL.m:195]: Agree. Will change.

File: Modules/xASL_module_ASL.m (hunk 18 above)
Comment (jan-petr) [reply Modules/xASL_module_ASL.m:202]: this you got wrong. `bidsPar` is a function and variable where we set all the default variable and tag names for BIDS and also set all the dependencies so that they are configured in a single file and easily resolved.

So `bidsPar.stringDeltaM` contains the string `deltam` so that in case this is changed in BIDS, we only have to change it in the `xASL_bids_Config` ? That OK? This has been there for half a year ;)

If we have a mixture of control/label/deltaM, then we are doomed - we don't really support these more complex stuff. Lets add a warning and implement late?

File: Modules/xASL_module_ASL.m (hunk 17 above)
Comment (jan-petr) [reply Modules/xASL_module_ASL.m:195]: On the other hand. A single volume will still have deltam in the context, so we don't need to program this option as this already works. ASLcontext always have to be present and is checked in import.

File: Functions/xASL_bids_parms2BIDS.m (hunk 19 above)
[the remark this answers is not in the document]
Comment (MichaelStritt) [reply Functions/xASL_bids_parms2BIDS.m:57]: I agree with Jan here.

File: Functions/xASL_quant_Basil.m (hunk 20 above)
[the remark this answers is not in the document]
Comment (MichaelStritt) [reply Functions/xASL_quant_Basil.m:1]: Couldn't find `isvar` either.

File: Functions/xASL_quant_Basil.m [hunk 34]
```diff
@@ -123,170 +130,193 @@
...
+		else
+			LDs = ones(size(PLDs))*x.Q.LabelingDuration/1000;
+		end
+		% For Time-encoded, we skip the first volume
+		if x.modules.asl.bTimeEncoded
+			PLDs = PLDs(2:end);
+			LDs = LDs(2:end);
+		end
+		
+		if x.modules.asl.bTimeEncoded || x.modules.asl.bMultiPLD
```
[the remark this answers is not in the document]
Comment (MichaelStritt) [reply Functions/xASL_quant_Basil.m:206]: I don't get it, I thought we can have multiple TIs and TEs @BeatrizPadrela ?

File: Functions/xASL_quant_Basil.m (hunk 1 above)
Comment (HenkMutsaerts) [reply Functions/xASL_quant_Basil.m:62]: We discussed this multiple times, and I have always emphasized that bMultiPLD should be true when bTimeEncoded is true. So TimeEncoded is a special case of multiPLD, this is to make life simpler. Throughout the pipeline, both multiPLD and TimeEncoded do exactly the same, except for a few locations only — e.g., when you decode Hadamard volumes into multiPLD volumes.

The change is probably small: we should:
1) verify at the start of the ASL module that this is the case
2) any time that you request bMultiPLD OR bTimeEncoded, you remove bTimeEncoded

Yes, I think I wrote this if-statement because it didn't work with PWI4D or something similar. If this is easy changed it would be good, otherwise we can do this later.

Most important probably is to do the comparison with Martin Craig.

File: Functions/xASL_bids_parms2BIDS.m (hunk 19 above)
[the remark this answers is not in the document]
Comment (HenkMutsaerts) [reply Functions/xASL_bids_parms2BIDS.m:57]: Ah OK, just note that we use it internally as a boolean, whereas BIDS fields usually contain (more) information. E.g., we also use `bMultiPLD`, whereas this also has a BIDS field (though bit more complicated). I'm fine either way, we should just be consistent, and it should be clear what datatype a variable is (that's why I like `bLookLocker`, the b tells you that this is a boolean/logical.

File: Functions/xASL_quant_Basil.m (hunk 20 above)
[the remark this answers is not in the document]
Comment (HenkMutsaerts) [reply Functions/xASL_quant_Basil.m:1]: What I mean, is that if there is no output from BASIL (e.g., with singlePLD), you will use `NaN` for ATT_map. To avoid the need of `if ~exist(ATT_map,'var');ATT_map = NaN; end` at the end, you can initialize `ATT_map` with `NaN` at the start. This is useful as singlePLD should still be the default (unless multiPLD is specifically designated).

[the remark this answers is not in the document]
Comment (HenkMutsaerts) [reply Functions/xASL_quant_Basil.m:1]: Currently we would need something like `isvar` (probably `exist(,'var')` instead) at the end. I want to avoid this. But it wasn't there, I was just giving this as example. If by whatever if statements that are skipped, the function end is reached, we need to catch `ATT_map` not existing as variable. Better (cleaner, easier to read and debug) to initialize this at the beginning.

File: Functions/xASL_quant_Basil.m (hunk 34 above)
[the remark this answers is not in the document]
Comment (HenkMutsaerts) [reply Functions/xASL_quant_Basil.m:206]: Hadamard/TimEncoded is a subtype of multiPLD, these are all labeling strategies. Multiple TEs (multiple echo times) is a type of readout. Has nothing to do with TimeEncoding (though I understand your confusion ;)

File: Functions/xASL_quant_GetMeanControl.m (hunk 21 above)
[the remark this answers is not in the document]
Comment (HenkMutsaerts) [reply Functions/xASL_quant_GetMeanControl.m:42]: Yes if you also add `bContainsLookLocker` ;)

File: Functions/xASL_quant_Basil.m (hunk 26 above)
[the remark this answers is not in the document]
Comment (HenkMutsaerts) [reply Functions/xASL_quant_Basil.m:102]: We could discuss how we want to standardize this, but usually it is `NaN`. Think of the variable always having to be numeric, so you can calculate it and the pipeline will never crash (which you can with NaN). When you have no variable, you need a lot of `if statements`. So I would go for `NaN` like we use in many other situations.

File: Functions/xASL_quant_Basil.m (hunk 30 above)
[the remark this answers is not in the document]
Comment (HenkMutsaerts) [reply Functions/xASL_quant_Basil.m:202]: OK perhaps just nice to avoid 1 extra PLD or LD variable and do this at a single location. Is easier to read for others, you can then do this at the top of the function with the admin, so you don't have to through the function.

File: Functions/xASL_quant_Basil.m (hunk 32 above)
[the remark this answers is not in the document]
Comment (HenkMutsaerts) [reply Functions/xASL_quant_Basil.m:247]: OK but then it is really short. Note that it should be more around 2 seconds for clinical populations. I agree that we should do the same as the FSL group does.

File: Functions/xASL_quant_MultiPLD.m (hunk 4 above)
Comment (HenkMutsaerts) [reply Functions/xASL_quant_MultiPLD.m:232]: I meant to add this feature to xASL_num2str as we probably want this in all cases. Read my comment, I said "add to `xASL_num2str`, I didn't say "add `xASL_num2str`" :)

File: Modules/SubModule_ASL/xASL_wrp_Quantify.m (hunk 8 above)
Comment (HenkMutsaerts) [reply Modules/SubModule_ASL/xASL_wrp_Quantify.m:472]: Perhaps use something that works for now, and soon update to BIDS terminology?

File: Modules/SubModule_ASL/xASL_wrp_RealignASL.m (hunk 9 above)
Comment (HenkMutsaerts) [reply Modules/SubModule_ASL/xASL_wrp_RealignASL.m:64]: OK I agree.

I would have liked splitting this issue in multiple issues, e.g., `bDeltaM` should be a separate issue at all (not only halfly implementing it in this issue and fixing it in another ;)

But I'm fine either way. If you want to do this properly, search for `nVolumes>1` or something similarly, especially in the realign function.

File: Modules/xASL_module_ASL.m (hunk 18 above)
Comment (HenkMutsaerts) [reply Modules/xASL_module_ASL.m:202]: The mixture of `control-label-deltaM` is realistic. I'm fine with all this, as long as we add proper warnings in place!

File: Modules/xASL_module_ASL.m (hunk 17 above)
Comment (HenkMutsaerts) [reply Modules/xASL_module_ASL.m:195]: Yes, but then this needs to be automated in the import, always putting 1 volume to `deltaM` with a warning, if `ASLcontext` wasn't provided yet.

File: Functions/xASL_bids_parms2BIDS.m (hunk 19 above)
[the remark this answers is not in the document]
Comment (jan-petr) [reply Functions/xASL_bids_parms2BIDS.m:57]: Yes. The BIDS field `LookLocker` is a boolean. So the use is consistent. OK to resolve the issue?!

File: Functions/xASL_quant_Basil.m (hunk 20 above)
[the remark this answers is not in the document]
Comment (jan-petr) [reply Functions/xASL_quant_Basil.m:1]: As previously discussed - we keep this as it is. Can you resolve?!

File: Functions/xASL_quant_Basil.m (hunk 1 above)
Comment (jan-petr) [reply Functions/xASL_quant_Basil.m]: Fixed bTimeEncoded being always bMultiPLD a10bfd4

File: Functions/xASL_quant_Basil.m (hunk 34 above)
[the remark this answers is not in the document]
Comment (jan-petr) [reply Functions/xASL_quant_Basil.m]: Done in a10bfd4

File: Functions/xASL_quant_Basil.m (hunk 26 above)
[the remark this answers is not in the document]
Comment (jan-petr) [reply Functions/xASL_quant_Basil.m:102]: Agreed that we keep it as it is, right? Can you resolve?

File: Functions/xASL_quant_Basil.m (hunk 30 above)
[the remark this answers is not in the document]
Comment (jan-petr) [reply Functions/xASL_quant_Basil.m:202]: Agreed that it is more transparent to keep as it is. Can you resolve this?

File: Functions/xASL_quant_Basil.m (hunk 32 above)
[the remark this answers is not in the document]
Comment (jan-petr) [reply Functions/xASL_quant_Basil.m:247]: Yes, short, but proposed by FSL. we might need to fine tune later. Also, that's the initial value and will be still optimized to match the data.

File: Functions/xASL_quant_GetMeanControl.m (hunk 33 above)
[the remark this answers is not in the document]
Comment (jan-petr) [reply Functions/xASL_quant_GetMeanControl.m:36]: Fixed in a10bfd4

File: Modules/SubModule_ASL/xASL_wrp_Quantify.m (hunk 5 above)
Comment (jan-petr) [reply Modules/SubModule_ASL/xASL_wrp_Quantify.m]: Done. a10bfd4

File: Modules/SubModule_ASL/xASL_wrp_Quantify.m (hunk 6 above)
Comment (jan-petr) [reply Modules/SubModule_ASL/xASL_wrp_Quantify.m:403]: We agreed on this?! Resolve?

File: Modules/SubModule_ASL/xASL_wrp_Quantify.m (hunk 8 above)
Comment (jan-petr) [reply Modules/SubModule_ASL/xASL_wrp_Quantify.m:472]: Yes. Can you resolve?

File: Functions/xASL_quant_GetMeanControl.m (hunk 21 above)
[the remark this answers is not in the document]
Comment (jan-petr) [reply Functions/xASL_quant_GetMeanControl.m]: `bDeltaM` renamed to `bContainsDeltaM` 312b844 .Can you resolve?

File: Functions/xASL_quant_MultiPLD.m (hunk 4 above)
Comment (jan-petr) [reply Functions/xASL_quant_MultiPLD.m:232]: New issue made for this. OK to resolve?
https://github.com/ExploreASL/ExploreASL/issues/995

File: Modules/SubModule_ASL/xASL_wrp_RealignASL.m (hunk 9 above)
Comment (jan-petr) [reply Modules/SubModule_ASL/xASL_wrp_RealignASL.m]: I have reviewed all use of `nVolumes` and either `bContainsDeltaM` is there or it doesn't need to be there. So we are OK to resolve this one.

File: Modules/SubModule_ASL/xASL_wrp_ResampleASL.m (hunk 11 above)
Comment (jan-petr) [reply Modules/SubModule_ASL/xASL_wrp_ResampleASL.m:226]: I've checked again the code and currently, it always save PWI and PWI4D with the exception of single-volume or single-PLD files, where it saves PWI.nii only. 

But BASIL, later on, tries to read PWI4D.nii and quantifies with that in preference and only goes to PWI when PWI4D is not there. So all works as it should.
OK to resolve?

**Comment by MichaelStritt** [comment]
### Open tasks

- [ ] Add `LookLocker` to dataPar markdown template https://github.com/ExploreASL/ExploreASL/pull/986#discussion_r767737279
- [ ] ASL context https://github.com/ExploreASL/ExploreASL/pull/986#discussion_r767751276
- [ ] Renaming https://github.com/ExploreASL/ExploreASL/pull/986#discussion_r767262642
- [ ] ASL context (single volume) https://github.com/ExploreASL/ExploreASL/pull/986#discussion_r767514654
- [ ] Add warning https://github.com/ExploreASL/ExploreASL/pull/986#discussion_r767512917


### Can be resolved

- [ ] PLD variable (discussed on monday) https://github.com/ExploreASL/ExploreASL/pull/986#discussion_r767250625
    ▶️ No fix necessary
- [ ] NaN default (discussed on monday) https://github.com/ExploreASL/ExploreASL/pull/986#discussion_r767260136
    ▶️ No fix necessary
- [ ] nVolumes and deltaM https://github.com/ExploreASL/ExploreASL/pull/986#discussion_r767261309
    ▶️ Fix https://github.com/ExploreASL/ExploreASL/pull/986/commits/312b84473c9bfb371dd24b40bda1a4d9df16bb34
- [ ] PWI and PWI4D https://github.com/ExploreASL/ExploreASL/pull/986#discussion_r767261525 
    ▶️  Fix https://github.com/ExploreASL/ExploreASL/pull/986/commits/9995c40c6459fd439ff1ce46bda19c1f33212a69

File: Modules/xASL_module_ASL.m (hunk 18 above)
Comment (MichaelStritt) [reply Modules/xASL_module_ASL.m:203]: The mix wouldn't be correct according to BIDS AFAIK, so the validation should already alert you. Right now we still recommend to run the BIDS validation. We don't say anywhere that we do perfect validation ourselves. If we start validating that stuff from start to finish, there are a hundred new issues you can theoretically open. That's not really part of this PR IMHO.

File: Functions/xASL_bids_parms2BIDS.m (hunk 19 above)
[the remark this answers is not in the document]
Comment (jan-petr) [reply Functions/xASL_bids_parms2BIDS.m:57]: It is x.Q field directly obtained from BIDS, not a dataPar field. Same as e.g. x.Q.BackgroundSuppression. I know that we have all those fields in dataParTemplate, but that's an obsolete thing. We have `Initial_PLD`, `readoutDim` and all those field in the Legacy format, which will only confuse the user - these things are now not supposed to be added through the dataPar.json, but they should be added through studyPar.json in the BIDS format. And we should remove all these from here in the future. 

So I can add LookLocker there for now, but that goes against our current philosophy.

File: Modules/xASL_module_ASL.m (hunk 17 above)
Comment (jan-petr) [reply Modules/xASL_module_ASL.m]: Agree. Added this warning.

File: Modules/xASL_module_ASL.m (hunk 18 above)
Comment (jan-petr) [reply Modules/xASL_module_ASL.m]: Vendors do all crazy things of putting `control` and `label` and `deltaM` and `cbf` in the same sequence. Besides, it is not strictly against BIDS definition to have all these there. I don't foresee why would anybody have some controls and some deltams in the same sequence that wouldn't be simply duplicite. But that's nowhere in our Flavors. I would thus recommend to make this BIDS check in the import and not here. I've made a new issue for that. One of the reasons why not to do it now is that we don't have any such flavors, we therefore don't know what to expect and how to properly react to that.

File: Modules/xASL_module_ASL.m (hunk 16 above)
Comment (jan-petr) [reply Modules/xASL_module_ASL.m]: I've checked this function and it needs a revamp. It creates a HUGE structure of 30.000 cells. 
I've made a new issue for that #1006 and I will add the ASL4Dcontext path there. It makes no sense to add this new path there quickly without revamping the function as it would only make it grow even more.

File: Functions/xASL_bids_parms2BIDS.m (hunk 19 above)
[the remark this answers is not in the document]
Comment (HenkMutsaerts) [reply Functions/xASL_bids_parms2BIDS.m:57]: Agree!

File: Modules/xASL_module_ASL.m (hunk 18 above)
Comment (HenkMutsaerts) [reply Modules/xASL_module_ASL.m]: Sounds good

File: Modules/SubModule_ASL/xASL_wrp_ResampleASL.m (hunk 11 above)
Comment (HenkMutsaerts) [reply Modules/SubModule_ASL/xASL_wrp_ResampleASL.m:226]: OK I updated this in #997

File: Functions/xASL_init_FileSystem.m [hunk 35]
```diff
@@ -159,6 +159,8 @@
     end
     x.P.Pop_Path_MaskVascular = fullfile(x.D.PopDir, ['MaskVascular_' x.P.SubjectID '_' x.P.SessionID '.nii']);
     x.P.Path_Pop_MaskSusceptibility = fullfile(x.D.PopDir, ['rMaskSusceptibility_' x.P.SubjectID '_' x.P.SessionID '.nii']);    
+	
+	x.P.Path_ASL4D_aslcontext = fullfile(Path{2},'ASL4D_aslcontext.tsv');
```
Comment (HenkMutsaerts) [inline Functions/xASL_init_FileSystem.m:163]: This filename is incorrect, in ExploreASL we currently exchange `asl` for `ASL4D`. So to be consistent:

BIDS -> legacy
`_asl.json` -> `ASL4D.json`
`_aslcontext.tsv` -> `ASL4Dcontext.tsv`

imho

File: Modules/SubModule_ASL/xASL_wrp_RealignASL.m [hunk 36]
```diff
@@ -61,21 +61,18 @@ function xASL_wrp_RealignASL(x,bSubtraction)
 PercExcl = NaN;
 MinimumtValue = NaN;
 
-if x.modules.asl.bMultiPLD || x.modules.asl.bMultiTE
+if x.modules.asl.bMultiPLD || x.modules.asl.bMultiTE || x.modules.asl.bContainsDeltaM
     % ENABLE is disabled if multiPLD/TE
```
Comment (HenkMutsaerts) [inline Modules/SubModule_ASL/xASL_wrp_RealignASL.m:65]: Change into:
`% ENABLE is temporary disabled if multiPLD/TE.`

Comment (HenkMutsaerts) [inline Modules/SubModule_ASL/xASL_wrp_RealignASL.m:65]: I would move `x.modules.asl.bContainsDeltaM` to a separate if-statement at the beginning of `xASL_wrp_RealignASL`, because in this case we want to skip motion correction completely right?

File: Modules/SubModule_ASL/xASL_wrp_RealignASL.m [hunk 37]
```diff
@@ -139,7 +136,7 @@ function xASL_wrp_RealignASL(x,bSubtraction)
 %     end
 
 % Run motion correction for corresponding case
-if nFrames>2 && bSubtraction && (x.modules.asl.bMultiPLD  ||  x.modules.asl.bMultiTE  || x.modules.asl.bTimeEncoded)
+if nFrames>2 && bSubtraction && (x.modules.asl.bMultiPLD  ||  x.modules.asl.bMultiTE)
```
Comment (HenkMutsaerts) [inline Modules/SubModule_ASL/xASL_wrp_RealignASL.m:139]: Incorrect, this is a check to state if we can run motion correction at all right, this is irrespective of multiPLD and multiTE...

Also, I don't know exactly what `bSubtraction` does here, this boolean is here to differentiate between `spm_realign` (`bSubtraction==false`) and `spm_realign` with zig-zag (`bSubtraction==true`).
We might replace `bSubtraction` by `bZigZag` for clarification

File: Modules/xASL_module_ASL.m [hunk 38]
```diff
@@ -150,15 +151,16 @@
 %% D4. TimeEncoded parsing
 % Check if TimeEncoded is defined
 if isfield(x.Q,'TimeEncodedMatrixType') || isfield(x.Q,'TimeEncodedMatrixSize') 
-    x.modules.asl.bTimeEncoded = 1;
+    x.modules.asl.bTimeEncoded = true;
```
Comment (HenkMutsaerts) [inline Modules/xASL_module_ASL.m:154]: We should add a warning here:

>> warning('We detected TimeEncoded data (e.g., Hadamard or Walsh), we will process this but this is still an experimental feature');

And similarly for multiPLD in this admin section:

>> warning('We detected multiPLD data, we will process this but this is still an experimental feature');

File: Modules/xASL_module_ASL.m [hunk 39]
```diff
@@ -323,7 +348,7 @@
             xASL_im_CenterOfMass(x.P.Path_ASL4D, OtherList, 10); % set CenterOfMass to lower accepted distance for when rerunning wrong registration
         end
 
-        if  nVolumes>1
+        if  nVolumes>1 && ~x.modules.asl.bContainsDeltaM && (~isfield(x.Q,'LookLocker') || (x.Q.LookLocker == 0))
             % Run motion Correction
             xASL_wrp_RealignASL(x);
```
Comment (HenkMutsaerts) [inline Modules/xASL_module_ASL.m:353]: Here we do check for `bContainsDeltaM`, but to be sure I would also do this inside `xASL_wrp_RealignASL`, only once, at the top of the wrapper where the admin is done. We can remove it elsewhere in `xASL_wrp_RealignASL`.

**Review by HenkMutsaerts — CHANGES_REQUESTED** [review]
Few minor fixes left

File: Modules/SubModule_ASL/xASL_wrp_RealignASL.m (hunk 36 above)
Comment (MichaelStritt) [reply Modules/SubModule_ASL/xASL_wrp_RealignASL.m]: 2ac98fc

File: Modules/xASL_module_ASL.m (hunk 38 above)
Comment (MichaelStritt) [reply Modules/xASL_module_ASL.m:155]: ccec3a5

Comment (MichaelStritt) [reply Modules/xASL_module_ASL.m:156]: a67a7bd

File: Modules/xASL_module_ASL.m (hunk 39 above)
Comment (MichaelStritt) [reply Modules/xASL_module_ASL.m:355]: I'll quickly try to implement what you want, but this isn't how reviewing should be done. We shouldn't stack feature request over feature request again and again.

Comment (MichaelStritt) [reply Modules/xASL_module_ASL.m:355]: 9256d4e

File: Modules/SubModule_ASL/xASL_wrp_Quantify.m [hunk 40]
```diff
@@ -71,9 +71,16 @@ function xASL_wrp_Quantify(x, PWI_Path, OutputPath, M0Path, SliceGradientPath)
...
-    OutputPath = x.P.Pop_Path_qCBF;
+
+if nargin<3 || isempty(pathOutputCBF)
+    pathOutputCBF = x.P.Pop_Path_qCBF;
 end
+% Define output path for ATT map based on the CBF output path
+% Replace CBF with ATT in the output path
+iStringCBF = regexpi(pathOutputCBF, 'CBF');
+iStringCBF = iStringCBF(end);
+pathOutputTT = [pathOutputCBF(1:(iStringCBF-1)) 'TT' pathOutputCBF((iStringCBF+3):end)];
```
Comment (MDijsselhof) [inline Modules/SubModule_ASL/xASL_wrp_Quantify.m:82]: 'TT' Is this a typo?

File: Modules/SubModule_ASL/xASL_wrp_Quantify.m (hunk 8 above)
Comment (MDijsselhof) [reply Modules/SubModule_ASL/xASL_wrp_Quantify.m:472]: I apologise for opening this again, but what is the difference? Both produce ATT maps?

File: Modules/SubModule_ASL/xASL_wrp_RealignASL.m (hunk 37 above)
Comment (MDijsselhof) [reply Modules/SubModule_ASL/xASL_wrp_RealignASL.m:143]: I agree this is unclear, maybe we should add comments for these `if` statements to show what is happening

File: Functions/xASL_quant_Basil.m [hunk 41]
```diff
@@ -123,170 +130,203 @@
...
+		else
+			% Bolus duration not know. If multi-TI, then try to infer it
+			if length(TIs) > 1
+				fprintf(FIDoptionFile, '--infertau\n');
+				fprintf('BASIL: Infer bolus duration component\n')
+			end
+		end
+		
+	case {'casl','pcasl'}
+		fprintf(FIDoptionFile, '--casl\n');
```
Comment (MDijsselhof) [inline Functions/xASL_quant_Basil.m:189]: Although this is fine, we should add `--pasl` to the PASL case to make it clear

File: Functions/xASL_quant_Basil.m [hunk 42]
```diff
@@ -123,170 +130,203 @@
...
+			end
+			for iTI = 1:length(TIs)
+				fprintf(FIDoptionFile, '--ti%d=%.2f\n', iTI, TIs(iTI));
+			end
+			
+		else
+			fprintf(FIDoptionFile, '--ti=%.2f\n', TIs);
+		end
+		
+		% Either print bolus duration or unspecify it
```
Comment (MDijsselhof) [inline Functions/xASL_quant_Basil.m:177]: Is this going correctly for multiple LDs? Or are we improving this later?

File: Functions/xASL_quant_Basil.m [hunk 43]
```diff
@@ -123,170 +130,203 @@
...
-    
-    %% ATT and arterial component inference only possible with multi-PLD
-    if ~bMultiPLD
-        fprintf('Basil: Single-delay data - cannot infer ATT or arterial component\n');
-        x.Q.BasilInferATT = 0;
-        x.Q.BasilInferArt = 0;
-    end
+% Right now, we assume that we have averaged over PLDs
+%fprintf(FIDoptionFile, '--repeats=%i\n', size(PWI, 4)/PLDAmount);
+fprintf(FIDoptionFile, '--repeats=1\n');
```
Comment (MDijsselhof) [inline Functions/xASL_quant_Basil.m:221]: Why, I thought we were going to supply BASIL with multiple repeats?

File: Functions/xASL_quant_Basil.m [hunk 44]
```diff
@@ -123,170 +130,203 @@
...
+	
+% Slice-timing
+fprintf(FIDoptionFile, '--slicedt=%f\n', x.Q.BasilSliceReadoutTime/1000);
+
+if isfield(x.Q,'LookLocker') && x.Q.LookLocker 
+	if isfield(x.Q,'FlipAngle')
+		fprintf(option_file, '--FA=%f\n', x.Q.FlipAngle);
+		fprintf('BASIL: Flip angle for Look-Locker readout: %f\n', x.Q.FlipAngle);
```
Comment (MDijsselhof) [inline Functions/xASL_quant_Basil.m:229]: I know of only fixed FA Look-Locker, but is it possible to have multiple FAs? Would complicate the reconstruction I would say, just curious

**Review by MDijsselhof — CHANGES_REQUESTED** [review]
Couple of questions!

File: Functions/xASL_quant_Basil.m (hunk 42 above)
Comment (MDijsselhof) [reply Functions/xASL_quant_Basil.m:177]: This is about the code below !

File: Modules/SubModule_ASL/xASL_wrp_Quantify.m (hunk 8 above)
Comment (jan-petr) [reply Modules/SubModule_ASL/xASL_wrp_Quantify.m:472]: No worries. There's no difference. It was just called TT previously, so while ATT is better, we will keep the initial name. And we also don't want to have both TT and ATT as this would be confusing.

There's of course a difference in the algorithms - one works with multi-PLD, the other with single-PLD and crusher ON/OFF. 

If that explains it, you can resolve this one.

File: Functions/xASL_init_FileSystem.m (hunk 35 above)
Comment (jan-petr) [reply Functions/xASL_init_FileSystem.m]: Very good comment! But we need to fix this everywhere ;) See this 26fa3e2d
Note that to properly test this, we will need to change flavors as well, and we can only do the full test upon merging with `develop` that has some new edits in import.

File: Modules/SubModule_ASL/xASL_wrp_RealignASL.m (hunk 37 above)
Comment (jan-petr) [reply Modules/SubModule_ASL/xASL_wrp_RealignASL.m]: Yes. Unclear. Plus it should have reused bZigZag assigned previously here :D This is now fixed.

`bSubtraction` was there previously, to activate ZigZag. This is now renamed to `bASL` and for non-ASL, `bZigZag` is turned off. And the whole `bZigZag` assignment is done above.

With all the above - makes no sense to rename `bSubtraction` to `bZigZag` as there are cases with `bSubtraction==1` that still have `bZigZag` off. Like if it contains deltaMs - is a subtraction-based technique, but ZigZag has to be off - this is all explained in the comment above and fixed in this commit: 3d240036

File: Modules/SubModule_ASL/xASL_wrp_RealignASL.m (hunk 36 above)
Comment (jan-petr) [reply Modules/SubModule_ASL/xASL_wrp_RealignASL.m]: The input parameter `bSubtraction` was confusing as it wasn't clear if this refers to the fact that input is 'already subtracted' or 'subtraction-based images'. I have changed that to `bASL` is it is literally only ASL that has this option true. And it is only an internal parameter. This way, we won't confuse it with the `bContainsDeltaM` parameter.

To your question: It's a bit more complex.
- bContainsDeltaM turns off ENABLE and ZigZag as both need control/labels currently
- multi-PLD turns of both as well as with ENABLE it will be really tricky to exclude something, and ZigZag needs to be specially adapted for multi-PLD - but that's temporarily.
- However, single-PLD and bContainsDeltaM with multiple averages (though not sure if we have such a flavor) can run motion correction with ENABLE=0 and ZigZag = 0.

Finally, bZigZag was ignored currently in the code and was assigned 'manually'. I have fixed that as well.

All in 3d240036

File: Modules/xASL_module_ASL.m (hunk 39 above)
Comment (jan-petr) [reply Modules/xASL_module_ASL.m:355]: See all my comments above. `bContainsDeltaM` by itself is not a reason not to run motion correction. It's a combination with other factors that disable or modify motion correction. So warning removed. And removed `bContainsDeltaM` from this if-statement - see explanations above.

File: Modules/SubModule_ASL/xASL_wrp_Quantify.m (hunk 40 above)
Comment (jan-petr) [reply Modules/SubModule_ASL/xASL_wrp_Quantify.m:82]: No it isn't - historically, we're having it this way and decided to keep it like this and only change it when BIDS-derivatives names are introduced.

Comment (jan-petr) [reply Modules/SubModule_ASL/xASL_wrp_Quantify.m:82]: See also my reply in the re-opened comment.

File: Functions/xASL_quant_Basil.m (hunk 43 above)
Comment (jan-petr) [reply Functions/xASL_quant_Basil.m:221]: Yes, in the future, we will always provide all repeats to the PWI4D for BASIL. But currently, we average and we would have to change it on several places and properly test. So currently, we keep it averaged with a single repeat and we have a new issue for this already.

File: Functions/xASL_quant_Basil.m (hunk 44 above)
Comment (jan-petr) [reply Functions/xASL_quant_Basil.m]: Good point. Look-Locker practically have a single-FA only per volume (or a single volume batch after a single labeling), but you can indeed have different FAs for different repetitions - like in QUASAR. Currently, BASIL seems to accept only a single FA value here, and QUASAR has it's own quantification function. So since almost nobody uses Look-Locker, and nobody uses QUASAR, no point implementing QUASAR now and we can leave it here for single FA. I added a warning though: 4dffd3ca

File: Functions/xASL_quant_Basil.m (hunk 42 above)
Comment (jan-petr) [reply Functions/xASL_quant_Basil.m:178]: Good point. For PASL, the labeling duration is not defined by its actual duration (cause that is almost instantaneous) but by the timing of the bolus saturation pulse. And I guess that this doesn't really differ for multi-PLD sequences - or at least we don't really have the example for this. Still a valid point and I'll add a warning for future possible cases! Fixed here: 4dffd3ca

File: Functions/xASL_quant_Basil.m (hunk 41 above)
Comment (jan-petr) [reply Functions/xASL_quant_Basil.m:194]: Good point. But PASL is the default option and it doesn't need to be added to the config file. Besides, that option doesn't exist ;)
I added some explanatory comments to the code here: 4dffd3ca

**Comment by MichaelStritt** [comment]
@jan-petr, @BeatrizPadrela, @MDijsselhof & @HenkMutsaerts: Let's merge as is and test in release branch. Easier and better IMHO 👍

**Review by MDijsselhof — APPROVED** [review]

**Review by BeatrizPadrela — APPROVED** [review]

File: Functions/xASL_init_FileSystem.m (hunk 35 above)
Comment (HenkMutsaerts) [reply Functions/xASL_init_FileSystem.m]: Sure, we will revamp this anyway when going fully to BIDS. But nice if we can keep ourselves adherent to BIDS as much as possible, that will make the future changes smaller.

File: Modules/SubModule_ASL/xASL_wrp_RealignASL.m (hunk 37 above)
Comment (HenkMutsaerts) [reply Modules/SubModule_ASL/xASL_wrp_RealignASL.m]: Well you can say the same for `bASL`, there are also cases where `bASL` is true and `bZigZag` is off.
I would keep it simplier.

We need as options inside `xASL_wrp_Realign`:
`bMotionCorrection`
`bSubtraction` (used previously only to switch between ZigZag off-on) -> `bZigZag`
`bENABLE`

In the header of `xASL_wrp_Realign`, we set these three options based on the type of ASL (`bMultiPLD`, `bContainsDeltaM`, `bMultiTE`, etc)

File: Modules/SubModule_ASL/xASL_wrp_RealignASL.m (hunk 36 above)
Comment (HenkMutsaerts) [reply Modules/SubModule_ASL/xASL_wrp_RealignASL.m]: See below.

File: Modules/xASL_module_ASL.m (hunk 39 above)
Comment (HenkMutsaerts) [reply Modules/xASL_module_ASL.m:355]: See above. Let's replace this by `bMotionCorrection` and `bZigzag` et, which we all parse nicely in the header. Then it's easier to discuss what needs to happen and you don't have to read the whole code to understand this.

File: Modules/SubModule_ASL/xASL_wrp_Quantify.m (hunk 8 above)
Comment (HenkMutsaerts) [reply Modules/SubModule_ASL/xASL_wrp_Quantify.m:472]: > @jan-petr, @BeatrizPadrela, @MDijsselhof & @HenkMutsaerts: Let's merge as is and test in release branch. Easier and better IMHO 👍

We should first agree on the structure, then test this branch, and then test the release branch. But we can fuse the last two to speed things up, for now. And we could move things to a new issue.

But the clarity in `xASL_wrp_Realign` what is done when, is something I would like to implement now, saves time testing and discussing.

File: Functions/xASL_init_FileSystem.m (hunk 35 above)
Comment (jan-petr) [reply Functions/xASL_init_FileSystem.m]: Sure. But can you resolve this?! ;)

File: Modules/SubModule_ASL/xASL_wrp_RealignASL.m (hunk 37 above)
Comment (jan-petr) [reply Modules/SubModule_ASL/xASL_wrp_RealignASL.m]: That's not what is described in the header. Header say bSubtraction == bASL == ASL yes/no

Yes, we have now both `bZigZag` and `bASL`. We don't need `bMotionCorrection`, all is motion corrected. We only turn of ZigZag, but not depending on function parameters, but on data parameters. We need to keep this transparent and adjust based on data. To me, it makes no sense to start gluing up extra functionality - that's what you always protest against ;)

File: Modules/xASL_module_ASL.m (hunk 39 above)
Comment (jan-petr) [reply Modules/xASL_module_ASL.m:355]: Makes no sense to me. We moved all the details inside wrappers to keep ASL-module clean. It doesn't make sense to start moving things back from wrappers again.

`bContainsDeltaM` is now removed from here. And we can remove `nVolumes` and `LookLocker` and put it inside the wrapper if you want. But any larger changes do not make sense here.

Comment (HenkMutsaerts) [reply Modules/xASL_module_ASL.m:355]: Not outside the wrapper, just to the header of the wrapper

Comment (jan-petr) [reply Modules/xASL_module_ASL.m:355]: I see. Sorry, missed that. Yes, we can move that in.

File: Modules/SubModule_ASL/xASL_wrp_RealignASL.m (hunk 37 above)
Comment (MichaelStritt) [reply Modules/SubModule_ASL/xASL_wrp_RealignASL.m]: If you want to change functionality without messing up things with too much backwards compatibility, we can just tackle this in the next major release. For me the current header and descriptions seem pretty clear.

File: Modules/xASL_module_ASL.m (hunk 39 above)
Comment (jan-petr) [reply Modules/xASL_module_ASL.m]: Fixed 791df878

**Review by HenkMutsaerts — APPROVED** [review]
I added 2 commits, for clarity and to avoid running through `xASL_wrp_Realign` when `bMotionCorrection`
