### PR TITLE
Bug #1201 ge import

### LINKED ISSUE #1201: Testing GE_RX28 MS HongKong
### Description

Testing the flavor merged in #1170.

### Tasks

- [ ] `aslcontext` gives twice an `m0scan`, and `asl.nii.gz` contains 2 M0 volumes
- [ ] error:
>> xASL_Move: skip: destination exists: /Users/henk/ExploreASL/FlavorDatabase/GE_PCASL_3Dspiral_RX28.02_1/derivatives/ExploreASL/temp/Sub124/ASL_1/ASL4D_4_.nii
xASL_Move: skip: destination exists: /Users/henk/ExploreASL/FlavorDatabase/GE_PCASL_3Dspiral_RX28.02_1/derivatives/ExploreASL/temp/Sub124/ASL_1/ASL4D_4_.json

- [ ] Somehow `"ArterialSpinLabelingType": "PCASL" (`studyPar.json`) was incorrectly set to `"ArterialSpinLabelingType": "PCASL" (`ASL.json`)
- [ ] PLD should be 2025 according to the protocol PDF file but 1525 was found by conversion (`ASL.json`)?

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

Closes #1201 

1. Images are fine.
2. PLD taken as 2025ms from studyPar
3. CASL is correctly overwritten by PCASL from studyPar
4. Bsup - make up your mind if you want it or not.

### CODE REVIEW

**Review by HenkMutsaerts — CHANGES_REQUESTED** [review]
CASL is still not overwritten by PCASL, perhaps you forgot to commit that change?
Otherwise, I'm happy. Let me know when I can tell the Hong Kong guys that they can use the develop branch.

**Comment by HenkMutsaerts** [comment]
Now we understand one another :)
I printed below my `FlavorDatabase/GE_PCASL_3Dspiral_RX28.02_1/derivatives/ExploreASL/temp/Sub124/ASL_1/ASL4D.json`, can you compare with yours? Perhaps there are other differences? The dcm2nii version seems to be correct.

{"Modality":"MR",
"MagneticFieldStrength":3,
"ImagingFrequency":127.757,
"Manufacturer":"GE",
"ManufacturersModelName":"SIGNA Premier",
"BodyPartExamined":"BRAIN",
"PatientPosition":"HFS",
"SoftwareVersions":"28\\LX\\MR Software release:RX28.0_R02_1946.a",
"MRAcquisitionType":"3D",
"ScanningSequence":"RM",
"SequenceVariant":"NONE",
"ScanOptions":"SAT_GEMS\\EDR_GEMS\\SPIRAL_GEMS\\FS",
"PulseSequenceName":"ASL",
"SeriesNumber":4,
"AcquisitionTime":"NaN",
"AcquisitionNumber":1,
"SliceThickness":4,
"SpacingBetweenSlices":4,
"SAR":0.688305,
"EchoTime":0.0528,
"RepetitionTime":4.678,
"FlipAngle":111,
"ShimSetting":[84,-67,-199],
"PrescanReuseString":"Coil/s1",
"CoilString":"48HAP",
"ArterialSpinLabelingType":"CASL",
"LabelingDuration":1.45,
"NumberOfPointsPerArm":512,
"NumberOfArms":8,
"PercentPhaseFOV":100,
"PercentSampling":100,
"AcquisitionMatrixPE":8,
"ReconMatrixPE":128,
"ParallelReductionFactorInPlane":2,
"PixelBandwidth":976.562,
"ImageOrientationPatientDICOM":[1,0,0,0,1,0],
"InPlanePhaseEncodingDirectionDICOM":"COL",
"ConversionSoftware":"dcm2niix",
"ConversionSoftwareVersion":"v1.0.20220720",
"RescaleSlope":1,
"RescaleSlopeOriginal":1,
"MRScaleSlope":1,
"RescaleIntercept":0,
"AcquisitionMatrix":512,
"Rows":[128,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
"Columns":[128,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
"NumberOfTemporalPositions":1,
"EffectiveEchoSpacing":[],
"GELabelingDuration":1.45,
"InversionTime":1.525,
"GELabelingType":"ASL",
"InPlanePhaseEncodingDirection":"COL",
"TotalReadoutTime":[],
"RepetitionTimePreparation":4.678,
"TotalAcquiredPairs":3,
"ASLContext":"m0scan,deltam"}

**Comment by HenkMutsaerts** [comment]
If I compare `/FlavorDatabase/GE_PCASL_3Dspiral_RX28.02_1/rawdata/sub-Sub124/perf/sub-Sub124_asl.json` with the reference, I get two differences:

-"ScanningSequence":"RM\\IR",
+"ScanningSequence":"RM",
-"ArterialSpinLabelingType":"PCASL",
+"ArterialSpinLabelingType":"CASL",

**Comment by jan-petr** [comment]
Bug identified - when merging 2 parts of NII in DICOM2NII, we merge also JSONs, but without prioritizing ASL part over M0 - this has to change as the M0 part has errors in it.

File: Functions/BIDS/xASL_bids_MergeNifti_Merge.m [hunk 1]
```diff
@@ -75,17 +83,30 @@
...
-
+	%% Merge all the JSONs according to their priority
+	
+	% Create an order in which the JSONs are going to be read
+	[~, priorityListIndex] = sort(priorityList);
+	outputJSON = struct();
+	for iJSON = 1:length(NiftiPaths)
+		% Go through the JSONs in increasing priority
+		[Fpath, Ffile] = xASL_fileparts(NiftiPaths{priorityListIndex(iJSON)});
+		if xASL_exist(fullfile(Fpath,[Ffile '.json']), 'file')
```
Comment (HenkMutsaerts) [inline Functions/BIDS/xASL_bids_MergeNifti_Merge.m:97]: What happens if this file is in the NIfTIPaths list but not existing?

File: Functions/BIDS/xASL_bids_MergeNifti.m [hunk 2]
```diff
@@ -214,6 +217,20 @@
 		return;
 	end
 	
+	% Set priorities for merging JSONs, higher number = higher priority
```
Comment (HenkMutsaerts) [inline Functions/BIDS/xASL_bids_MergeNifti.m:220]: This is a bit tricky perhaps.

1) Note that in the case of GE, it is a deltaM image, not CBF (which it spits out separately). So deltaM should probably go before m0scan. And control/label as well?
2) I don't think we should generalize this. For BIDS, we want to keep NIfTIs as how they were acquired. GE/dcm2niiX just has a bug by splitting their single sequence here. Siemens as well I guess. But the generalized solution is to keep the output as it was.

File: Functions/BIDS/xASL_bids_MergeNifti_Merge.m [hunk 3]
```diff
@@ -130,19 +151,14 @@
...
             % Write changes to JSON
-            structFirstJSON = spm_jsonread(firstJSON);
-            structFirstJSON.EchoTime = EchoTimes;
-            spm_jsonwrite(firstJSON, structFirstJSON);
-        end
-        % Copy the first JSON to this name
-        if ~isempty(firstJSON)
-            xASL_Copy(firstJSON,fullfile(Fpath,[nameMerged '.json']),1);
-        end
+			outputJSON.EchoTime = EchoTimes;
```
Comment (HenkMutsaerts) [inline Functions/BIDS/xASL_bids_MergeNifti_Merge.m:157]: Why is this dealt with separately? Shouldn't other vectors be dealt with separately as well then (PLDs, labdur) for multi-PLD/Hadamard?

File: Functions/BIDS/xASL_bids_MergeNifti_Merge.m [hunk 4]
```diff
@@ -75,17 +83,30 @@
...
+	outputJSON = struct();
+	for iJSON = 1:length(NiftiPaths)
+		% Go through the JSONs in increasing priority
+		[Fpath, Ffile] = xASL_fileparts(NiftiPaths{priorityListIndex(iJSON)});
+		if xASL_exist(fullfile(Fpath,[Ffile '.json']), 'file')
+			currentJSON = spm_jsonread(fullfile(Fpath,[Ffile '.json']));
+			
+			% Go through all fields
+			listFieldNames = fieldnames(currentJSON);
+			for iFieldName = 1:length(listFieldNames)
```
Comment (HenkMutsaerts) [inline Functions/BIDS/xASL_bids_MergeNifti_Merge.m:102]: Is this field-wise compiling of the merged JSON the best solution? Why doing this instead of just prioritizing one full JSON that dcm2nii outputted?

(not saying it's not a good idea, just saying that this may or may not work. One disadvantage I can think of, is that you potentially get a mix of values belonging to a label and an M0 image).

File: Functions/BIDS/xASL_bids_MergeNifti.m [hunk 5]
```diff
@@ -41,7 +41,7 @@
 %
 % -----------------------------------------------------------------------------------------------------------------------------------------------------
 % __________________________________
-% Copyright 2015-2021 ExploreASL
+% Copyright 2015-2022 ExploreASL
```
Comment (HenkMutsaerts) [inline Functions/BIDS/xASL_bids_MergeNifti.m:44]: Very nice work! Is it easy for you to add a list in the function header of example cases? It's GE and Siemens right?

**Review by HenkMutsaerts — CHANGES_REQUESTED** [review]

File: Functions/BIDS/xASL_bids_MergeNifti_Merge.m (hunk 1 above)
Comment (jan-petr) [reply Functions/BIDS/xASL_bids_MergeNifti_Merge.m:97]: I don't understand?! NiftiPaths contains only NII that we converted and are existing. So all JSONs should be there as well - a missing JSON is very unlikely. But for this unlikely event, I'm checking its existence and if it isn't there it just skips it.

= It shouldn't ever happen, but if it does, it skips it and program doesn't crash.

File: Functions/BIDS/xASL_bids_MergeNifti.m (hunk 2 above)
Comment (jan-petr) [reply Functions/BIDS/xASL_bids_MergeNifti.m:220]: 1. deltaM HAS the highest priority - higher number has the highest priority (as said in the comment in the code). so deltaM overwrites all. deltaM > control/label > m0scan > cbf (this is there just for completeness). I don't understand your comment, deltaM already goes before anything else.

2. Indeed, we are not generalizing. All this priority stuff is done in a GE subfunction only applying for GE. For Siemens and Philips - JSONs are merged with equal priorities.

File: Functions/BIDS/xASL_bids_MergeNifti_Merge.m (hunk 3 above)
Comment (jan-petr) [reply Functions/BIDS/xASL_bids_MergeNifti_Merge.m:157]: Because it needs to be dealt with separately. We need to assemble TE files from several JSONs. PLDs and labdurs are never in a separate file for multi-PLD and Hadamard.

Once I have such a flavor, I can write and tweak such fix, but so far, it is only needed for TE. 
And I dont' want to write a general fix, because it is unclear if this would work in a future case (as unfortunately, things are not really done consistently in DICOM that would allow that).

File: Functions/BIDS/xASL_bids_MergeNifti_Merge.m (hunk 4 above)
Comment (jan-petr) [reply Functions/BIDS/xASL_bids_MergeNifti_Merge.m:102]: I'm not really sure either - previously, I was always taking a random JSON, because there were no differences between them. This is the first case encountered that they actually differ :) 

So hard to say if it is better to select one or compile all :) Or even impossible to say - both can be later proven to be wrong :) For now, I would slightly prefer merging (and checking if there's nothing extra), then selecting one and potentially missing something. 

But if you think that selecting is better, I am not against ;)

File: Functions/BIDS/xASL_bids_MergeNifti.m (hunk 5 above)
Comment (jan-petr) [reply Functions/BIDS/xASL_bids_MergeNifti.m:44]: Not sure if I follow - the header is already quite detailed. Explaining what is done for GE and Siemens. What exactly you want to add?

Comment (HenkMutsaerts) [reply Functions/BIDS/xASL_bids_MergeNifti.m:44]: OK I see now. I thought a bit more detail, e.g.:

* dcm2nii outputs GEs deltaM and M0scan separately, even though they are scanned in a single sequence and should belong together
* Siemens stores all controls and labels separately, which need to be reordered according their acquisition order

BTW: I would move the sub-functions to actual subfunctions, instead of separate code. If a function is only used in a single function, and belongs with it, then I would use it as true subfunction (as is the case here). The only disadvantage may be debugging, but the code tree could become definitely easier to follow! 

(fine if you resolve this and do this in a new issue, though adding my text above, adding some more of your own, and moving to subfunctions is perhaps not a lot of work)

File: Functions/BIDS/xASL_bids_MergeNifti.m (hunk 2 above)
Comment (HenkMutsaerts) [reply Functions/BIDS/xASL_bids_MergeNifti.m:220]: 1. Ah I see now. Then I would just mention them in the order such that 1 and 0 are together, now this is confusing to read. So keep the code as is, just 4 3 2 1 0 instead of 1 2 3 4. If that's done, you can resolve this comment.
2. OK, this prioritization of merging could actually be general. Also, since you reuse it in xASL_bids..._Merge, this sounds generic. But fine for now how it is.

File: Functions/BIDS/xASL_bids_MergeNifti_Merge.m (hunk 1 above)
Comment (HenkMutsaerts) [reply Functions/BIDS/xASL_bids_MergeNifti_Merge.m:97]: Yes but if it doesn't exist, we DO want the program to crash (or at least we want a warning). If you add a warning in this case, I'm fine and you can resolve.

File: Functions/BIDS/xASL_bids_MergeNifti_Merge.m (hunk 4 above)
Comment (HenkMutsaerts) [reply Functions/BIDS/xASL_bids_MergeNifti_Merge.m:102]: I would at least issue warnings if there are differences between the JSONs. Then I would choose the priority JSON. Then you can resolve :)

File: Functions/BIDS/xASL_bids_MergeNifti_Merge.m (hunk 3 above)
Comment (HenkMutsaerts) [reply Functions/BIDS/xASL_bids_MergeNifti_Merge.m:157]: I would want to generalize this. You could just add this for PLDs and labeling duration (which are the only ones where we need to know this right). If they are always the same, we don't care (we take unique) but if they differ, we issue a warning that differences are detected and imported as ...multi-TE or multi-PLD or whatsoever.

So you are saying that you don't want unexpected behavior: I say that we issue a warning (so we will at least know this), and IF there are multiple PLDs between NIfTIs which could make sense, then we catch them at least. Anyway, choose what you want and resolve this.

File: Functions/InputOutput/xASL_io_dcm2nii.m [hunk 6]
```diff
@@ -351,11 +351,10 @@
                 end
 
                 if length(vectorKeep)>1 % add iVolume suffix (if there are multiple)
-                    try
+                    if isempty(niiInstanceNumber)
+						DestFileName = [DestFileName '_' int2str(iVolume)];
```
Comment (HenkMutsaerts) [inline Functions/InputOutput/xASL_io_dcm2nii.m:355]: Why not num2str or xASL_num2str, are these not more flexible?
You can choose, and resolve.

**Review by HenkMutsaerts — CHANGES_REQUESTED** [review]
See last changes, if you processed them, I'm fine and don't have to re-review :)

File: Functions/BIDS/xASL_bids_MergeNifti_Merge.m (hunk 1 above)
Comment (jan-petr) [reply Functions/BIDS/xASL_bids_MergeNifti_Merge.m:97]: We don't really want crash. But as I say - won't happen ;) Warning added about a missing file.

File: Functions/BIDS/xASL_bids_MergeNifti.m (hunk 2 above)
Comment (jan-petr) [reply Functions/BIDS/xASL_bids_MergeNifti.m:220]: I've clarified this in the comment. I don't agree to merge 0 and 1 because a known file type (CBF) should have a higher priority than unknown (that has a zero priority).

Changing the order of code doesn't make any sense - it won't affect the readability at all. Sorry, but not doing things that don't make any sense ;) The options are listed in order of increasing priority. Otherwise is always listed at the end.

Just as an FYI: The prioritization function is general. But the setting of priorities is only used in specific cases when we know.

File: Functions/BIDS/xASL_bids_MergeNifti_Merge.m (hunk 3 above)
Comment (jan-petr) [reply Functions/BIDS/xASL_bids_MergeNifti_Merge.m:157]: Warning added for PLD and LabDur. But only warning - concatenation has to be tested once we have such a dataset.

File: Functions/BIDS/xASL_bids_MergeNifti_Merge.m (hunk 4 above)
Comment (jan-petr) [reply Functions/BIDS/xASL_bids_MergeNifti_Merge.m:102]: I've added that for LabDur and PLD - and we can add more important fields. But otherwise this makes no sense. There are a lot of differences between JSONs in parameters not important for ASL. It would be issuing to many warnings if warning for all.

File: Functions/BIDS/xASL_bids_MergeNifti.m (hunk 5 above)
Comment (jan-petr) [reply Functions/BIDS/xASL_bids_MergeNifti.m:44]: Detail added.
Subfunctions merged.

File: Functions/InputOutput/xASL_io_dcm2nii.m (hunk 6 above)
Comment (jan-petr) [reply Functions/InputOutput/xASL_io_dcm2nii.m]: Fixed.

**Comment by jan-petr** [comment]
The latest commit messed up things. Trying to revert it.

 {'GE_PCASL_3Dspiral_DV22.0_1'                 }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.json'                                      }
    {'GE_PCASL_3Dspiral_DV22.0_1'                 }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.nii.gz'                                    }
    {'GE_PCASL_3Dspiral_DV22.0_1'                 }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_aslcontext.tsv'                                }
    {'GE_PCASL_3Dspiral_DV23.1_1'                 }    {'rawdata'             }    {'Missing file'          }    {'/sub-11/perf/sub-11_asl.json'                                          }
    {'GE_PCASL_3Dspiral_DV23.1_1'                 }    {'rawdata'             }    {'Missing file'          }    {'/sub-11/perf/sub-11_asl.nii.gz'                                        }
    {'GE_PCASL_3Dspiral_DV23.1_1'                 }    {'rawdata'             }    {'Missing file'          }    {'/sub-11/perf/sub-11_aslcontext.tsv'                                    }
    {'GE_PCASL_3Dspiral_DV24.0_1'                 }    {'rawdata'             }    {'Missing folder'        }    {'/sub-Sub103/anat'                                                      }
    {'GE_PCASL_3Dspiral_DV24.0_1'                 }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub103/anat/sub-Sub103_T1w.json'                                  }
    {'GE_PCASL_3Dspiral_DV24.0_1'                 }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub103/anat/sub-Sub103_T1w.nii.gz'                                }
    {'GE_PCASL_3Dspiral_DV24.0_1'                 }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub103/perf/sub-Sub103_asl.json'                                  }
    {'GE_PCASL_3Dspiral_DV24.0_1'                 }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub103/perf/sub-Sub103_asl.nii.gz'                                }
    {'GE_PCASL_3Dspiral_DV24.0_1'                 }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub103/perf/sub-Sub103_aslcontext.tsv'                            }
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'}    {'rawdata'             }    {'Missing folder'        }    {'/sub-001/ses-1/anat'                                                   }
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'}    {'rawdata'             }    {'Missing file'          }    {'/sub-001/ses-1/anat/sub-001_ses-1_FLAIR.json'                          }
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'}    {'rawdata'             }    {'Missing file'          }    {'/sub-001/ses-1/anat/sub-001_ses-1_FLAIR.nii.gz'                        }
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'}    {'rawdata'             }    {'Missing file'          }    {'/sub-001/ses-1/anat/sub-001_ses-1_T1w.json'                            }
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'}    {'rawdata'             }    {'Missing file'          }    {'/sub-001/ses-1/anat/sub-001_ses-1_T1w.nii.gz'                          }
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'}    {'rawdata'             }    {'Missing file'          }    {'/sub-001/ses-1/perf/sub-001_ses-1_asl.json'                            }
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'}    {'rawdata'             }    {'Missing file'          }    {'/sub-001/ses-1/perf/sub-001_ses-1_asl.nii.gz'                          }
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'}    {'rawdata'             }    {'Missing file'          }    {'/sub-001/ses-1/perf/sub-001_ses-1_aslcontext.tsv'                      }
    {'GE_PCASL_3Dspiral_DV25.0_product_1'         }    {'rawdata'             }    {'Missing folder'        }    {'/sub-001/anat'                                                         }
    {'GE_PCASL_3Dspiral_DV25.0_product_1'         }    {'rawdata'             }    {'Missing file'          }    {'/sub-001/anat/sub-001_T1w.json'                                        }
    {'GE_PCASL_3Dspiral_DV25.0_product_1'         }    {'rawdata'             }    {'Missing file'          }    {'/sub-001/anat/sub-001_T1w.nii.gz'                                      }
    {'GE_PCASL_3Dspiral_DV25.0_product_1'         }    {'rawdata'             }    {'Missing file'          }    {'/sub-001/perf/sub-001_asl.json'                                        }
    {'GE_PCASL_3Dspiral_DV25.0_product_1'         }    {'rawdata'             }    {'Missing file'          }    {'/sub-001/perf/sub-001_asl.nii.gz'                                      }
    {'GE_PCASL_3Dspiral_DV25.0_product_1'         }    {'rawdata'             }    {'Missing file'          }    {'/sub-001/perf/sub-001_aslcontext.tsv'                                  }
    {'GE_PCASL_3Dspiral_RX28.02_1'                }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub124/perf/sub-Sub124_asl.json'                                  }
    {'GE_PCASL_3Dspiral_RX28.02_1'                }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub124/perf/sub-Sub124_asl.nii.gz'                                }
    {'GE_PCASL_3Dspiral_RX28.02_1'                }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub124/perf/sub-Sub124_aslcontext.tsv'                            }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'}    {'rawdata'             }    {'Missing folder'        }    {'/sub-Sub1/anat'                                                        }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'}    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/anat/sub-Sub1_FLAIR.json'                                    }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'}    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/anat/sub-Sub1_FLAIR.nii.gz'                                  }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'}    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/anat/sub-Sub1_T1w.json'                                      }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'}    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/anat/sub-Sub1_T1w.nii.gz'                                    }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'}    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.json'                                      }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'}    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.nii.gz'                                    }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'}    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_aslcontext.tsv'                                }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'rawdataReference'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.json'                                      }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'rawdataReference'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.nii.gz'                                    }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'rawdataReference'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_aslcontext.tsv'                                }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_run-1_asl.json'                                }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_run-1_asl.nii.gz'                              }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_run-1_aslcontext.tsv'                          }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_run-1_m0scan.json'                             }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_run-1_m0scan.nii.gz'                           }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_run-2_asl.json'                                }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_run-2_asl.nii.gz'                              }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_run-2_aslcontext.tsv'                          }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_run-2_m0scan.json'                             }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'rawdata'             }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_run-2_m0scan.nii.gz'                           }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD'        }    {'Both'                }    {'Different file content'}    {'Different file content: /sub-Sub1/fmap/sub-Sub1_dir-pa_m0scan.json'    }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD'        }    {'Both'                }    {'Different file content'}    {'Different file content: /sub-Sub1/perf/sub-Sub1_asl.json'              }
    {'GE_PCASL_3Dspiral_DV22.0_1'                 }    {'derivatives'         }    {'Missing folder'        }    {'/ExploreASL/sub-Sub1_1/ASL_1'                                          }
    {'GE_PCASL_3Dspiral_DV22.0_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'                               }
    {'GE_PCASL_3Dspiral_DV22.0_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.nii.gz'                             }
    {'GE_PCASL_3Dspiral_DV22.0_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D_Source.json'                        }
    {'GE_PCASL_3Dspiral_DV22.0_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D_Source.nii.gz'                      }
    {'GE_PCASL_3Dspiral_DV22.0_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4Dcontext.tsv'                         }
    {'GE_PCASL_3Dspiral_DV22.0_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4Dcontext_Source.tsv'                  }
    {'GE_PCASL_3Dspiral_DV22.0_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/M0.json'                                  }
    {'GE_PCASL_3Dspiral_DV22.0_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/M0.nii.gz'                                }
    {'GE_PCASL_3Dspiral_DV23.1_1'                 }    {'derivatives'         }    {'Missing folder'        }    {'/ExploreASL/sub-11_1/ASL_1'                                            }
    {'GE_PCASL_3Dspiral_DV23.1_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-11_1/ASL_1/ASL4D.json'                                 }
    {'GE_PCASL_3Dspiral_DV23.1_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-11_1/ASL_1/ASL4D.nii.gz'                               }
    {'GE_PCASL_3Dspiral_DV23.1_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-11_1/ASL_1/ASL4D_Source.json'                          }
    {'GE_PCASL_3Dspiral_DV23.1_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-11_1/ASL_1/ASL4D_Source.nii.gz'                        }
    {'GE_PCASL_3Dspiral_DV23.1_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-11_1/ASL_1/ASL4Dcontext.tsv'                           }
    {'GE_PCASL_3Dspiral_DV23.1_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-11_1/ASL_1/ASL4Dcontext_Source.tsv'                    }
    {'GE_PCASL_3Dspiral_DV23.1_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-11_1/ASL_1/M0.json'                                    }
    {'GE_PCASL_3Dspiral_DV23.1_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-11_1/ASL_1/M0.nii.gz'                                  }
    {'GE_PCASL_3Dspiral_DV24.0_1'                 }    {'derivatives'         }    {'Missing folder'        }    {'/ExploreASL/sub-Sub103_1/ASL_1'                                        }
    {'GE_PCASL_3Dspiral_DV24.0_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub103_1/ASL_1/ASL4D.json'                             }
    {'GE_PCASL_3Dspiral_DV24.0_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub103_1/ASL_1/ASL4D.nii.gz'                           }
    {'GE_PCASL_3Dspiral_DV24.0_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub103_1/ASL_1/ASL4D_Source.json'                      }
    {'GE_PCASL_3Dspiral_DV24.0_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub103_1/ASL_1/ASL4D_Source.nii.gz'                    }
    {'GE_PCASL_3Dspiral_DV24.0_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub103_1/ASL_1/ASL4Dcontext.tsv'                       }
    {'GE_PCASL_3Dspiral_DV24.0_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub103_1/ASL_1/ASL4Dcontext_Source.tsv'                }
    {'GE_PCASL_3Dspiral_DV24.0_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub103_1/ASL_1/M0.json'                                }
    {'GE_PCASL_3Dspiral_DV24.0_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub103_1/ASL_1/M0.nii.gz'                              }
    {'GE_PCASL_3Dspiral_DV24.0_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub103_1/T1.json'                                      }
    {'GE_PCASL_3Dspiral_DV24.0_1'                 }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub103_1/T1.nii.gz'                                    }
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'}    {'derivatives'         }    {'Missing folder'        }    {'/ExploreASL/sub-001/ASL_1'                                             }
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'}    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-001/ASL_1/ASL4D.json'                                  }
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'}    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-001/ASL_1/ASL4D.nii.gz'                                }
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'}    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-001/ASL_1/ASL4D_Source.json'                           }
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'}    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-001/ASL_1/ASL4D_Source.nii.gz'                         }
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'}    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-001/ASL_1/ASL4Dcontext.tsv'                            }
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'}    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-001/ASL_1/ASL4Dcontext_Source.tsv'                     }
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'}    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-001/ASL_1/M0.json'                                     }
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'}    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-001/ASL_1/M0.nii.gz'                                   }
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'}    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-001/FLAIR.json'                                        }
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'}    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-001/FLAIR.nii.gz'                                      }
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'}    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-001/T1.json'                                           }
    {'GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1'}    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-001/T1.nii.gz'                                         }
    {'GE_PCASL_3Dspiral_DV25.0_product_1'         }    {'derivatives'         }    {'Missing folder'        }    {'/ExploreASL/sub-001_1/ASL_1'                                           }
    {'GE_PCASL_3Dspiral_DV25.0_product_1'         }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-001_1/ASL_1/ASL4D.json'                                }
    {'GE_PCASL_3Dspiral_DV25.0_product_1'         }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-001_1/ASL_1/ASL4D.nii.gz'                              }
    {'GE_PCASL_3Dspiral_DV25.0_product_1'         }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-001_1/ASL_1/ASL4D_Source.json'                         }
    {'GE_PCASL_3Dspiral_DV25.0_product_1'         }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-001_1/ASL_1/ASL4D_Source.nii.gz'                       }
    {'GE_PCASL_3Dspiral_DV25.0_product_1'         }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-001_1/ASL_1/ASL4Dcontext.tsv'                          }
    {'GE_PCASL_3Dspiral_DV25.0_product_1'         }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-001_1/ASL_1/ASL4Dcontext_Source.tsv'                   }
    {'GE_PCASL_3Dspiral_DV25.0_product_1'         }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-001_1/ASL_1/M0.json'                                   }
    {'GE_PCASL_3Dspiral_DV25.0_product_1'         }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-001_1/ASL_1/M0.nii.gz'                                 }
    {'GE_PCASL_3Dspiral_DV25.0_product_1'         }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-001_1/T1.json'                                         }
    {'GE_PCASL_3Dspiral_DV25.0_product_1'         }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-001_1/T1.nii.gz'                                       }
    {'GE_PCASL_3Dspiral_RX28.02_1'                }    {'derivatives'         }    {'Missing folder'        }    {'/ExploreASL/sub-Sub124_1/ASL_1'                                        }
    {'GE_PCASL_3Dspiral_RX28.02_1'                }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub124_1/ASL_1/ASL4D.json'                             }
    {'GE_PCASL_3Dspiral_RX28.02_1'                }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub124_1/ASL_1/ASL4D.nii.gz'                           }
    {'GE_PCASL_3Dspiral_RX28.02_1'                }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub124_1/ASL_1/ASL4D_Source.json'                      }
    {'GE_PCASL_3Dspiral_RX28.02_1'                }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub124_1/ASL_1/ASL4D_Source.nii.gz'                    }
    {'GE_PCASL_3Dspiral_RX28.02_1'                }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub124_1/ASL_1/ASL4Dcontext.tsv'                       }
    {'GE_PCASL_3Dspiral_RX28.02_1'                }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub124_1/ASL_1/ASL4Dcontext_Source.tsv'                }
    {'GE_PCASL_3Dspiral_RX28.02_1'                }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub124_1/ASL_1/M0.json'                                }
    {'GE_PCASL_3Dspiral_RX28.02_1'                }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub124_1/ASL_1/M0.nii.gz'                              }
    {'Philips_PASL_2DEPI_5.4.0.2-LookLocker_1'    }    {'derivativesReference'}    {'Missing folder'        }    {'/ExploreASL/temp'                                                      }
    {'Philips_PASL_2DEPI_5.4.0.2-LookLocker_1'    }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/temp/dcm2niiCatchedErrors.json'                            }
    {'Philips_PASL_2DEPI_5.4.0.2-LookLocker_1'    }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/temp/dcm2niiCatchedErrors.mat'                             }
    {'Philips_PCASL_2DEPI_5.3.1.1_1'              }    {'derivativesReference'}    {'Missing folder'        }    {'/ExploreASL/temp'                                                      }
    {'Philips_PCASL_2DEPI_5.3.1.1_1'              }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/temp/dcm2niiCatchedErrors.json'                            }
    {'Philips_PCASL_2DEPI_5.3.1.1_1'              }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/temp/dcm2niiCatchedErrors.mat'                             }
    {'Philips_PCASL_3DGRASE_5.4.0.2_Product_2'    }    {'derivativesReference'}    {'Missing folder'        }    {'/ExploreASL/temp'                                                      }
    {'Philips_PCASL_3DGRASE_5.4.0.2_Product_2'    }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/temp/dcm2niiCatchedErrors.json'                            }
    {'Philips_PCASL_3DGRASE_5.4.0.2_Product_2'    }    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/temp/dcm2niiCatchedErrors.mat'                             }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'}    {'derivativesReference'}    {'Missing folder'        }    {'/ExploreASL/temp'                                                      }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'}    {'derivatives'         }    {'Missing folder'        }    {'/ExploreASL/sub-Sub1_1/ASL_1'                                          }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'}    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/temp/dcm2niiCatchedErrors.json'                            }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'}    {'derivativesReference'}    {'Missing file'          }    {'/ExploreASL/temp/dcm2niiCatchedErrors.mat'                             }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'}    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'                               }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'}    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.nii.gz'                             }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'}    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D_Source.json'                        }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'}    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D_Source.nii.gz'                      }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'}    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4Dcontext.tsv'                         }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'}    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4Dcontext_Source.tsv'                  }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'}    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/M0.json'                                  }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'}    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/M0.nii.gz'                                }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'}    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/FLAIR.json'                                     }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'}    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/FLAIR.nii.gz'                                   }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'}    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/T1.json'                                        }
    {'Siemens_PASL_2DEPI_VB15A_ADNI2_941_S_4764_1'}    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/T1.nii.gz'                                      }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'derivatives'         }    {'Missing folder'        }    {'/ExploreASL/sub-Sub1_1/ASL_2'                                          }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/M0.json'                                  }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/M0.nii.gz'                                }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_2/ASL4D.json'                               }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_2/ASL4D.nii.gz'                             }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_2/ASL4Dcontext.tsv'                         }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_2/M0.json'                                  }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'derivatives'         }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_2/M0.nii.gz'                                }
    {'Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1'       }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'       }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD'        }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/dataPar.json'                      }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD'        }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'       }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD'        }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/ASL4D_Source.json'}
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD'        }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/M0.json'          }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD'        }    {'Both'                }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub1_1/ASL_1/M0_RevPE.json'    }

**Review by HenkMutsaerts — APPROVED** [review]
