### PR TITLE
#1303 ExploreASL_Initialize fix spaces in path

### LINKED ISSUE #1303: Leading or trailing spaces in paths, initializing ExploreASL
### Description

Leading and trailing spaces in paths will crash ExploreASL. They should not crash ExploreASL but rather give a warning and continue (with the space removed). This will save us some user questions and thus time.

### Tasks

- [x] Detect spaces in paths on the first and last position. When detected, remove them and issue a warning.

### How to test

`ExploreASL(' /Users/henk/ExploreASL/FlavorDatabase/GE_PCASL_3Dspiral_DV22.0_1',1,0);`

### Release notes

Remove leading and trailing spaces in the path.

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

Close #1303

### CODE REVIEW

File: ExploreASL_Initialize.m [hunk 1]
```diff
@@ -600,6 +600,33 @@ function xASL_init_AddDirsOfxASL(MyPath)
                 end
             end
         
+			% Check and remove empty spaces at the start and end of the DatasetRoot
+			if ~isempty(x.opts.DatasetRoot)
+
+				% Remove the empty spaces at the start
+				if x.opts.DatasetRoot(1) == ' '
+					[~, ~, indexUniqueChars] = unique(x.opts.DatasetRoot, 'stable'); % Create a vector that gives for each character its unique identifier
```
Comment (HenkMutsaerts) [inline ExploreASL_Initialize.m]: This gives the rank right? "unique identifier" is very vague

When ranking 1000 2000 1500, you get 1 3 2, this is what you mean right?

File: ExploreASL_Initialize.m [hunk 2]
```diff
@@ -600,6 +600,33 @@ function xASL_init_AddDirsOfxASL(MyPath)
                 end
             end
         
+			% Check and remove empty spaces at the start and end of the DatasetRoot
```
Comment (HenkMutsaerts) [inline ExploreASL_Initialize.m]: We have functions for this already, e.g., `xASL_adm_ReplaceSymbols` or `xASL_adm_UnixPath`, but they don't do exactly what you want here I believe.

I would at least make this a separate section in the code, or even a subfunction, to keep it all readable.

This could be as easy as replacing % with %%

**Review by HenkMutsaerts — CHANGES_REQUESTED** [review]
Nice, some minor things

File: ExploreASL_Initialize.m (hunk 1 above)
Comment (jan-petr) [reply ExploreASL_Initialize.m]: No. A unique unsorted identified. 
1000 2000 1500 gives 1,2,3

Explained in 3dc9978e

File: ExploreASL_Initialize.m (hunk 2 above)
Comment (jan-petr) [reply ExploreASL_Initialize.m]: ReplaceSymbols and UnixPath indeed does a different thing.
I'm adding %%. Fine?
3dc9978e

File: ExploreASL_Initialize.m (hunk 1 above)
Comment (HenkMutsaerts) [reply ExploreASL_Initialize.m]: I think you can simplify this using regular expressions that search for spaces. But fine with this implementation.

Just a minor note: if you want to explain what is happening, it is not only nice to explain what your code does technically (e.g., aacba gives 1 1 2 3 1) but also why you do this (e.g.,

% Remove empty spaces at the start of the path
% First, we check if the first index is a space
% Second, we check the position of the second unique character (the first unique character being a space).
% This position is where the path starts (there can be multiple spaces that need to be omitted)

File: ExploreASL_Initialize.m [hunk 3]
```diff
@@ -600,7 +540,36 @@ function xASL_init_AddDirsOfxASL(MyPath)
...
+				if x.opts.DatasetRoot(1) == ' '
+					[~, ~, indexUniqueChars] = unique(x.opts.DatasetRoot, 'stable'); % Create a vector that gives for each character its unique identifier
+					indexCharacter2 = find(indexUniqueChars==2); % Find the indices of the second unique character
+					if ~isempty(indexCharacter2)
+						x.opts.DatasetRoot = x.opts.DatasetRoot(indexCharacter2(1):end);
+						warning(['x.opts.DataserRoot contains ' xASL_num2str(indexCharacter2(1)-1) ' empty spaces at the start. Fixing this']);
+					end
+				end
+
+				% Remove the empty spaces at the end
```
Comment (HenkMutsaerts) [inline ExploreASL_Initialize.m:555]: Same here

File: ExploreASL_Initialize.m [hunk 4]
```diff
@@ -509,23 +462,10 @@ function xASL_init_AddDirsOfxASL(MyPath)
     
 end
 
-
```
Comment (HenkMutsaerts) [inline ExploreASL_Initialize.m:512]: I added these spaces for a reason I believe, that there is a lot of space between main code sections/subfunctions and less space between different code sections (not complaining on your edit, just explaining why I did this)

**Review by HenkMutsaerts — CHANGES_REQUESTED** [review]
Minor comment, you can copy-paste my comment to explain your code.

File: ExploreASL_Initialize.m (hunk 4 above)
Comment (jan-petr) [reply ExploreASL_Initialize.m:512]: Yesyes. I know - but then we added the double %%, which actually works now nicely, so I thought we can remove the space. If you agree?

File: ExploreASL_Initialize.m (hunk 1 above)
Comment (jan-petr) [reply ExploreASL_Initialize.m]: Good idea. Actually, for PLDs, I had to write this code, which I then ported here. But you are right that with regexp, it is much easier, so I redid all that now with regexp.

The explanations is now also much more simple

Comment (HenkMutsaerts) [reply ExploreASL_Initialize.m]: Hmm you say that you redid everything with regexp, but that's not what I see in the code?

**Review by HenkMutsaerts — APPROVED** [review]
You say that you redid everything with regexp, but that's not what I see in the code? Perhaps you forgot to push?

Anyway, I'm fine keeping it like this, I added some extra comments to clarify what you're doing. I just kept 1 conversation open so you can see what I mean, but feel free to close that and merge this.

File: ExploreASL_Initialize.m (hunk 1 above)
Comment (jan-petr) [reply ExploreASL_Initialize.m]: Sorry. Forgot to push indeed.
