### PR TITLE
Closes #1103 xASL_module_BIDS2Legacy: add backward compatibility

### LINKED ISSUE #1103: <SUBJECTNAME> vs <SUBJECTNAME>_1
### Description

When `/rawdata/<SUBJECTNAME>` `/derivatives/ExploreASL/<SUBJECTNAME>` both exist, `xASL_module_BIDS2Legacy` will recreate `/derivatives/ExploreASL/<SUBJECTNAME>_1` (failing to recognize that this is the same as the one without _1).

However, if `010_BIDS2LEGACY.status` exists for <SUBJECTNAME>_1, it will behave correctly.

Without `010_BIDS2LEGACY.status`, `/derivatives/ExploreASL/<SUBJECTNAME_1>` will be overwritten. 

It is probably nicest to add warnings, see proposed changes below.

### Tasks

- [x] If a folder in /derivatives/ExploreASL/ exists and will be overwritten, issue a warning
- [x] Recognize that <SUBJECTNAME> and <SUBJECTNAME>_1 are the same in `/derivatives/ExploreASL` (per legacy structure) so that this will also be overwritten and issue a warning

### How to test

clone `/ExploreASL/External/TestDataSet`, run `ExploreASL('path', 0, 0)`, rename `sub-Sub1_1` to `sub-Sub1` and rerun `ExploreASL('path', 0, 0)`

This will give the following two warnings. Note that the second warning and text will be shown if a folder already existed, without renaming sub-*** to sub-***_1. This only applies to the first visit/session, and only if the lock file `010_BIDS2LEGACY.status` doesn't exist for this subject.

image

### Release notes

Fix BIDS2Legacy renaming to SUBJECTNAME_1

### PR DESCRIPTION
**Pull request by HenkMutsaerts**
### Linked issue

Closes #1103

### CODE REVIEW

File: Modules/xASL_module_BIDS2Legacy.m [hunk 1]
```diff
@@ -102,7 +102,26 @@
...
             pathLegacy_SubjectSession = fullfile(x.dir.xASLDerivatives, SubjectSession);
-            
+            bFolderExisted = exist(pathLegacy_SubjectSession, 'dir')==7;
+
+            % Backwards compatibility: rename sub-*** to sub-***_1
+            if strcmp(SessionID, '1')
+                pathLegacy_SubjectSession_OLD = fullfile(x.dir.xASLDerivatives, SubjectID);
+                if ~bFolderExisted && exist(pathLegacy_SubjectSession_OLD, 'dir')==7
+                    warning(['Renaming ' pathLegacy_SubjectSession_OLD '->' SubjectSession]);
+                    xASL_Move(pathLegacy_SubjectSession_OLD, pathLegacy_SubjectSession, 1, 0);
```
Comment (jan-petr) [inline Modules/xASL_module_BIDS2Legacy.m]: A minor issue - we rename the folder, but don't rename the lock-files. So the old lock-files stay there. 

Shall we ignore that or keep that? Removing might be nice to avoid potential future issues. On the other hand, it's only relevant to old data. So just think about it and decide what you want ;)

File: Modules/xASL_module_BIDS2Legacy.m [hunk 2]
```diff
@@ -102,7 +102,26 @@
...
+                    bFolderExisted = true;
+                end
+            end
+
+            % Provide warning that we are going to overwrite the folder
+            if bFolderExisted
+                warning(['Overwriting rawdata copied to: ' pathLegacy_SubjectSession]);
```
Comment (jan-petr) [inline Modules/xASL_module_BIDS2Legacy.m]: A bit confusing so the user might think you are overwriting raw data.

File: Modules/xASL_module_BIDS2Legacy.m [hunk 3]
```diff
@@ -102,7 +102,26 @@
...
+                fprintf('%s\n', 'Note that we do not overwrite any derivatives');
```
Comment (jan-petr) [inline Modules/xASL_module_BIDS2Legacy.m]: You mean, we don't overwrite processed files. Cause the origin files derivatives/ExploreASL/sub1/ASL_1/ASL.nii is kind of a derivative file.

In other words, we are not overwriting derived files, but this message can be confusing and the user might think we talk about the entire "derivatives" folder.

File: Modules/xASL_module_BIDS2Legacy.m [hunk 4]
```diff
@@ -102,7 +102,26 @@
...
+                fprintf('%s\n', 'Rather, we merge them with the freshly copied rawdata');
```
Comment (jan-petr) [inline Modules/xASL_module_BIDS2Legacy.m]: We merge previously processed data with ...

File: Modules/xASL_module_BIDS2Legacy.m [hunk 5]
```diff
@@ -102,7 +102,26 @@
...
+                fprintf('%s\n', 'It is always cleanest to remove all derivatives before rerunning');
```
Comment (jan-petr) [inline Modules/xASL_module_BIDS2Legacy.m]: Nevertheless, ...

**Review by jan-petr — CHANGES_REQUESTED** [review]
Minor comments.

File: Modules/xASL_module_BIDS2Legacy.m (hunk 1 above)
Comment (HenkMutsaerts) [reply Modules/xASL_module_BIDS2Legacy.m]: Good point, but then we would need to rename all derivatives as well. Done in 16d0ee0c9a8ea0b26985b41e69d75091b4c951e9

File: Modules/xASL_module_BIDS2Legacy.m (hunk 5 above)
Comment (HenkMutsaerts) [reply Modules/xASL_module_BIDS2Legacy.m]: a750e39ae434b87ce24d127bfc2a24d87652ab95

File: Modules/xASL_module_BIDS2Legacy.m (hunk 4 above)
Comment (HenkMutsaerts) [reply Modules/xASL_module_BIDS2Legacy.m]: a750e39ae434b87ce24d127bfc2a24d87652ab95

File: Modules/xASL_module_BIDS2Legacy.m (hunk 3 above)
Comment (HenkMutsaerts) [reply Modules/xASL_module_BIDS2Legacy.m]: a750e39ae434b87ce24d127bfc2a24d87652ab95

File: Modules/xASL_module_BIDS2Legacy.m (hunk 2 above)
Comment (HenkMutsaerts) [reply Modules/xASL_module_BIDS2Legacy.m]: a750e39ae434b87ce24d127bfc2a24d87652ab95

**Review by jan-petr — APPROVED** [review]
OK
