### PR TITLE
Closes #911 xASL_module_ASL: Revamp initialization

### LINKED ISSUE #911: Revamp initialization structure of `xASL_module_ASL`
### Description

Revamp initialization structure of `xASL_module_ASL`. 

### Requirements

The order of the initialization was wrong, causing default parameters to override `asl4d.json`. This is now fixed.
We now run the following initialization steps in `xASL_module_ASL`:

>> % A. Check if ASL exists, otherwise skip this module
% B. Manage mutex state — processing step
% C. Cleanup before rerunning
%
% D - ASL processing parameters
% D1. Load ASL parameters (inheritance principle)
% D2. Default ASL processing settings in the x.modules.asl field
% D3. Multi-PLD parsing
% D4. TimeEncoded parsing
% D5. Multi-TE parsing
%
% E - ASL quantification parameters
% E1. Default quantification parameters in the Q field
% E2. Define sequence (educated guess based on the Q field)
% F. Backward and forward compatibility of filenames
% G. Split ASL and M0 within the ASL time series
% H. Skip processing if invalid image

### How to test

Test by running `xASL_qc_TestExploreASL`. The results for macOS intel 2019a look good, except for `Philips_2DEPI_Lesion*`, which misses the PVC value because of the limited FoV. @jan-petr do you remember if we fixed this already?

image

### Release notes

Revamp initialization structure of xASL_module_ASL to restore a correct order of all steps.

### PR DESCRIPTION
**Pull request by HenkMutsaerts**
### Linked issue

Closes #911

### CODE REVIEW

File: Modules/xASL_module_ASL.m [hunk 1]
```diff
@@ -183,34 +136,42 @@
...
-if ~x.mutex.HasState('999_ready')
-    bO = true; % generate output, some processing has and some has not been yet done
-else
-    bO = false; % skip output, as all processing has been performed
-end
 
+%% D1. Load ASL parameters (inheritance principle)
 [~, x] = xASL_adm_LoadParms(x.P.Path_ASL4D_parms_mat, x, bO);
 
 if ~isfield(x,'Q')
```
Comment (jan-petr) [inline Modules/xASL_module_ASL.m:116]: You can remove the Q-checking here (line 144) as it is already on line 197 at step E1.

**Review by MichaelStritt — APPROVED** [review]
@HenkMutsaerts: I did some minor changes. I just love putting code to sub-functions to make the code more readable. I saw that you already did the 10 test datasets and I didn't redo them.

File: Modules/xASL_module_ASL.m [hunk 2]
```diff
@@ -224,19 +185,88 @@
...
 
 
-%% Define sequence (educated guess)
+%% E2. Define sequence (educated guess based on the Q field)
 x = xASL_adm_DefineASLSequence(x);
 
 
-%% Skip processing if invalid image
+%% F. Backward and forward compatibility of filenames
+if ~xASL_exist(x.P.Path_M0, 'file')
```
Comment (jan-petr) [inline Modules/xASL_module_ASL.m:198]: You have reverted the order of the code for M0-path fixing and ASL-M0 splitting. This in theory should be fine - but in theory only ;)

**Review by jan-petr — CHANGES_REQUESTED** [review]
Looks very good. But these revamps are never really without small errors - see my comments ;)

File: Modules/xASL_module_ASL.m (hunk 1 above)
Comment (MichaelStritt) [reply Modules/xASL_module_ASL.m:116]: And `xASL_init_SubStructs` should always add it for your 😄

Comment (jan-petr) [reply Modules/xASL_module_ASL.m:116]: So that means - delete on both places :D

Comment (jan-petr) [reply Modules/xASL_module_ASL.m:116]: Fixed.

File: Modules/xASL_module_ASL.m [hunk 3]
```diff
@@ -39,21 +59,9 @@
...
-    warning('x.Q.ApplyQuantification had too few parameters, using default 1');
-    x.Q.ApplyQuantification(length(x.Q.ApplyQuantification)+1:5) = 1;
-end
 
-if ~isfield(x.modules.asl,'bPVCNativeSpace') || isempty(x.modules.asl.bPVCNativeSpace)
-	x.modules.asl.bPVCNativeSpace = 0;
-end
 
-% Only continue if ASL exists
+%% A. Check if ASL exists, otherwise skip this module
```
[the remark this answers is not in the document]
Comment (jan-petr) [reply Modules/xASL_module_ASL.m:63]: Fixed

File: Modules/xASL_module_ASL.m (hunk 2 above)
Comment (HenkMutsaerts) [reply Modules/xASL_module_ASL.m:188]: True, that's why I tested the testdatasets

File: Modules/xASL_module_ASL.m [hunk 4]
```diff
@@ -113,12 +113,6 @@
 %% D1. Load ASL parameters (inheritance principle)
 [~, x] = xASL_adm_LoadParms(x.P.Path_ASL4D_parms_mat, x, bO);
 
-if ~isfield(x,'Q')
```
Comment (HenkMutsaerts) [inline Modules/xASL_module_ASL.m:204]: @MichaelStritt did you delete this because you already have this in this general field initialization/defaulting function that you made?

**Review by HenkMutsaerts — COMMENTED** [review]
Minor question, and I cannot easily see that everything is nicely put into submodules but I assume this ;)

And I cannot approve

File: Modules/xASL_module_ASL.m (hunk 4 above)
Comment (jan-petr) [reply Modules/xASL_module_ASL.m:204]: Yes

**Review by jan-petr — APPROVED** [review]
OK.
