### PR TITLE
#1751 stat_GetDICOMStatistics Bug fix

### LINKED ISSUE #1751: Unit test fail
### Description

Unit tests fails at several places as a result of previous untested merges of #1717 

### Tasks

- [x] ExploreASL unittest fails in last 4 subtests. The error is in TSV writing in stat_GetDICOMStatistics. Sometimes, DICOM tag can be composed of multiple fields, which then turns into a cell and crashes TSV writing. So we need to turn cells into a composed string fe8e7eef
- [x] BIDS2Legacy unittest fails -> this was related to the error above. No further fix needed. 

### Release notes

Report together with #1717 as it fixes error in that issue.

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

Close #1751

### CODE REVIEW

File: Modules/Module_Processing/Module_Population/xASL_stat_GetROIstatistics.m [hunk 1]
```diff
@@ -538,7 +538,7 @@
 			DataIm(:) = NaN;
 		end
 		%% 4.d Show ROIs projected on ASL image (%% PM %% : ALSO DONE BELOW)
-		LabelIM = xASL_vis_Convert4D_3D_atlas(xASL_im_Column2IM(SubjectSpecificMasks(:,[1:3:end]), x.S.masks.WBmask));
+		LabelIM = xASL_vis_Convert4D_3D_atlas(xASL_im_Column2IM(SubjectSpecificMasks(:, 1:3:end), x.S.masks.WBmask));
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/Module_Population/xASL_stat_GetROIstatistics.m:541]: This will create a conflict with another recent issue, so because it doesn't seem necessary, I would revert this one. But your decision, you will probably be the one resolving the conflict :)

File: Modules/Module_Processing/Module_Population/xASL_stat_GetDICOMStatistics.m [hunk 2]
```diff
@@ -92,9 +92,13 @@ function xASL_stat_GetDICOMStatistics(x, ScanType, HasSessions, bOverwrite)
 end
 fprintf('\n');
 
-
+% Verify that all gathered cells include strings and not cells inside
+listCells = find(cellfun(@iscell, TSV(:)));
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/Module_Population/xASL_stat_GetDICOMStatistics.m:96]: I thought I fixed this with the xASL_num2str or something. But if this fix by you works and you tested it, I'm fine.

**Review by HenkMutsaerts — APPROVED** [review]
Approved with 2 questions, up to you

File: Modules/Module_Processing/Module_Population/xASL_stat_GetROIstatistics.m (hunk 1 above)
Comment (jan-petr) [reply Modules/Module_Processing/Module_Population/xASL_stat_GetROIstatistics.m:541]: Haha - no worries - that's a conflict I can handle :)
