### PR TITLE
Closes #1178 xASL_init_Iteration: fix diaryFile for LongReg

### LINKED ISSUE #1178: Symbol not defined: SESSION  -- when running Longitudinal Registration
### Description

Probably related to #1103 . In short, due to the "_#" approach, the SESSION symbol can't be resolved when it is requested to do so within `xASL_init_iteration` -> `runIteration`. Error happens around this block:

```matlab
% Optional diary logfile of command window
        if ~isempty(diaryFile)
            % NB. Don't overwrite diaryFile itself because it might be expanded
            % with different values in the next iteration.
            diaryFileEx = xASL_adm_ReplaceSymbols(diaryFile,x);
            diaryFileEx = fullfile(diaryFileEx);
```

### Tasks

- [ ] Fix SESSION field in `x` struct by the time `xASL_adm_ReplaceSymbols` is called before running longitudinal registration

### How to test

1) Checkout `develop` branch.

2) Run a dataset with multiple visits. Example given below, which successfully completed the Structural Module and is about to execute the LongReg module:

image

3) In dataPar.json, `x.modules.bRunLongReg` is set to 1.  Run with only the Structural module selected.

4) Breakpoint at line 304 in `xASL_init_Iteration` when `jobfn` is @xASL_module_LongReg. (workspace attached)

[LongRegBugSESSIONSymbol__xASL_init_Iteration.zip](https://github.com/ExploreASL/ExploreASL/files/9465340/LongRegBugSESSIONSymbol__xASL_init_Iteration.zip)

### Release notes

Required: Fixed a bug where the <SESSION> symbol was not interpreted correctly prior to beginning longitudinal regsitration.

### PR DESCRIPTION
**Pull request by HenkMutsaerts**
### Linked issue

Closes #1178

### CODE REVIEW

**Review by jan-petr — CHANGES_REQUESTED** [review]
This commit looks good. But please check and close all tasks from the main issue first.

**Comment by HenkMutsaerts** [comment]
Done, see issue. Also addressed the request by Toshihiko, though he should test it (we don't have a TestDataSet for DARTEL or LongReg); btw: should he run LongReg or DARTEL?

**Comment by jan-petr** [comment]
> Done, see issue. Also addressed the request by Toshihiko, though he should test it (we don't have a TestDataSet for DARTEL or LongReg); btw: should he run LongReg or DARTEL?

You mean a request that doesn't have an issue yet? Good. Thanks. BTW: Is issue #1103 also fixed by this?

HENK: no, read my response in the issue itself.

File: Functions/Initialization/xASL_init_Iteration.m [hunk 1]
```diff
@@ -114,8 +114,11 @@
         dbSettings.diaryFile = fullfile('<ROOT>', 'derivatives', 'ExploreASL' ,'log', [moduleName '_sub-<SUBJECT>.log']);
     elseif ~isempty(regexpi(ModName,'(Structural|LongReg)', 'once'))
         dbSettings.diaryFile = fullfile('<ROOT>', 'log', [moduleName '_<SUBJECT>.log']);
+    elseif ~isempty(regexpi(ModName,'(ASL|func|dwi)', 'once'))
```
Comment (jan-petr) [inline Functions/Initialization/xASL_init_Iteration.m:132]: We don't want the local log? There's another place where this is done?

**Review by jan-petr — CHANGES_REQUESTED** [review]
Looks good. One minor question only.

File: Functions/Initialization/xASL_init_Iteration.m (hunk 1 above)
Comment (HenkMutsaerts) [reply Functions/Initialization/xASL_init_Iteration.m:132]: I don't understand your question. I have only done the following here:

1. Ensure that structural & LongRun don't get <SESSION> in their log filename (because they don't have SESSIONS, and it crashed because SESSIONS weren't defined)
2. Ensure that ASL|func|dwi do get SESSIONS in the log filename.
3. Use `fullfile` instead of `/`

I didn't change any location?

File: Functions/Initialization/xASL_init_Iteration.m [hunk 2]
```diff
@@ -87,38 +89,37 @@
         ModName = moduleName;
     end
     
-    % DARTEL & LongReg settings
-    if  strcmp(ModName,'DARTEL') || strcmp(ModName,'LongReg')
-        dbSettings.x.dir.LockDir = [dbSettings.x.dir.LockDir '_' x.P.STRUCT ];
```
Comment (jan-petr) [inline Functions/Initialization/xASL_init_Iteration.m:107]: The lock-dir for LongReg is now different. And for DARTEL, no lockdir is now defined. Is that correct?

File: Functions/Initialization/xASL_init_Iteration.m (hunk 1 above)
Comment (jan-petr) [reply Functions/Initialization/xASL_init_Iteration.m:132]: Sorry. I don't understand this neither anymore :) This what you mention is all fine. I just don't understand the lockdir change for DARTEL+LongReg - see the other comment.

**Review by jan-petr — CHANGES_REQUESTED** [review]
I have clarified my question now. Maybe it is all OK - I'm just asking if this was done on purpose.

File: Functions/Initialization/xASL_init_Iteration.m (hunk 2 above)
Comment (HenkMutsaerts) [reply Functions/Initialization/xASL_init_Iteration.m:107]: line 41 sets a general lockdir that is used for all non-specific cases; LongReg specifically needed a different lock folder, as this crashed for Maurice

Comment (jan-petr) [reply Functions/Initialization/xASL_init_Iteration.m:107]: Yes. So now DARTEL is using the default lockDir set on Line 41? And LongReg now uses the common lockdir set on line 96? Is that fine? I'm not saying it isn't ;)

**Review by jan-petr — CHANGES_REQUESTED** [review]
See last questions in code. It's just to double-check, not necessarily wrong...

File: Functions/Initialization/xASL_init_Iteration.m (hunk 2 above)
Comment (HenkMutsaerts) [reply Functions/Initialization/xASL_init_Iteration.m:107]: Yes, something like that. I tested it after I rewrote this; it should be fine:) One of the two expected a session-extension in the lockdir, which wasn't there, which made it crash for Maurice. Then I think I did a small improvement: DARTEL should have no extension, whereas LongReg should have a subject extension.

**Review by jan-petr — APPROVED** [review]
OK.
