### PR TITLE
#1766 wrp_DCM2NII_Subject warning multiple scans

### LINKED ISSUE #1766: xASL_imp_CreateSummaryFile crashes with too many missing scans per single Subject/Visit/Session
### Description

xASL_imp_CreateSummaryFile crashes with too many missing scans per single Subject/Visit/Session. In some cases we obtain multiple scans per single session/run, which might need concatenation or are erroneous, but in any case it gives a crash.
I fixed it with the changes below, but @jan-petr may want to check if we shouldn't also add a warning that something goes wrong in the session/scan definition?

Screenshot 2024-09-09 at 13 50 10

JAN: Problem is not indexing in summary files. The problem is that we have multiple versions of a single scan discovered. That cannot be tolerated as ExploreASL cannot deal with that. It then randomly converts a single scan and reports missing scans that are actually there.
So as a new solution, we report an error that the user needs to specify more clearly which scans to take to avoid ambiguous entries.

### Release notes

Warning when duplicate scans are detected.

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

Close #1766

### CODE REVIEW

File: Modules/Module_Import/xASL_wrp_DCM2NII_Subject.m [hunk 1]
```diff
@@ -103,6 +103,12 @@
             end
             
             %% 4. Iterate over scans
+			% Safety-check, we can't allow multiple matches for the same sequence
+			if numel(thisRun.scanIDs) ~= numel(unique(thisRun.scanIDs))
+				fprintf('Detected duplicit scans: %s\n',strjoin(thisRun.scanIDs, ', '));
+				error('We do not allow multiple matches per scan for. Please delete some sequences or adjust sourcestructure.json');
```
Comment (HenkMutsaerts) [inline Modules/Module_Import/xASL_wrp_DCM2NII_Subject.m]: should be

error('We do not allow multiple token matches per scantype. Please adjust sourcestructure.json');

For clarity, but most importantly users should NOT delete sourcedata! Ideally this is always readonly, because from the philosophy of BIDS sourcedata is always exactly what you got, without restructuring etc. I know this is not what we do yet for practical reasons, but you get my point :)

File: Modules/Module_Import/xASL_wrp_DCM2NII_Subject.m [hunk 2]
```diff
@@ -103,6 +103,12 @@
             end
             
             %% 4. Iterate over scans
+			% Safety-check, we can't allow multiple matches for the same sequence
+			if numel(thisRun.scanIDs) ~= numel(unique(thisRun.scanIDs))
+				fprintf('Detected duplicit scans: %s\n',strjoin(thisRun.scanIDs, ', '));
```
Comment (HenkMutsaerts) [inline Modules/Module_Import/xASL_wrp_DCM2NII_Subject.m]: duplicit -> duplicate

No, “duplicit” is not a correct word in English. The correct word you’re thinking of is “duplicate”, which refers to something that is an exact copy or reproduction of another item.

There might be confusion with “duplicitous,” which is an adjective used to describe someone as being deceitful or two-faced. However, “duplicit” on its own is not recognized as an English word.

Thanks chatGPT :)

**Review by HenkMutsaerts — APPROVED** [review]
Two minor comments that you can easily fix without me having to re-approve

File: Modules/Module_Import/xASL_wrp_DCM2NII_Subject.m (hunk 2 above)
Comment (jan-petr) [reply Modules/Module_Import/xASL_wrp_DCM2NII_Subject.m]: nice. fixed.

File: Modules/Module_Import/xASL_wrp_DCM2NII_Subject.m (hunk 1 above)
Comment (jan-petr) [reply Modules/Module_Import/xASL_wrp_DCM2NII_Subject.m]: good point. fixed.
