### PR TITLE
Bug #1705 tumor population

### LINKED ISSUE #1705: Tumor population analysis
### Description

Making sure that the population analysis runs correctly for Ivar with Lesion_T1_1.nii

### Tasks

- [x] Incorrect removal of temporary data.
- [x] Make sure the standard space analysis runs.
- [x] Native space analysis has issues with MRAcquisitionType not found.
- [x] Make sure the native space analysis runs.
- [x] Check that Lesion files are created in native space
- [x] Run stats also on Lesion files -> or create a new issue for that. Will be done in #58 

### Release notes

Transform Lesion and ROI - T1 files into ASL space.

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

Close #1705

### CODE REVIEW

File: Modules/Module_Processing/Module_ASL/xASL_wrp_PreparePV.m [hunk 1]
```diff
@@ -143,22 +143,54 @@
...
+
+% Create a list of lesions
+LesionROIList = xASL_adm_GetFileList(fullfile(x.D.ROOT, x.SUBJECT), '(?i)^(Lesion|ROI)_(T1|FLAIR|T2)_\d*\.(nii|nii\.gz)', 'List', [0 Inf]);
+
+% Go through all the lesions
+for iROI = 1:length(LesionROIList)
+	LesionROIName = LesionROIList{iROI};
+
+	% Unzip and remove .gz extension if necessary
+	if ~isempty(regexpi(LesionROIName, '\.gz$', 'once'))
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/Module_ASL/xASL_wrp_PreparePV.m]: This is redundant code, you can just run xASL_adm_UnzipNifti which will automatically only unzip if needed

File: Modules/Module_Processing/Module_ASL/xASL_wrp_PreparePV.m [hunk 2]
```diff
@@ -143,22 +143,54 @@
...
 end
 
+% Transform WMH segmentation maps to the ASL space
 if xASL_exist(x.P.Path_WMH_SEGM) 
 	xASL_im_PreSmooth(x.P.Path_PWI,x.P.Path_WMH_SEGM, x.P.Path_PVwmh,x.S.optimFWHM_Res_mm,[],x.P.Path_mean_PWI_Clipped_sn_mat, 1);
 	xASL_spm_reslice(x.P.Path_PWI, x.P.Path_PVwmh, x.P.Path_mean_PWI_Clipped_sn_mat, 1, x.settings.Quality, x.P.Path_PVwmh);
 end
 
+% Transform Lesion and ROI masks to the ASL space. Note that we transform binary masks to maps with values between 0 and 1 so that the PV factor is recorded.
+% The maps have then have to be binarized again with a given threshold before using them again as masks
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/Module_ASL/xASL_wrp_PreparePV.m]: Where do we binarize again?
The threshold to binarize is unknown to the user? So depending on resolution differences, the mask will change. 
I would binarize again in the new space (which also saves space, and then we control this just using p>0.5). One other thing we could do, is adapting the threshold such that the volume stays the same in old and new space. But I don't know how significant this bias could be/how important this is. I would in any case not leave this to the user:

We have either probabilistic or binary masks. This should always be due to the segmentation, not to our resampling. Because it becomes then difficult to judge by the user if the probabilities are "real" probabilities (method/PV) or "induced by smoothing/resampling".

File: Modules/Module_Processing/Module_ASL/xASL_wrp_ResampleASL.m [hunk 3]
```diff
@@ -319,8 +319,6 @@ function xASL_wrp_ResampleASL(x)
     end
     xASL_adm_DeleteFilePair(x.P.Path_rtemp_despiked_ASL4D, 'mat', 'json');
     xASL_adm_DeleteFilePair(x.P.Path_temp_despiked_ASL4D, 'mat', 'json');
-else
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/Module_ASL/xASL_wrp_ResampleASL.m:322]: Why is this removed? I cannot judge this from this issue?

Probably we want to keep the temporary ASL4D when DELETETEMP is off, because you use it to create new derivatives in standard space, for CBF4D or whatsoever. There must be a reason I put it there ;)

File: Modules/Module_Processing/xASL_init_DefaultEffectiveResolution.m [hunk 4]
```diff
@@ -48,6 +48,17 @@
     return;
 end
 
+% Obtain the x.Q.MRAcquisitionType field from the json
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/xASL_init_DefaultEffectiveResolution.m]: Are you sure we also have PulseSequence here? Because remember we concluded they should always be together (one is 2D/3D, the other is EPI/GRASE/spiral).

File: Modules/Module_Processing/xASL_init_DefaultEffectiveResolution.m [hunk 5]
```diff
@@ -48,6 +48,17 @@
...
+if ~isempty(tJson) && isfield(tJson, 'Q') && isfield(tJson.Q, 'MRAcquisitionType')
+	x.Q.MRAcquisitionType = tJson.Q.MRAcquisitionType;
+end
+
+% If sequence is still missing we skip this function
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/xASL_init_DefaultEffectiveResolution.m:49]: Will it not be defaulted to something that is potentially wrong? Not sure if we should always avoid crashing in case of "illegal" data.

**Review by HenkMutsaerts — CHANGES_REQUESTED** [review]

File: Modules/Module_Processing/Module_ASL/xASL_wrp_PreparePV.m (hunk 1 above)
Comment (jan-petr) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_PreparePV.m]: I know. xASL_adm_UnzipNifti can be run without it. But I need to adapt the name of the lesion for input/output and also for calling SPM.

File: Modules/Module_Processing/Module_ASL/xASL_wrp_PreparePV.m (hunk 2 above)
Comment (jan-petr) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_PreparePV.m]: Currently nowhere, because we are not yet doing native-space analysis with ROIs and Lesions -> this is currently missing and has to be implemented. But rather than doing the thresholding here, it might be wiser to do it directly in the population moduel as we can nicely adapt this and change this later or even make it somehow variable. 
Haha - of course not leaving that to the user. I'm just leaving the question of correct threshold for the population module. This comment is not for the user but for our record.

Fully agree about probabilistic/binary. But since I call this PVLesion_T1_1, it makes it clear in the name that this is probabilistic rather than binary. 

Yes - in ideal world, we don't change probabilistic to binary and vice versa. But tumor are rather tricky and I don't want to make a clear decision on how to threshold it. It would be wrong to cut it at 50% as we can miss a large part of the tumor as these tend to be very thin at certain times. So this decision should be made in the population module and we either consider the PV or we threshold.

File: Modules/Module_Processing/Module_ASL/xASL_wrp_ResampleASL.m (hunk 3 above)
Comment (jan-petr) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_ResampleASL.m:322]: That was a bug. tmp_despiked was already saved in the code above. 
So this was a forgotten saving that was useless as no "ASL" variable exists anymore at this line. 

So we were revamping the code, moved the saving above and forgot to delete this line in previous issues.

File: Modules/Module_Processing/xASL_init_DefaultEffectiveResolution.m (hunk 4 above)
Comment (jan-petr) [reply Modules/Module_Processing/xASL_init_DefaultEffectiveResolution.m]: Yes. I'm sure. We have always a combination PulseSequenceType and MRAcquisitionType (like you say). And we always load them together and evaluate together. But we somehow forgot to do this also here.

File: Modules/Module_Processing/xASL_init_DefaultEffectiveResolution.m (hunk 5 above)
Comment (jan-petr) [reply Modules/Module_Processing/xASL_init_DefaultEffectiveResolution.m:49]: Previously, we were defaulting to 3DGrase or something. And you decided to remove this defaulting. 

I'm happy to insert "crash" here if you want...

File: Modules/Module_Processing/Module_ASL/xASL_wrp_PreparePV.m (hunk 2 above)
Comment (HenkMutsaerts) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_PreparePV.m]: I would argue why the ASL native space lesion mask needs to be implemented. "Because Ivar asks for it" is not a good argument. Otherwise, I see your point.

File: Modules/Module_Processing/Module_ASL/xASL_wrp_PreparePV.m (hunk 1 above)
Comment (HenkMutsaerts) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_PreparePV.m]: Doesn't xASL_adm_UnzipNifti give the bare .nii name as output? I thought that was the whole reason of this function, to avoid 5 lines of code.

File: Modules/Module_Processing/xASL_init_DefaultEffectiveResolution.m (hunk 5 above)
Comment (HenkMutsaerts) [reply Modules/Module_Processing/xASL_init_DefaultEffectiveResolution.m:49]: I would say that we need a single check that either MRAcquisitionType or PulseSequenceType is missing, and then we issue an error. Because this should already be covered by BIDS.

We can also add this to our generic parameter check at the beginning of the ASL module, then you can remove the check here (because submodule you start the ASL module with, it always needs to pass this generic parameter check).

File: Modules/Module_Processing/Module_ASL/xASL_wrp_PreparePV.m (hunk 1 above)
Comment (jan-petr) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_PreparePV.m]: no. it gives the full path. i need the name only...

File: Modules/Module_Processing/Module_ASL/xASL_wrp_PreparePV.m (hunk 2 above)
Comment (jan-petr) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_PreparePV.m]: we wanted to have native space analysis and that has to be complete. It's only that I forgot about this option when doing native space analysis. And only Ivar actually discovered this shortcoming. So it's not adding that because he wanted it. But it's somethign that should have been there from the get go, but it wasn't and he discovered that.

File: Modules/Module_Processing/xASL_init_DefaultEffectiveResolution.m (hunk 5 above)
Comment (jan-petr) [reply Modules/Module_Processing/xASL_init_DefaultEffectiveResolution.m:49]: We are already checking the parameter presence at the start of ASL modules.

I've changed the code to an error. So in case they are missing, I'm issuing a full error. But that's a safety catch cause that situation wouldn't happen here.

File: Modules/Module_Processing/Module_ASL/xASL_wrp_PreparePV.m (hunk 2 above)
Comment (HenkMutsaerts) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_PreparePV.m]: You know my opinion ;)

I have now fixed this by adding many warnings and making the code clear that this needs fixing when we fix the whole native space mess.

File: Modules/Module_Processing/Module_ASL/xASL_wrp_PreparePV.m (hunk 1 above)
Comment (HenkMutsaerts) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_PreparePV.m]: See my fix

**Review by HenkMutsaerts — APPROVED** [review]
OK, if you agree with my minor revamp
