### PR TITLE
Closes #936 Check directories for reruns/crashed imports

### LINKED ISSUE #936: Import module incorrectly says "has been run before"
### Description

If the import module has been run but crashed, it will still not allow rerunning — unless the user removes the `derivatives` folder. I thought the import module would now modularly check each subject? Does it only check if the subject folder exists? Or does it also check if the folder contains valid NIfTI files etc?

It should use the lock files appropriately, if import was run before, but crashed, these lock files won't exist, so should rerun. It should not be dependent on existence of folders.

### Requirements

Optional: add bug requirements here

### How to test

Put an error in different places of the import modules, the modularity should work in each case, and be independent of existence of folders etc. Also try putting an error at the beginning of the import module, this should also work.

### Release notes

Required: summarize the changes for the release notes here

### PR DESCRIPTION
**Pull request by MichaelStritt**
### Linked issue

Closes #936

### CODE REVIEW

**Comment by MichaelStritt** [comment]
@jan-petr & @HenkMutsaerts: I don't really know how this is supposed to work in some cases. For NII2BIDS it is somewhat easy, because we can just check if the rawdata ASL or T1 folder already exists and delete it for the reruns or when the pipeline crashed. For BIDS2Legacy this is problematic, because we do the import on subject level and as I said before, as long as we don't have subject directories in legacy, this is kind of impossible. For DCM2NII I know there was a previous option with bOverwrite and so on. Maybe we can use that. Other than that I don't know how I should check for existing directories if one directory can be the top of the other one (T1 on top of ASL e.g.) or if we don't exactly know all of the output scans of DCM2NII beforehand. Nevertheless, I think the implemented code is an improvement for NII2BIDS and there are some simplifications for BIDS2Legacy.

File: Modules/SubModule_Import/xASL_bids_BIDS2Legacy.m [hunk 1]
```diff
@@ -97,21 +96,23 @@
 
         %% 3. Define Session
         iVisit = find(strcmp(BIDS.sessionName, SessionID));
-        % remove iteration for iVisit=1 % iterate visit/session in this "BIDS.subjects" (always 1 session per BIDS.subjects)
+        % Remove iteration for iVisit = 1 -> iterate visit/session in this "BIDS.subjects" (always 1 session per BIDS.subjects)
         % ExploreASL uses visit as a number (e.g. _1 _2 _3 etc)
         if nVisits==1
-            pathLegacy_SubjectVisit = fullfile(pathLegacy, SubjectID);
+            pathLegacy_SubjectVisit = fullfile(x.dir.pathLegacy, SubjectID);
```
Comment (HenkMutsaerts) [inline Modules/SubModule_Import/xASL_bids_BIDS2Legacy.m:102]: If we have `x.dir.DatasetRoot`, would make it more consistent to also have `x.dir.raw` and `x.dir.derivatives`? `x.dir.pathLegacy` is a new name, not clear to the new reader, but pathDerivatives or something similar is clear (and this is what we mean here right?

File: Modules/SubModule_Import/xASL_imp_BIDS2Legacy.m [hunk 2]
```diff
@@ -50,39 +50,37 @@
...
-		if length(fListDataPar) > 1
-			warning('Multiple dataPar*.jsons exist. Using the first: %s\n',fListDataPar{1});
-		end
-		% Fill the dataPars with the provided parameters
-		x.dataPar = spm_jsonread(fListDataPar{1});
-		x = xASL_bids_BIDS2Legacy(localDatasetRoot, x, 1);
+	fListDataPar = xASL_adm_GetFileList(x.dir.DatasetRoot,'(?i)(^dataPar.*\.json$)', 'FPList', [], 0);
+    if length(fListDataPar) < 1
+        % Fill the dataPars with default parameters
+        fprintf('There is no dataPar.json file in the study root directory. Default settings will be used...\n');
```
Comment (HenkMutsaerts) [inline Modules/SubModule_Import/xASL_imp_BIDS2Legacy.m:73]: What happens if, at the start of the whole import, only `/DatasetRoot/derivatives/ExploreASL/dataPar.json` exists? That would be the first thing a user would try right? At least this shouldn't be overwritten. Perhaps we can detect this, copy to the datasetRoot, and issue a warning that this was found and will be used.

File: Modules/SubModule_Import/xASL_imp_DCM2NII_ConvertScan.m [hunk 3]
```diff
@@ -88,7 +88,8 @@
             bPutInSessionFolder = false;
     end
 
-    if ~isempty(strfind(char(imPar.folderHierarchy(end)),'PAR'))
+    % Check for old PARREC data
```
Comment (HenkMutsaerts) [inline Modules/SubModule_Import/xASL_imp_DCM2NII_ConvertScan.m:91]: I just removed this in #938

**Review by HenkMutsaerts — CHANGES_REQUESTED** [review]
For the rerun, I would:

* base rerunning and overwriting or skipping per subject only on the existence of the lock files, identical to how this is managed in the processing modules. So if a lock/status file doesn't exist, this means that the current subject wasn't correctly run, and the previous rawdata should be deleted
* ensure that the lock/status files are only created after successful import of a single subject
* always overwrite existing rawdata or derivatives for the current subject (since overwriting/skipping is managed by the lock/status files)

So instead of checking folders, files, what if they exist partly, etc, etc, you only rely on the lock files (unless you create a `bCompletelyRerunImport` parameter of course, in that case you delete all lock files). Makes the code/program also much more transparent.

**Comment by MichaelStritt** [comment]
> So instead of checking folders, files, what if they exist partly, etc, etc, you only rely on the lock files

And that doesn't work on your side? If one of the import steps crashes for me, then the lock file is not created and on a rerun it reruns the sub-module. I think we should make it cleaner and remove some files/folders for the import reruns, because I'm not sure if every xASL_Move command or the used tools work with overwrite, but other than that this part should be fine. Please actually describe the defect/failure behavior.

File: Modules/SubModule_Import/xASL_imp_DCM2NII_ConvertScan.m (hunk 3 above)
Comment (MichaelStritt) [reply Modules/SubModule_Import/xASL_imp_DCM2NII_ConvertScan.m:91]: Okay? Then it will be a part of the conflict resolving, I guess?

File: Modules/SubModule_Import/xASL_bids_BIDS2Legacy.m (hunk 1 above)
Comment (jan-petr) [reply Modules/SubModule_Import/xASL_bids_BIDS2Legacy.m:102]: Very good comment. `DatasetRoot` is good for the root to all directories. `RawData`, `SourceData`, `Derivatives` might be used as well. So while we are at it, we can probably change `pathLegacy` to `Derivatives`, but it can't be just derivatives - that would preclude further extensions and `xASLDerivatives` might be better - just to show that we don't mean root derivatives folder. In general, regarding use of `Legacy` - apart from this case, we don't need to rename it that much, because all Legacy will be later renamed to fit better the BIDS derivatives format.

File: Modules/SubModule_Import/xASL_imp_DCM2NII_ConvertScan.m (hunk 3 above)
Comment (jan-petr) [reply Modules/SubModule_Import/xASL_imp_DCM2NII_ConvertScan.m:91]: Yes, that's going to be part of resolving indeed. BUT, in #938, Henk did an equivalent fix as you did here and moved the code elsewhere. It is thus easier to restore this (with a new commit) to the previous state - it will save us some hassle with the conflict solving.

**Review by jan-petr — CHANGES_REQUESTED** [review]
Minor comments only.

File: Modules/SubModule_Import/xASL_imp_DCM2NII_ConvertScan.m (hunk 3 above)
Comment (MichaelStritt) [reply Modules/SubModule_Import/xASL_imp_DCM2NII_ConvertScan.m]: 3e79423 ?

Comment (MichaelStritt) [reply Modules/SubModule_Import/xASL_imp_DCM2NII_ConvertScan.m]: Reverted 👍

File: Modules/SubModule_Import/xASL_bids_BIDS2Legacy.m (hunk 1 above)
Comment (MichaelStritt) [reply Modules/SubModule_Import/xASL_bids_BIDS2Legacy.m]: Done

File: Modules/SubModule_Import/xASL_imp_BIDS2Legacy.m (hunk 2 above)
Comment (MichaelStritt) [reply Modules/SubModule_Import/xASL_imp_BIDS2Legacy.m:73]: The workflow already checks for dataPar.json files in derivatives. I added a print statement for you 2fc744d

**Comment by MichaelStritt** [comment]
Still think we should implement a sub/ses/run structure in the xASL derivatives and optimize the temp structure, so that reruns can be done in an easier way by removing pre-existing data from pipeline crashes etc.

**Comment by HenkMutsaerts** [comment]
> @jan-petr & @HenkMutsaerts: I don't really know how this is supposed to work in some cases. For NII2BIDS it is somewhat easy, because we can just check if the rawdata ASL or T1 folder already exists and delete it for the reruns or when the pipeline crashed. For BIDS2Legacy this is problematic, because we do the import on subject level and as I said before, as long as we don't have subject directories in legacy, this is kind of impossible. For DCM2NII I know there was a previous option with bOverwrite and so on. Maybe we can use that. Other than that I don't know how I should check for existing directories if one directory can be the top of the other one (T1 on top of ASL e.g.) or if we don't exactly know all of the output scans of DCM2NII beforehand. Nevertheless, I think the implemented code is an improvement for NII2BIDS and there are some simplifications for BIDS2Legacy.

I would use the existence of lock files, so we don't have to check folders, because that is arbitrary. `BIDS2Legacy` is much faster than the other import submodules, so I wouldn't worry too much if that needs rerunning; plus this needs to be moved to the processing part anyway (and we will add subject directories in legacy as you say in the future).

The import should always overwrite (so `bOverwrite` is always true), and if a lock file exists, importing of a subject is skipped. That should work right?

**Comment by HenkMutsaerts** [comment]
> > So instead of checking folders, files, what if they exist partly, etc, etc, you only rely on the lock files
> 
> And that doesn't work on your side? If one of the import steps crashes for me, then the lock file is not created and on a rerun it reruns the sub-module. I think we should make it cleaner and remove some files/folders for the import reruns, because I'm not sure if every xASL_Move command or the used tools work with overwrite, but other than that this part should be fine. Please actually describe the defect/failure behavior.

OK if this works for you, then this is fine. Your reasoning is correct here. I think my point here was that the import incorrectly said "has been run before". So this was an error on the beginning, not in the iteration.

**Comment by HenkMutsaerts** [comment]
> Still think we should implement a sub/ses/run structure in the xASL derivatives and optimize the temp structure, so that reruns can be done in an easier way by removing pre-existing data from pipeline crashes etc.

Yep good point for version 2.0

**Comment by HenkMutsaerts** [comment]
PS: why are we discussing here, shouldn't we discuss in the issue?

File: Functions/xASL_init_DetermineRequiredPaths.m [hunk 4]
```diff
@@ -34,12 +34,21 @@
     % BIDS DatasetRoot directory
     x.dir.DatasetRoot = x.opts.DatasetRoot;
     x.opts.dataParType = 'directory';
+    
+    % Set other basic BIDS directories
+    x.dir.SourceData = fullfile(x.opts.DatasetRoot,'sourcedata');
```
Comment (HenkMutsaerts) [inline Functions/xASL_init_DetermineRequiredPaths.m:39]: Nice to have all in `x.dir`. I don't understand the difference between `x.opts` and `x.dir` here. Is x.opt necessary as a separate input options field? Don't all input options fall under some other field?

File: Modules/SubModule_Import/xASL_imp_NII2BIDS_Subject.m [hunk 5]
```diff
@@ -34,6 +34,11 @@
     subjectDirectory = fullfile(imPar.BidsRoot,['sub-' bidsLabel.subject]);
     if ~xASL_exist(subjectDirectory,'dir')
```
Comment (HenkMutsaerts) [inline Modules/SubModule_Import/xASL_imp_NII2BIDS_Subject.m:35]: You can simplify this by moving `xASL_adm_CreateDir` outside, and below, the if statement.
`xASL_adm_CreateDir` always checks if a folder exists before creating it.

File: Modules/SubModule_Import/xASL_imp_DCM2NII_ConvertScan.m [hunk 6]
```diff
@@ -149,6 +149,15 @@
     end
 
     %% 4.6 Start the conversion if this scan should not be skipped
+
```
Comment (HenkMutsaerts) [inline Modules/SubModule_Import/xASL_imp_DCM2NII_ConvertScan.m:152]: Indeed, if everything is done on the subject level, then everything should be managed at the subject level. So we either delete everything for a single subject and rerun everything for this subject, or we don't at all.

File: Modules/SubModule_Import/xASL_imp_BIDS2Legacy.m (hunk 2 above)
Comment (HenkMutsaerts) [reply Modules/SubModule_Import/xASL_imp_BIDS2Legacy.m:73]: I would solve this differently. `dataPar.json` contains settings for processing, and you recommend the user to put this in `/datasetRoot`, and then at the end of the `BIDS2legacy` submodule, this `dataPar.json` will be merged with the new fields that are generated automatically, if these fields didn't exist (e.g., `x.Quality`, `x.SUBJECTS` etc). At least, this should happen!

My point here was that, if the user created a `/datasetRoot/derivatives/ExploreASL/dataPar.json` instead of `/datasetRoot/dataPar.json`, you move the `/datasetRoot/derivatives/ExploreASL/dataPar.json` to `/datasetRoot/dataPar.json`, so that in the end of the `BIDS2legacy` submodule, they will be merged appropriately.

If the user reruns ExploreASL and forgets to delete the previous `/datasetRoot/derivatives/ExploreASL/dataPar.json`, this is the user's fault (or we could warn the user at the beginning of all modules everything, if no lock files exist yet, if you want).

File: Modules/SubModule_Import/xASL_bids_BIDS2Legacy.m [hunk 7]
```diff
@@ -33,48 +32,52 @@
...
 
 % Verify that the rawdata subfolder exists
-if ~exist(fullfile(pathStudy,'rawdata'),'dir')
+if ~exist(fullfile(x.dir.DatasetRoot,'rawdata'),'dir')
     warning('Invalid folder selected, not containing rawdata folder');
     return;
 end
 
+% Check derivatives of ExploreASL
+if ~isfield(x.dir,'xASLDerivatives')
```
Comment (HenkMutsaerts) [inline Modules/SubModule_Import/xASL_bids_BIDS2Legacy.m:58]: Note that nobody knows what "xASL" means, that is just an abbreviation that we use internally. Best to replace this by "ExploreASL derivatives folder" or something that doesn't lead to the user asking you what you meant ;)

**Review by HenkMutsaerts — CHANGES_REQUESTED** [review]
Some suggestions, hope this helps you also understanding this from a user perspective, which can be very useful in software development!

File: Functions/xASL_init_DetermineRequiredPaths.m (hunk 4 above)
Comment (MichaelStritt) [reply Functions/xASL_init_DetermineRequiredPaths.m:39]: Don't think this is the right issue/PR or the right time to restructure this again.

File: Modules/SubModule_Import/xASL_imp_NII2BIDS_Subject.m (hunk 5 above)
Comment (MichaelStritt) [reply Modules/SubModule_Import/xASL_imp_NII2BIDS_Subject.m]: 10deab0

File: Modules/SubModule_Import/xASL_bids_BIDS2Legacy.m (hunk 7 above)
Comment (MichaelStritt) [reply Modules/SubModule_Import/xASL_bids_BIDS2Legacy.m:58]: This should only occur if it really crashes. In that case it doesn't make sense for the user to know that one x field which isn't called "ExploreASL derivatives folder" is missing. 

We should differentiate between warnings for users and warnings for developers.
