### PR TITLE
Closes #1881 groupwise qc rms

### LINKED ISSUE #1881: Improve group-wise QC based on similarity with group-template
### Description

Comparing (smoothed) individual images with the group-template can perhaps be a good way to speed up QC.

### Tasks
- [x] xASL_stat_RobustMean: also output RMS with mean template
- [x] xASL_wrp_CreatePopulationTemplates: Add RMS with mean template output
- [x] xASL_bids_Add2ParticipantsTSV: Bugfix checking number of columns
- [x] xASL_bids_Add2ParticipantsTSV: allow custom pathTSV
- [x] xASL_wrp_CreatePopulationTemplates: Add RMS output

### Miscellaneous tasks/bugs
- [x] xASL_init_Session_TimePoint_Lists: when you have ASL_n also in subfolders other than the designated subject folders, it will find them and incorrectly determine the number of sessions
- [x] xASL_ext_FSLTopUp: bugfix parameter TopUp path
- [x] xASL_imp_ReadoutSourceData: bugfix filename containing extension such as ima ging
- [x] xASL_wrp_NII2BIDS: code simplification
- [x] xASL_init_LoadMetadata: Speeding up variable reading
- [x] xASL_bids_GenerateParticipantsJSON: extra options

### PM, let's leave this for later
* Copy the ASL_Check images to a QC_folder where the names are 1_sub-045_ASL_2 2_sub-078_ASL_2 etc, with the first number meaning the sorted "distance" from the template defined as RMS
* The user is then helped doing the visual QC based on the similarity with the group-average, e.g. "We repeated our analysis with excluding 5% subjects with worst ASL scans and excluding 25% subjects with worst ASL scans, defined by their RMS of voxel-wise difference with the group-average."

### How to test

Henk tests this with AMYPAD & DDI processing

### Release notes

Added /Population/Stats/QC_RMS.tsv containing difference from template, to guide QC

### PR DESCRIPTION
**Pull request by HenkMutsaerts**
### Linked issue

Closes #1881

### CODE REVIEW

File: Functions/BIDS/xASL_bids_Add2ParticipantsTSV.m [hunk 1]
```diff
@@ -1,4 +1,4 @@
-function xASL_bids_Add2ParticipantsTSV(DataIn, DataName, x, bOverwrite)
+function xASL_bids_Add2ParticipantsTSV(DataIn, DataName, x, bOverwrite, PathTSV)
 %xASL_bids_Add2ParticipantsTSV Add data to participants.tsv
 %
 % FORMAT: xASL_bids_Add2ParticipantsTSV(DataIn, DataName, x[, bOverwrite])
```
Comment (jan-petr) [inline Functions/BIDS/xASL_bids_Add2ParticipantsTSV.m]: Add the parameter to FORMAT and to INPUT.

File: Functions/BIDS/xASL_bids_GenerateParticipantsJSON.m [hunk 2]
```diff
@@ -130,13 +131,13 @@ function xASL_bids_GenerateParticipantsJSON(x)
                 
 
                 %% 4b. Manage units
-                if contains(descriptionBIDS, 'cbf')
+                if ~isempty(regexpi(descriptionBIDS, '(cbf|cerebral blood flow)'))
                     jsonParticipants.(lower(listKeys{iList})).Units = 'mL/100g/min';
-                elseif contains(descriptionBIDS, 'abv')
+                elseif ~isempty(regexpi(descriptionBIDS, ('abv|arterial blood volume)')))
```
Comment (jan-petr) [inline Functions/BIDS/xASL_bids_GenerateParticipantsJSON.m]: ('abv|arterial blood volume)'))) 
should be
'(abv|arterial blood volume)'))

File: Functions/Statistics/xASL_stat_RobustMean.m [hunk 3]
```diff
@@ -1,4 +1,4 @@
-function [NotOutliers, iOutliers] = xASL_stat_RobustMean(IM, ParameterFunction)
+function [NotOutliers, iOutliers, RMS] = xASL_stat_RobustMean(IM, ParameterFunction)
 % Submodule of ExploreASL Structural module, that obtains volumes from the tissue segmentations
 % (& FLAIR WMH segmentations if they exist)
 %
```
Comment (jan-petr) [inline Functions/Statistics/xASL_stat_RobustMean.m:4]: Add RMS to OUTPUT
Modify FORMAT - it should have RMS and should not have ThresholdDeviation

File: Functions/Statistics/xASL_stat_RobustMean.m [hunk 4]
```diff
@@ -50,40 +49,38 @@
...
+MedianIM = repmat(xASL_stat_MedianNan(IM, 2), [1 Size4]);
 
-if strcmp(ParameterFunction,'SoS')
-     ValueMask = abs(IM - MedianIM);
-elseif strcmp(ParameterFunction,'AI')
-     ValueMask = abs(IM - repmat(IMtemp,[1 Size4])) ./ (0.5.*(IM + repmat(IMtemp,[1 Size4]))); % weighted SoS, AI
-end        
+if strcmpi(ParameterFunction,'SoS')
+     DiffIm = (IM - MedianIM).^2;
+     Deviation = xASL_stat_MeanNan(DiffIm, 1); % gives deviation sum per image, higher is worse quality
```
Comment (jan-petr) [inline Functions/Statistics/xASL_stat_RobustMean.m:64]: It calculates it along the first dimension. If the input is [X,Y,Z] then the output will not be a scalar, but [1, Y, Z]. 
Is this what you really want?!

File: Modules/Module_Processing/Module_Population/xASL_wrp_CreatePopulationTemplates.m [hunk 5]
```diff
@@ -1,4 +1,4 @@
-function xASL_wrp_CreatePopulationTemplates(x, bSaveUnmasked, bCompute4Sets, SpecificScantype, bSkipWhenMissingScans, bRemoveOutliers, FunctionsAre, bUpdateMetadata, SmoothingFWHM, bSaveMasks4QC)
+function RMS = xASL_wrp_CreatePopulationTemplates(x, bSaveUnmasked, bCompute4Sets, SpecificScantype, bSkipWhenMissingScans, bRemoveOutliers, FunctionsAre, bUpdateMetadata, SmoothingFWHM, bSaveMasks4QC)
 %xASL_wrp_CreatePopulationTemplates ExploreASL Population module wrapper,
 %creates population parametric images for each ScanType
 %
```
Comment (jan-petr) [inline Modules/Module_Processing/Module_Population/xASL_wrp_CreatePopulationTemplates.m:4]: Update FORMAT and OUTPUT

**Review by jan-petr — CHANGES_REQUESTED** [review]
A few small bugs

File: Functions/Statistics/xASL_stat_RobustMean.m (hunk 4 above)
Comment (HenkMutsaerts) [reply Functions/Statistics/xASL_stat_RobustMean.m:64]: Yes, the input is the column/vector image (masked), not a 3D image, for efficiency

File: Functions/Statistics/xASL_stat_RobustMean.m (hunk 3 above)
Comment (HenkMutsaerts) [reply Functions/Statistics/xASL_stat_RobustMean.m:4]: Fixed in 934b26e8f5fb0f9a84273cc6f5b7ffb3c4d053f7

File: Functions/BIDS/xASL_bids_GenerateParticipantsJSON.m (hunk 2 above)
Comment (HenkMutsaerts) [reply Functions/BIDS/xASL_bids_GenerateParticipantsJSON.m]: Fixed in 934b26e8f5fb0f9a84273cc6f5b7ffb3c4d053f7

File: Functions/BIDS/xASL_bids_Add2ParticipantsTSV.m (hunk 1 above)
Comment (HenkMutsaerts) [reply Functions/BIDS/xASL_bids_Add2ParticipantsTSV.m]: Fixed in 934b26e8f5fb0f9a84273cc6f5b7ffb3c4d053f7

**Review by jan-petr — APPROVED** [review]
OK
