### PR TITLE
Closes #1375 xASL_wrp_RealignASL: Option fixed threshold

### LINKED ISSUE #1375: Motion Threshold for outlier exclusion
### Description

To incude the possibility to choose a fixed threshold for the exclusion of motion spikes (as alternative to the threshold-free spike removal method). 

### Tasks

- [x] Implement removal of spike frames from PWI using a chosen NDV threshold in function xASL_wrp_RealignASL(x, bASL).
- [x] Write the excluded frames per scan to matfile  -> HENK: was already fixed before
- [x] Provide mean NDV before and after exclusion of the scrubbed frames -> HENK: was already fixed before
- [x] Add new parameter to `https://github.com/ExploreASL/Documentation/blob/master/source/ProcessingParameters.md`

### How to test

Add `x.modules.asl.SpikeRemovalAbsoluteThreshold` to `dataPar.json` (e.g., 0.05 mm)

### Release notes

Add an option for absolute threshold on motion spike removal.

### PR DESCRIPTION
**Pull request by HenkMutsaerts**
### Linked issue

Closes #1375

### How to test

Required: if not defined in the linked issue, add a simple test description here

### Comments

Optional: add helpful comments for the reviewers here

### CODE REVIEW

File: Modules/SubModule_ASL/xASL_wrp_RealignASL.m [hunk 1]
```diff
@@ -129,34 +107,75 @@ function xASL_wrp_RealignASL(x, bASL)
...
+    bSpikeRemoval = false;
+    bENABLE = true;
+
+elseif ~isfield(x.modules.asl,'SpikeRemovalAbsoluteThreshold')
+    x.modules.asl.SpikeRemovalAbsoluteThreshold = 0; % disable by default
+    bSpikeRemoval = false;
+    bENABLE = true;
+
+elseif ~isnumeric(x.modules.asl.SpikeRemovalAbsoluteThreshold) || x.modules.asl.SpikeRemovalAbsoluteThreshold<0 || x.modules.asl.SpikeRemovalAbsoluteThreshold>1
+    % If the field exists (as evidenced by the previous elseif) we check if
```
Comment (jan-petr) [inline Modules/SubModule_ASL/xASL_wrp_RealignASL.m:144]: I have tried to fix this already. But you fixed it back :)
In both branches at line 144 and line 151 - SpikeRemovalThreshold is not existing and on line 144 bENABLE and bSpikeRemoval are not existing - this was what I was trying to fix.

**Review by jan-petr — CHANGES_REQUESTED** [review]

File: Modules/SubModule_ASL/xASL_wrp_RealignASL.m (hunk 1 above)
Comment (HenkMutsaerts) [reply Modules/SubModule_ASL/xASL_wrp_RealignASL.m:144]: Now fixed. Note that `SpikeRemovalAbsoluteThreshold` is not required if you set `bSpikeRemoval` to false

**Review by jan-petr — APPROVED** [review]
OK.
