### PR TITLE
#1890 Fix AAL atlas

### LINKED ISSUE #1890: Fix AAL atlas
### Description

The AAL atlas is incorrectly saved an aligned.

### Tasks

- [x] The main issue is that the original atlas AAL3v1 isn't aligned to any of the MNI2009 or ICBM152 atlases, but it is rather created on colin27 atlas. So we need to segment AAL3v1 using CAT12 to obtain the colin27->IXI512 alignment. And then this must be applied to AAL3v1.
- [x] Furthermore, AAL3v is split to left and right regions. We need to merge this and the splitting to hemispheres is done in ExploreASL
- [x] Fix the script
- [x] Perform the transformation and save the new atlas

### Release notes

Nothing. Report together with #1855

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

Close #1890

### CODE REVIEW

File: WorkInProgress/Administration/xASL_adm_CoregisterAtlas.m [hunk 1]
```diff
@@ -1,4 +1,4 @@
-% Copyright 2015-2024 ExploreASL (Works In Progress code)
+% Copyright 2015-2025 ExploreASL (Works In Progress code)
```
Comment (HenkMutsaerts) [inline WorkInProgress/Administration/xASL_adm_CoregisterAtlas.m:1]: Please change the name to xASL_adm_RegisterAtlas or something, coregistration has the same meaning, and if it differs, coregistration is used for linear/intra-subject registration.

File: WorkInProgress/Administration/xASL_adm_CoregisterAtlas.m [hunk 2]
```diff
@@ -10,9 +10,13 @@
 pathTPMAtlasFile = 'mni_icbm152_gm_tal_nlin_asym_09c.nii';
 pathTPMAtlasFileWM = 'mni_icbm152_wm_tal_nlin_asym_09c.nii';
 pathTPMAtlasFileGMWM = 'mni_icbm152_gmwm_tal_nlin_asym_09c.nii';
+pathColinDir = 'mni_colin27_2008';
```
Comment (HenkMutsaerts) [inline WorkInProgress/Administration/xASL_adm_CoregisterAtlas.m:13]: We don't save these in ExploreASL right? (at least we shouldn't if we don't use them in the pipeline), should we save them in CustomScripts for ease of use?

File: WorkInProgress/Administration/xASL_adm_CoregisterAtlas.m [hunk 3]
```diff
@@ -122,12 +191,38 @@
...
 
 % Create MAT file
-IM = xASL_io_Nifti2Im(fullfile(pathTPM, 'oAAL3v1_1mm.nii'));
-IM = uint8(IM);
-save(fullfile(pathTPM, 'oAAL3v1_1mm.nii.mat'),'IM');
-xASL_adm_GzipNifti(fullfile(pathTPM, 'oAAL3v1_1mm.nii'));
-
 IM = xASL_io_Nifti2Im(fullfile(pathTPM, 'oWMPM_Type_III.nii'));
-IM = uint8(IM);
+IM = uint8(ceil(IM/2.0)); % Make sure it's divided by 2 and rounded to deal with the L-R and merge them to bilateral
```
Comment (HenkMutsaerts) [inline WorkInProgress/Administration/xASL_adm_CoregisterAtlas.m]: This doesn't work for each atlas, most have left and right but also single bilateral regions; so this needs checking per ROI atlas!

**Review by HenkMutsaerts — APPROVED** [review]
Few points for you to check but I don't need to see them :)

File: WorkInProgress/Administration/xASL_adm_CoregisterAtlas.m (hunk 1 above)
Comment (jan-petr) [reply WorkInProgress/Administration/xASL_adm_CoregisterAtlas.m:1]: Yes. Agree. Will do...

File: WorkInProgress/Administration/xASL_adm_CoregisterAtlas.m (hunk 2 above)
Comment (jan-petr) [reply WorkInProgress/Administration/xASL_adm_CoregisterAtlas.m:13]: Haha. No of course not - these are all on my disc in a temp dir. I only save the result to ExploreASL dir.
But it's a good idea to add also the input files to CustomScripts so that this can be re-run easier.

File: WorkInProgress/Administration/xASL_adm_CoregisterAtlas.m (hunk 3 above)
Comment (jan-petr) [reply WorkInProgress/Administration/xASL_adm_CoregisterAtlas.m]: Yes. Fully agree!!! But for these two cases, it works right?

Comment (jan-petr) [reply WorkInProgress/Administration/xASL_adm_CoregisterAtlas.m]: Fix with the correct script.
