### PR TITLE
Closes #577 bug #577 population sessions

### LINKED ISSUE #577: Incorrect volumetric output
Structural volumetric output (GM/WM/CSF_vol etc.) is not outputted into a _stats_ file at all times. If the session number does not start with 1, no output will be given. See below:

image

The printing of the stats files should recognise which session is the first in the subject and output volumetrics accordingly.

### PR DESCRIPTION
**Pull request by HenkMutsaerts**
### Linked issue

Closes #577

### How to test

Required: if not defined in the linked issue, add a simple test description here

### Comments

Optional: add helpful comments for the reviewers here

### CODE REVIEW

**Comment by HenkMutsaerts** [comment]
@MDijsselhof Can you test this in your dataset(s) by rerunning the population module? The first columns in the stats files are created from `participants.tsv`, which is why you should first remove `participants.tsv`. Now `participants.tsv` should be created correctly and the rest should follow.

File: Functions/Administration/xASL_adm_GetPopulationSessions.m [hunk 1]
```diff
@@ -54,13 +50,13 @@
         NewList{iSession,1} = SessionList{iSession}(1,IndexStart:IndexEnd); % create a cell array containings characters of all session numbers present
     end
     
-    UniqueSessions = unique(NewList); % determine unique session numbers
+    SESSIONS = sort(unique(NewList)); % determine unique session numbers
```
Comment (jan-petr) [inline Functions/Administration/xASL_adm_GetPopulationSessions.m]: We have to be very careful about sorting! Because when sorting strings, ASL_12 will come before ASL_2, but we want to sort by the number - so ASL_12 after ASL_2

Comment (jan-petr) [reply Functions/Administration/xASL_adm_GetPopulationSessions.m]: You have to sort as number not as string. Or perhaps this won't matter later in the code, but then the sorting might not be necessary. My point - if you need to sort, then you better do it properly ;)

File: Functions/BIDS/xASL_bids_Add2ParticipantsTSV.m [hunk 2]
```diff
@@ -60,22 +60,32 @@ function xASL_bids_Add2ParticipantsTSV(DataIn, DataName, x, bOverwrite)
...
+    % Sessions found
+    if size(DataIn,2)<3 % A session column should exist
         warning('Session column missing, too few columns, skipping');
         return;
-    else
-        TempSessionNames = unique(DataIn(:,2));
-        if ~max(strcmp(TempSessionNames, 'ASL_1'))
-            warning('First session missing, might go wrong');
+    else % check if the sessions are the same in DataIn and x.SESSIONS
+        TempSessionNames = sort(unique(DataIn(:,2)))';
```
Comment (jan-petr) [inline Functions/BIDS/xASL_bids_Add2ParticipantsTSV.m]: again - careful how you sort.

File: Functions/BIDS/xASL_bids_Add2ParticipantsTSV.m [hunk 3]
```diff
@@ -202,4 +211,60 @@ function xASL_bids_Add2ParticipantsTSV(DataIn, DataName, x, bOverwrite)
...
+    %% Admin
+    if nargin<3 || isempty(bHasHeader)
+        bHasHeader = false;
+    end
+
+    numberColumns = size(MatrixIn,2); % Obtain the size of the matrix (number of data points)
+
+    %% Create the header (if needed)
+    if bHasHeader
+        MatrixOut(1, 1) = MatrixIn(1, 1); % subject header
```
Comment (jan-petr) [inline Functions/BIDS/xASL_bids_Add2ParticipantsTSV.m:241]: careful -  you are using different brackets on each line. It is probably fine as MatrixIn has cells. I'm just asking to double check and you can then resolve without answering ;)

File: Functions/ImageProcessing/xASL_im_SplitImageLabels.m [hunk 4]
```diff
@@ -1,4 +1,4 @@
-function xASL_im_SplitImageLabels(ImagePaths, LabelTable, OutputFolder, bOverwrite, ResampleDir, SubRegExp)
+function xASL_im_SplitImageLabels(ImagePaths, LabelTable, OutputFolder, bOverwrite, ResampleDir, SubRegExp, sessionFolder)
 %xASL_im_SplitImageLabels Extract individual label/regions from image(s)
 %
 % FORMAT: xASL_im_SplitImageLabels(ImagePaths, LabelTable[, OutputFolder, bOverwrite, ResampleDir, SubRegExp])
```
Comment (jan-petr) [inline Functions/ImageProcessing/xASL_im_SplitImageLabels.m]: please add the new variable to this line as well

**Review by jan-petr — CHANGES_REQUESTED** [review]
Some minor formal things to be fixed.

File: Functions/Administration/xASL_adm_GetPopulationSessions.m (hunk 1 above)
Comment (HenkMutsaerts) [reply Functions/Administration/xASL_adm_GetPopulationSessions.m]: Good point. At this time, nobody probably has used >9 sessions, Mathijs could have for NOMARED, would be good to check. I fixed this throughout now.

**Review by jan-petr — APPROVED** [review]
OK.

File: Functions/BIDS/xASL_bids_Add2ParticipantsTSV.m [hunk 5]
```diff
@@ -1,7 +1,7 @@
 function xASL_bids_Add2ParticipantsTSV(DataIn, DataName, x, bOverwrite)
 %xASL_bids_Add2ParticipantsTSV Add data to participants.tsv
 %
-% FORMAT: xASL_bids_Add2ParticipantsTSV(DataIn, DataName, x, bOverwrite)
+% FORMAT: xASL_bids_Add2ParticipantsTSV(DataIn, DataName, x[, bOverwrite])
```
Comment (MDijsselhof) [inline Functions/BIDS/xASL_bids_Add2ParticipantsTSV.m:4]: Should it be like this? With the [ ]?

**Review by MDijsselhof — CHANGES_REQUESTED** [review]
I had one small question

File: Functions/BIDS/xASL_bids_Add2ParticipantsTSV.m (hunk 5 above)
Comment (jan-petr) [reply Functions/BIDS/xASL_bids_Add2ParticipantsTSV.m:4]: Yes. This is correct. Not in the real function declaration. But in the comment, it specifies that the parameters in [ ] are optional. So correct in this case - we do it like this in almost all other functions.

**Review by MDijsselhof — APPROVED** [review]
