### PR TITLE
Fixes #850 xASL_wrp_RealingASL: field checks

### LINKED ISSUE #850: Hadamard or TimeEncoded field check required
### Description

While processing ADNI case 003_S_6264 using develop, I got this error:

```
====================================================================================
Running xASL_module_ASL ...   
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
=== Subject: sub-003S6264_1, Session: ASL_1, Module: xASL_module_ASL_<SESSION>,  24-Sep-2021 10:53:25 ===

Cleaning data to rerun subject sub-003S6264_1
nRemoving lock folders:100%
Restoring backupped _ORI (original) files:   
Deleting native space CAT12 temporary folders:   
Deleting native space files for module 2:100%
Deleting all standard space files for module 2

Cleaning up x-struct:100%
Cleaning up QC_Collection json:100%
3D_GRASE sequence detected
No TopUp scans available, skipping...
Automatic alignment with center of mass: skipping, was too close
x.modules.asl.SpikeRemovalThreshold was not defined yet, default setting = 0.01 used
SPM motion estimation
ERROR: ASL module terminated for subject 1: sub-003S6264_1

ans =

    'Reference to non-existent field 'HadamardType'.
     
     Error in xASL_wrp_RealignASL (line 125)
     if nFrames>2 && bSubtraction && (numel(unique(x.Q.Initial_PLD))>1 
     || numel(unique(x.EchoTime))>1 || x.modules.asl.HadamardType~=0) %multiPLD or multiTE or Hadamard
     
     Error in xASL_module_ASL (line 306)
                 xASL_wrp_RealignASL(x);
```

I've been rerunning it using main, to check if the last release is fine. There the bug does not occur.

### Requirements

Optional: add bug requirements here

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here

### PR DESCRIPTION
**Pull request by MichaelStritt**
### Linked issue

Check out #850

### How to test

Develop without this fix should basically crash for almost every non-Hadamard dataset. Just do some basic testing of the ASL module using the test dataset. Alternatively you can always run the 10 test datasets, but that's probably overkill for such a small change.

### Comments

@BeatrizPadrela: Okay, same here as with https://github.com/ExploreASL/ExploreASL/pull/849, please check if everything works correctly. If yes, then approve & move it to @jan-petr's bucket.

### CODE REVIEW

**Comment by MichaelStritt** [comment]
### Unit testing

There still seems to be a small bug in there.

```
====================================== TEST RESULTS ======================================

                        name                           unit           tests        passed
    ____________________________________________    __________    _____________    ______

    'xASL_adm_CatchNumbersFromString'               'function'    [1x3  struct]    true  
    'xASL_adm_CheckFileCount'                       'function'    [1x2  struct]    true  
    'xASL_adm_CompareLists'                         'function'    [1x2  struct]    true  
    'xASL_adm_CorrectName'                          'function'    [1x3  struct]    true  
    'xASL_adm_DeleteFileList'                       'function'    [1x2  struct]    true  
    'xASL_adm_OrderFields'                          'function'    [1x1  struct]    true  
    'xASL_bids_BIDS2Legacy'                         'function'    [1x2  struct]    true  
    'xASL_bids_CheckDatasetDescription'             'function'    [1x2  struct]    true  
    'xASL_bids_CompareStructures'                   'function'    [1x1  struct]    false 
    'xASL_bids_Config'                              'function'    [1x1  struct]    true  
    'xASL_bids_CreateDatasetDescriptionTemplate'    'function'    [1x2  struct]    true  
    'xASL_bids_JsonCheck'                           'function'    [1x3  struct]    true  
    'xASL_bids_VendorFieldCheck'                    'function'    [1x1  struct]    true  
    'xASL_io_ExportVTK'                             'function'    [1x5  struct]    true  
    'xASL_io_Nifti2Im'                              'function'    [1x1  struct]    true  
    'xASL_stat_PSNR'                                'function'    [1x2  struct]    true  
    'xASL_stat_QuantileNan'                         'function'    [1x1  struct]    true  
    'xASL_stat_StdNan'                              'function'    [1x3  struct]    true  
    'xASL_str2num'                                  'function'    [1x3  struct]    true  
    'xASL_test_GetLogContent'                       'function'    [1x2  struct]    true  
    'xASL_tsvRead'                                  'function'    [1x2  struct]    true  
    'xASL_tsvWrite'                                 'function'    [1x2  struct]    true  
    'xASL_ExploreASL_Master'                        'master'      [1x11 struct]    false 
    'xASL_module_ASL'                               'module'      [1x1  struct]    true  
    'xASL_module_Population'                        'module'      [1x1  struct]    true  
    'xASL_module_Structural'                        'module'      [1x1  struct]    true  

==========================================================================================
```

**Comment by MichaelStritt** [comment]
@jan-petr & @BeatrizPadrela: all bugs fixed, unit tests pass now 👍 weird that you didn't see those bugs during testing of the multi-TE feature

**Review by BeatrizPadrela — APPROVED** [review]
Replaced HadamardType for TimeEncodedMatrixType, which is the variable name we use. (#858 branch was created to correct this, but maybe we can delete it because it's corrected here now)

File: Functions/xASL_bids_CompareStructures.m [hunk 1]
```diff
@@ -136,15 +136,19 @@
 function reportTable = xASL_bids_CompareStructures_AddEntriesToTable(reportTable,results,datasetA,datasetB)
 
     % Go through missing folders
-    if size(results.(datasetA).missingFolders,1)>0 && ~isempty(results.(datasetA).missingFolders{1})
+    if size(results.(datasetA).missingFolders,1)>0 && ...
```
Comment (jan-petr) [inline Functions/xASL_bids_CompareStructures.m:139]: Not really wrong, but would it not be easier to use numel rather than size 1 and size 2?
This applies also to lines 139-169. Including the for statements etc.

File: Modules/SubModule_ASL/xASL_wrp_RealignASL.m [hunk 2]
```diff
@@ -122,7 +122,11 @@ function xASL_wrp_RealignASL(x,bSubtraction)
 %         save('rp_ASL4D.txt','MotionAllTEs','-ascii')
 %     end  
     
-if nFrames>2 && bSubtraction && (numel(unique(x.Q.Initial_PLD))>1 || numel(unique(x.EchoTime))>1 || x.modules.asl.HadamardType~=0) %multiPLD or multiTE or Hadamard
+if nFrames>2 && bSubtraction && ...
```
Comment (jan-petr) [inline Modules/SubModule_ASL/xASL_wrp_RealignASL.m:125]: Not an entirely correct statement. it is multi-PLD OR multi-TE. So if echo-time is missing, you still want to check for multi-PLD...

We want this (but check if the brackets are ok;): 
nFrames>2 && bSubtraction && ( (isfield(x.Q,'Initial_PLD') && (numel(unique(x.Q.Initial_PLD))>1) || (isfield(x,'EchoTime') && numel(unique(x.EchoTime))>1) || (isfield(x.modules.asl,'TimeEncodedMatrixType') && x.modules.asl.TimeEncodedMatrixType~=0)) )

**Review by jan-petr — CHANGES_REQUESTED** [review]
Looks good - but 1 thing can be optimized and one is not entirely correct.

File: Modules/SubModule_ASL/xASL_wrp_RealignASL.m (hunk 2 above)
Comment (jan-petr) [reply Modules/SubModule_ASL/xASL_wrp_RealignASL.m:125]: Also - #859 seems to be solving a similar issue. Please apply the changes of #859 in this issue and mark #859 as duplicate.

Comment (MichaelStritt) [reply Modules/SubModule_ASL/xASL_wrp_RealignASL.m:125]: I thought Mathijs would add the multi-PLD check later on. This was just supposed to be a bugfix for the missing field checks, since the pipeline crashes without it.

File: Functions/xASL_bids_CompareStructures.m (hunk 1 above)
Comment (MichaelStritt) [reply Functions/xASL_bids_CompareStructures.m:139]: True, forgot that numel is easier here.

File: Modules/SubModule_ASL/xASL_wrp_RealignASL.m (hunk 2 above)
Comment (MichaelStritt) [reply Modules/SubModule_ASL/xASL_wrp_RealignASL.m:125]: > 
> 
> Also - #859 seems to be solving a similar issue. Please apply the changes of #859 in this issue and mark #859 as duplicate.

@BeatrizPadrela already did this.

File: Functions/xASL_bids_CompareStructures.m (hunk 1 above)
Comment (MichaelStritt) [reply Functions/xASL_bids_CompareStructures.m]: I'm not 100% sure about the for loops, but for the rest it's done cd90e1b and tested...

```
UnitTest = xASL_ut_function_xASL_bids_CompareStructures(TestRepository);

>> UnitTest

UnitTest = 

  struct with fields:

     tests: [1×4 struct]
    passed: 1
```

**Comment by BeatrizPadrela** [comment]
I processed one twin fomr baseline, and the structural + ASL modules are fine. I was having issues with ASL module, but it's all fine now

image

image

**Review by BeatrizPadrela — APPROVED** [review]

**Comment by BeatrizPadrela** [comment]
Unit Testing:

image

File: Functions/xASL_bids_CompareStructures.m [hunk 3]
```diff
@@ -136,15 +136,17 @@
 function reportTable = xASL_bids_CompareStructures_AddEntriesToTable(reportTable,results,datasetA,datasetB)
 
     % Go through missing folders
-    if size(results.(datasetA).missingFolders,1)>0 && ~isempty(results.(datasetA).missingFolders{1})
+    if numel(results.(datasetA).missingFolders)>0 && ...
+            ~isempty(results.(datasetA).missingFolders{1})
         for iElement=1:size(results.(datasetA).missingFolders,1)
```
Comment (jan-petr) [inline Functions/xASL_bids_CompareStructures.m:141]: Numel in the condition, but size,1 here... That might be a problem.

File: Functions/xASL_bids_CompareStructures.m [hunk 4]
```diff
@@ -136,15 +136,17 @@
...
             dataset = cellstr(datasetA);
             name = cellstr('Missing folder');
             message = cellstr(results.(datasetA).missingFolders{iElement,1});
```
Comment (jan-petr) [inline Functions/xASL_bids_CompareStructures.m:144]: and here - why, iElement,1? A potential problem

File: Functions/xASL_bids_CompareStructures.m [hunk 5]
```diff
@@ -136,15 +136,17 @@
...
             reportTable = xASL_bids_CompareStructures_AddTableRow(reportTable,dataset,name,message);
         end
     end
-    if size(results.(datasetB).missingFolders,1)>0 && ~isempty(results.(datasetB).missingFolders{1})
+    if numel(results.(datasetB).missingFolders)>0 && ...
```
Comment (jan-petr) [inline Functions/xASL_bids_CompareStructures.m:148]: And the same here - it was good replacing size,1 and size,2 with numel, but then this needs to be shadowed on the other lines of code.

File: Modules/SubModule_ASL/xASL_wrp_RealignASL.m [hunk 6]
```diff
@@ -120,9 +120,16 @@ function xASL_wrp_RealignASL(x,bSubtraction)
...
-if nFrames>2 && bSubtraction && (numel(unique(x.Q.Initial_PLD))>1 || numel(unique(x.EchoTime))>1 || x.modules.asl.HadamardType~=0) %multiPLD or multiTE or Hadamard
+%     end
+
+% Define conditions for motion correction in multi-PLD, multi-TE and Hadamard subjects
+conditionMultiPLD = isfield(x.Q,'Initial_PLD') && (numel(unique(x.Q.Initial_PLD))>1);
+conditionMultiTE = isfield(x,'EchoTime') && (numel(unique(x.EchoTime))>1);
+conditionHadamard = isfield(x.modules.asl,'TimeEncodedMatrixType') && (x.modules.asl.TimeEncodedMatrixType~=0);
+
+% Run motion correction for corresponding case
+if nFrames>2 && bSubtraction && (conditionMultiPLD  ||  conditionMultiTE  || conditionHadamard)
```
Comment (jan-petr) [inline Modules/SubModule_ASL/xASL_wrp_RealignASL.m:131]: Super - looks great now...

**Review by jan-petr — CHANGES_REQUESTED** [review]
Small request with the numel - otherwise looks good.

File: Functions/xASL_bids_CompareStructures.m (hunk 3 above)
Comment (MichaelStritt) [reply Functions/xASL_bids_CompareStructures.m:141]: Ah sure, I can change that, too. Normally the list is a column vector here, so until now it always worked, but it's easy to change that.

Comment (MichaelStritt) [reply Functions/xASL_bids_CompareStructures.m]: Fixed here: 4d00c8f 👍 
Tested here...

```
UnitTest = xASL_ut_function_xASL_bids_CompareStructures(TestRepository);
>> UnitTest

UnitTest = 

  struct with fields:

     tests: [1×4 struct]
    passed: 1
```

... 👍

File: Functions/xASL_bids_CompareStructures.m (hunk 4 above)
Comment (MichaelStritt) [reply Functions/xASL_bids_CompareStructures.m]: Fixed here: 4d00c8f 👍

File: Functions/xASL_bids_CompareStructures.m (hunk 5 above)
Comment (MichaelStritt) [reply Functions/xASL_bids_CompareStructures.m:148]: Fixed here: 4d00c8f 👍

**Review by jan-petr — APPROVED** [review]
Looks very good now. Though I hope I didn't make it unstable with the last optimization tips ;)

**Comment by MichaelStritt** [comment]
> 
> 
> Looks very good now. Though I hope I didn't make it unstable with the last optimization tips ;)

Don't worry 😆 The unit test has four different scenarios and all of them worked. In addition it's only the comparison script, which isn't used in the processing pipeline at all 👍
