### PR TITLE
Optimize #1311 matlab json

### LINKED ISSUE #1311: Use Matlab internal json-encode functions instead of SPM routines
### Description
Stop using `SPM_JSONREAD` as this tends to crash with certain illegal JSON formats. We'll switch to Matlab I/O and `JSONDECODE` and `JSONENCODE`

>> fileID = fopen('xxx.json','r');
txt = fscanf(fileID,"%s");
j = jsondecode(txt);
fclose(fileID);

I've tested that both functions run the same time, so time-wise we won't loose anything.

HENK: won't we have as side-effect that if something crashes in between `fopen` & `fclose`, this will be pain? The file would be locked, so you cannot easily remove e.g., the derivatives folder and rerun. You don't seem to have this issue with the current `spm_jsonread` MEX? But that is perhaps a small price to pay.

Or perhaps we can immediately close the fileID after reading it; same for writing.

JAN: We of course close it immediately, but the issue is not in doing it fast, but about catching potential issues. So all that's inbetween opening and closing of a file is in a try-catch and if something fails, we first close the file and then report an error. So there isn't really a possibility of keeping a file open. Besides - this is mainly a Windows problem.

>> fileID = fopen('xxx.json','r');
txt = fscanf(fileID,"%s");
fclose(fileID);
j = jsondecode(txt);

### Tasks

- [x] Write a new function `xASL_io_jsonread`
- [x] Write a new function `xASL_io_jsonwrite`
- [x] Replace all spm_readjson
- [x] Replace all spm_writejson
- [x] Write a UT function with one correct and one incorrect JSON

### How to test

- [x] Henk checks code
- [x] Unit testing with this new test runs through
- [x] Check flavors in develop
- [x] Flavors are still running fine in this branch?
- [x] Issues with the last flavor - Siemens_PCASL_3DGRASE_VB17A_TopUp_2
- [x] Should we remove this from the last lines of `xASL_mex_compileAll` about `spm_jsonread`. JAN: This is already removed!

### Release notes

Use Matlab functions instead of SPM for I/O of JSON files.

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

Closes #1311

### CODE REVIEW

File: Functions/InputOutput/xASL_io_ReadJson.m [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+%
+% EXAMPLE: json = xASL_io_ReadJson('/tmp/test.json');
+% __________________________________
+% Copyright (C) 2015-2023 ExploreASL
+
+
+%% ------------------------------------------------------------------------------------------------
+%% 0.   Administration
+if nargin < 1 || isempty(pathJSON)
+	error('Requires the path to the JSON file.');
```
Comment (HenkMutsaerts) [inline Functions/InputOutput/xASL_io_ReadJson.m]: Who requires the path? :) You meant the path is missing right.
"I need A" is not an error explanation. "A is missing" is an explanation of the error.

File: Functions/InputOutput/xASL_io_ReadJson.m [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+end
+
+if ~xASL_exist(pathJSON,'file')
+	error(['Cannot find the JSON file: ' pathJSON]);
+end
+
+%% 1. Read the JSON file
+fileID = fopen(pathJSON, 'r');
+txt = fscanf(fileID, '%s');
+
```
Comment (HenkMutsaerts) [inline Functions/InputOutput/xASL_io_ReadJson.m:44]: You can close before decoding, so close immediately after `fscanf` to avoid issues with open files in memory

File: Functions/InputOutput/xASL_io_ReadJson.m [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+%% 2. Decode the text content
+json = jsondecode(txt);
+
+% Close the file and returns
```
Comment (HenkMutsaerts) [inline Functions/InputOutput/xASL_io_ReadJson.m]: "and returns" is not understandable to non-programmers. You meant "ends the function"? But that is not what `fclose` does right

File: Functions/InputOutput/xASL_io_WriteJson.m [hunk 4]
```diff
@@ -0,0 +1,50 @@
+function xASL_io_WriteJson(pathJSON, json, bOverwrite)
+%xASL_io_WriteJson Writes the content of a json structure to a JSON file
+%
+% FORMAT: xASL_io_WriteJson(pathJSON, json[, bOverwrite])
+%
+% INPUT:
+%   pathJSON     - path to the JSON file (REQUIRED)
+%   json         - Matlab structure to be written as JSON (REQUIRED)
```
Comment (HenkMutsaerts) [inline Functions/InputOutput/xASL_io_WriteJson.m]: "string"

File: Functions/InputOutput/xASL_io_WriteJson.m [hunk 5]
```diff
@@ -0,0 +1,50 @@
+function xASL_io_WriteJson(pathJSON, json, bOverwrite)
+%xASL_io_WriteJson Writes the content of a json structure to a JSON file
+%
+% FORMAT: xASL_io_WriteJson(pathJSON, json[, bOverwrite])
+%
+% INPUT:
+%   pathJSON     - path to the JSON file (REQUIRED)
```
Comment (HenkMutsaerts) [inline Functions/InputOutput/xASL_io_WriteJson.m]: "string"

File: Functions/InputOutput/xASL_io_WriteJson.m [hunk 6]
```diff
@@ -0,0 +1,50 @@
...
+%   json         - Matlab structure to be written as JSON (REQUIRED)
+%   bOverwrite   - boolean that is true if an existing file should be overwritten (OPTIONAL, DEFAULT = TRUE)
+%
+% -----------------------------------------------------------------------------------------------------------------------------------------------------
+% DESCRIPTION: This function writes a Matlab structure into a JSON file located at the given path encoding it using the Matlab routine
```
Comment (HenkMutsaerts) [inline Functions/InputOutput/xASL_io_WriteJson.m]: function, not routine

**Comment by jan-petr** [comment]
COMPARISON TABLE:]
                        flavor                               dataset                      name                                                     message                                      
    _______________________________________________    ____________________    __________________________    ___________________________________________________________________________________

     {'Siemens_PCASL_3DGRASE_VB17A_TopUp_2'        }    {'rawdata'         }    {'Missing file'          }    {'/sub-SUB002/fmap/sub-SUB002_dir-pa_m0scan.json'                                 }
    {'Siemens_PCASL_3DGRASE_VB17A_TopUp_2'        }    {'rawdata'         }    {'Missing file'          }    {'/sub-SUB002/fmap/sub-SUB002_dir-pa_m0scan.nii.gz'                               }
    {'Siemens_PCASL_3DGRASE_VB17A_TopUp_2'        }    {'rawdata'         }    {'Missing file'          }    {'/sub-SUB002/perf/sub-SUB002_asl.json'                                           }
    {'Siemens_PCASL_3DGRASE_VB17A_TopUp_2'        }    {'rawdata'         }    {'Missing file'          }    {'/sub-SUB002/perf/sub-SUB002_asl.nii.gz'                                         }
    {'Siemens_PCASL_3DGRASE_VB17A_TopUp_2'        }    {'rawdata'         }    {'Missing file'          }    {'/sub-SUB002/perf/sub-SUB002_aslcontext.tsv'                                     }
    {'Siemens_PCASL_3DGRASE_VB17A_TopUp_2'        }    {'rawdata'         }    {'Missing file'          }    {'/sub-SUB002/perf/sub-SUB002_dir-ap_m0scan.json'                                 }
    {'Siemens_PCASL_3DGRASE_VB17A_TopUp_2'        }    {'rawdata'         }    {'Missing file'          }    {'/sub-SUB002/perf/sub-SUB002_dir-ap_m0scan.nii.gz'                               }

**Review by HenkMutsaerts — APPROVED** [review]
Quite a large change, and nice that you wrote unit tests as well. I would really test this one thoroughly before merging with develop.

**Comment by jan-petr** [comment]
> Quite a large change, and nice that you wrote unit tests as well. I would really test this one thoroughly before merging with develop.

Of course :) And I found quite some bugs. But all is fixed now. Our complete set of tests runs fine, except for one dataset in Flavors - this still has to be fixed.

File: Functions/InputOutput/xASL_io_ReadJson.m (hunk 1 above)
Comment (jan-petr) [reply Functions/InputOutput/xASL_io_ReadJson.m]: Agree. Fixed.

File: Functions/InputOutput/xASL_io_ReadJson.m (hunk 2 above)
Comment (jan-petr) [reply Functions/InputOutput/xASL_io_ReadJson.m:44]: Immediately doesn't really help. It has to be in a try-catch loop to catch issues with crashing while reading. But the decoding can then be moved for later.

File: Functions/InputOutput/xASL_io_ReadJson.m (hunk 3 above)
Comment (jan-petr) [reply Functions/InputOutput/xASL_io_ReadJson.m]: Fixed comment.

File: Functions/InputOutput/xASL_io_WriteJson.m (hunk 4 above)
Comment (jan-petr) [reply Functions/InputOutput/xASL_io_WriteJson.m]: fixed. all types added.

File: Functions/InputOutput/xASL_io_WriteJson.m (hunk 5 above)
Comment (jan-petr) [reply Functions/InputOutput/xASL_io_WriteJson.m]: fixed here as well.

File: Functions/InputOutput/xASL_io_WriteJson.m (hunk 6 above)
Comment (jan-petr) [reply Functions/InputOutput/xASL_io_WriteJson.m]: older term and mostly equivalent in this context. But I'm fine with saying function ;)
