### PR TITLE
Fixes #739 Introduce function to fix basic fields within JSON files

### LINKED ISSUE #739: Get info from the studyPar if the DICOMs are anonymized
### Description

If we have DICOMs that are all anonymized (including the Manufacturer name for example - yes, this happens with the twins data), we can write it in the studyPar so that the import module can recognize it.

### Requirements

Change the import functions that recognize the Manufacturer from the DICOMs and add an option to read it from the studyPar

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here

### PR DESCRIPTION
**Pull request by MichaelStritt**
### Linked issue

Check out #739

### How to test

Run import of twins datasets with and without Manufacturer in `studyPar.json` (hopefully it works both times).

### Comments

I introduced `xASL_bids_BIDSifyFixBasicFields` and improved the logging within the import master script. All changes are only import related and should therefore not affect issue #717 that much. Would be helpful to know if that's the right place for some of the functions or if we should move that functionality to another part @jan-petr.

### CODE REVIEW

**Comment by MichaelStritt** [comment]
### Beatriz test

https://github.com/ExploreASL/ExploreASL/issues/739#issuecomment-887006396

**Review by BeatrizPadrela — APPROVED** [review]
works with and without "Manufacturer" field in the Studypar!

**Comment by MichaelStritt** [comment]
Maybe the user feedback is a bit more humanly readable now 9ded2d4: image

**Comment by MichaelStritt** [comment]
Maybe the user feedback is a bit more humanly readable now f684169 & 9ded2d4 & 267fbf6: 
image

File: Functions/xASL_bids_BIDSifyFixBasicFields.m [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+        otherwise
+            fieldList = {'Manufacturer'};
+    end
+    
+    % Iterate over fields
+    for iField = 1:numel(fieldList)
+        if isfield(studyPar,fieldList{iField}) && ~isfield(jsonIn,fieldList{iField})
+            jsonIn.(fieldList{iField}) = studyPar.(fieldList{iField});
+        end
+    end
```
Comment (MichaelStritt) [inline Functions/xASL_bids_BIDSifyFixBasicFields.m:56]: @jan-petr: I forgot to say in the dev meeting that this can also help if the TotalAcquiredPairs are in the studyPar already, but not in the metadata. So it's really not only about the Manufacturer. I'm open for suggestions on improvements though. Would be cool if you could check the general behavior though.

**Comment by MichaelStritt** [comment]
@jan-petr: I was thinking about the ASPIRE task (#734) and I was working on that exact script anyway, so I added a suggestion in 79d67d7, but we can change it if you don't like it.

File: Functions/xASL_bids_BIDSifyFixBasicFields.m (hunk 1 above)
Comment (jan-petr) [reply Functions/xASL_bids_BIDSifyFixBasicFields.m:56]: Yes - I understood that at the meeting already. At first was afraid that this will create a mess. But I have checked all the code and it won't create conflicts - so good to have everything here...

Comment (jan-petr) [reply Functions/xASL_bids_BIDSifyFixBasicFields.m:56]: It was mainly the function name I didn't like ;) 'Fix' sounds very general - all functions 'fix' something. Besides, this is really more of a 'merge'. what about xASL_bids_MergeStudyPar?

File: Functions/xASL_bids_BIDSifyFixBasicFields.m [hunk 2]
```diff
@@ -0,0 +1,90 @@
+function jsonIn = xASL_bids_BIDSifyFixBasicFields(jsonIn,studyPar,bidsModality)
+%xASL_bids_BIDSifyFixBasicFields Check if required fields exist in studyPar but not in jsonIn 
+% or if we can find them out in other ways
+%
+% FORMAT: jsonIn = xASL_bids_BIDSifyFixBasicFields(jsonIn,studyPar);
```
Comment (jan-petr) [inline Functions/xASL_bids_BIDSifyFixBasicFields.m:5]: modality missing

File: Functions/xASL_bids_BIDSifyFixBasicFields.m [hunk 3]
```diff
@@ -0,0 +1,90 @@
...
+%
+% INPUT:
+%   jsonIn       - JSON with the input fields - from DICOMs (REQUIRED)
+%   studyPar     - Manually defined parameters (REQUIRED)
+%   bidsModality - Modality (CHAR ARRAY, OPTIONAL, DEFAULT = 'asl')
+%
+% OUTPUT: 
+%   jsonIn    - ordered and checked JSON structure
```
Comment (jan-petr) [inline Functions/xASL_bids_BIDSifyFixBasicFields.m:13]: it's not ordered and checked - It's really only merged

**Review by jan-petr — CHANGES_REQUESTED** [review]
Gave it another thought and I think that we should keep it the way it is - except for fixing a few small bugs ;)

File: Functions/xASL_bids_BIDSifyASLJSON.m [hunk 4]
```diff
@@ -296,7 +299,7 @@
 	end
 	
 	% If the length of SliceTiming fits to the number of slices, do nothing
-	if length(jsonOut.SliceTiming) ~= dimASL(3)
+	if isfield(jsonOut,'SliceTiming') && isfield(jsonOut,'SiemensSliceTime') && (length(jsonOut.SliceTiming) ~= dimASL(3))
```
[the remark this answers is not in the document]
Comment (MichaelStritt) [reply Functions/xASL_bids_BIDSifyASLJSON.m]: Oh, that's weird. Don't know how that got there, must have been a copy-paste error. Fixed in 16b1c3b.

File: Functions/xASL_bids_BIDSifyFixBasicFields.m (hunk 1 above)
Comment (MichaelStritt) [reply Functions/xASL_bids_BIDSifyFixBasicFields.m]: Sounds good 4f6c55a 😄

File: Functions/xASL_bids_JsonCheck.m [hunk 5]
```diff
@@ -139,12 +144,13 @@
         end
     end
     if ~isempty(strReport)
-        fprintf('%s\n\n',['Missing required M0 fields: ' strReport]);
+        fprintf('Missing required M0 fields:           %s\n',strReport);
```
[the remark this answers is not in the document]
Comment (MichaelStritt) [reply Functions/xASL_bids_JsonCheck.m]: Easy 067438e 👍

File: Functions/xASL_bids_BIDSifyFixBasicFields.m (hunk 2 above)
Comment (MichaelStritt) [reply Functions/xASL_bids_BIDSifyFixBasicFields.m]: 9941e81  👍

File: Functions/xASL_bids_BIDSifyFixBasicFields.m (hunk 3 above)
Comment (MichaelStritt) [reply Functions/xASL_bids_BIDSifyFixBasicFields.m]: Ah sorry, that was copy-pasted from another header c0d6cf4

**Review by jan-petr — APPROVED** [review]
All good now.
