### PR TITLE
#1678 quant_BSupCalculation Fix rounding for visualization

### LINKED ISSUE #1678: Too Precise BSup Timings Results in indexing error & crash
### Description

Tested in v1.11.0 on `main`.

Refer to ~line 129 in `xASL_quant_BSupCalculator.m`

```matlab
    % Repeat the same in a 1ms interval for a graphical output
    if ~isempty(PathGraph)
        % First invert the signal by the BSuppulse
        SignalPercentageVector(BackgroundSuppressionPulseTime(iBSup)) = -SignalPercentageVector(BackgroundSuppressionPulseTime(iBSup));
```

If the background suppressing timings are too precise,  `BackgroundSuppressionPulseTime(iBSup)` it will result in a float which can't be used to index `SignalPercentageVector`. 

```
ERROR: ASL module terminated for subject 11: sub-GRN263V11_1

ans =

    'Array indices must be positive integers or logical values.
```

### Tasks

- [x] Implement rounding safety in function `xASL_quant_BSupCalculator.m`

### Release notes

Fixed a bug in visualization with floating points BSup timings.

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

Close #1678

### CODE REVIEW

**Comment by MauricePasternak** [comment]
I'm unable to test this issue since it doesn't even arrive at the necessary breakpoint. An earlier error occurs in `xASL_im_ASLSubtractionAveraging.m` at this section:

```matlab
    % After averaging across PLDs, we'll obtain these unique PLDs+LD combinations
    % indexAverage_PLD_LabDur lists for each original position to where it should be averaged
	if isempty(x.Q.LabelingDuration)
		[~, ~, iUnique_TE_PLD_LabDur_PWI4D] = unique([x.Q.EchoTime_PWI4D(:), x.Q.InitialPLD_PWI4D(:)], 'stable', 'rows');
	else
		[~, ~, iUnique_TE_PLD_LabDur_PWI4D] = unique([x.Q.EchoTime_PWI4D(:), x.Q.InitialPLD_PWI4D(:), x.Q.LabelingDuration_PWI4D(:)], 'stable', 'rows');
	end
```

```
Error using horzcat
Dimensions of arrays being concatenated are not consistent.
```

`x.Q.LabelingDuration_PWI4D(:)` is a scalar. This issue does not occur on `main`. I've attached a workplace snapshot below.

[1678_quant_BSupCalc_horzcat_subissue.zip](https://github.com/ExploreASL/ExploreASL/files/15097815/1678_quant_BSupCalc_horzcat_subissue.zip)

**Comment by jan-petr** [comment]
@MauricePasternak We now save PLD, TE, LabelingDuration vector in a JSON along with all temporary PWI files. It seems that an incorrect length of LabelingDuration was saved (a scalar instead of a vector as long as there are ASL volumes).

Most likely explanation is that you ran part of the ASL module on version 1.11.0.
Try removing locks for ASL module and re-run the entire ASL module again.

File: Functions/Quantification/xASL_quant_BSupCalculation.m [hunk 1]
```diff
@@ -98,14 +98,15 @@
...
 if ~isempty(PathGraph)
+	% This part is used for visualization only and not for calculation the signal reduction
     % Preallocate (sum is required if multiPLD and therefore multiple ReadoutTime is present)
 	SignalPercentageVector = zeros(round(ReadoutTime + max(SliceTime)), 1);
 	
 	if PresaturationTime
-		SignalPercentageVector(1:PresaturationTime,1) = 1;
-		SignalPercentageVector(PresaturationTime+1:BackgroundSuppressionPulseTime(1),1) = 1 - (1 - 0)*exp(-(1:(BackgroundSuppressionPulseTime(1)-PresaturationTime))/T1Time);
+		SignalPercentageVector(1:round(PresaturationTime), 1) = 1;
+		SignalPercentageVector(round(PresaturationTime+1):round(BackgroundSuppressionPulseTime(1)), 1) = 1 - (1 - 0)*exp(-(1:round(BackgroundSuppressionPulseTime(1)-PresaturationTime))/T1Time);
```
Comment (MauricePasternak) [inline Functions/Quantification/xASL_quant_BSupCalculation.m:107]: These dimensions are different. Left side is N rows x 1 column, right side is 1 row x N columns.

**Review by MauricePasternak — CHANGES_REQUESTED** [review]

**Review by MauricePasternak — APPROVED** [review]
