### PR TITLE
#1702 Minor fix

### LINKED ISSUE #1702: Minor issues in import and processing
### Description

Fix these small bugs in import and processing of the following

### Tasks

- [x] Processing of Philips_PCASL_2DEPI_3.2.2.0_LookLocker_1 - line 366 of xASL_quant_FSL
- [x] Philips_PCASL_2DEPI_5.1.7.2_LookLocker_1 - line 366 of xASL_quant_FSL
- [x] GE_PCASL_3Dspiral_DV25.0_ADNI3_027_S_5079_1 - import flavor
- [x] Philips_PASL_2DEPI_5.4.1.0_ADNI3_006_S_6681_1 - import flavor
- [x] Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession - import flavor
- [x] Siemens_PCASL_3DGRASE_XA31_multiPLD_2 - import flavor
- [x] Siemens_PASL_2DEPI_VE12U_7T - import flavor
- [x] Siemens_PCASL_multiSequence_VE11C_2 - import flavor
- [x] tokenVisitAliases defined as only empty in sourcestructure.json are ignored.

### Release notes

Nothing. Report with #997

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

Close #1702

### CODE REVIEW

File: Modules/Module_Import/Import/xASL_imp_Initialize.m [hunk 1]
```diff
@@ -115,7 +115,12 @@
     end
 
     if ~isfield(imPar, 'tokenVisitAliases')
+		% tokenVisitAliases are not defined at all
         imPar.tokenVisitAliases = [];
+	elseif sum(~cellfun(@isempty, imPar.tokenVisitAliases)) == 0
+		% tokenVisitAliases are defined as all empty strings
+		imPar.tokenVisitAliases = [];
+		warning('All empty TokenVisitAliases are provided in sourcestructure.json. Please remove this field.')
```
Comment (HenkMutsaerts) [inline Modules/Module_Import/Import/xASL_imp_Initialize.m]: This is not a clear warning. Do you mean that the user should provide empty TokenVisitAliases in sourceStructure.json? And at the same time remove this field from sourceStructure.json?

(BTW sourceStructure not sourcestructure)

**Review by HenkMutsaerts — APPROVED** [review]
I approved it, though note that there is one unclear warning (if it is not clear to me then it will definitely not be clear to the user ;)

File: Modules/Module_Import/Import/xASL_imp_Initialize.m (hunk 1 above)
Comment (jan-petr) [reply Modules/Module_Import/Import/xASL_imp_Initialize.m]: Done
