### PR TITLE
Bug #1921 debbie import

### LINKED ISSUE #1921: Import issues with DEBBIE
### Description

Several issues arised when importing DEBBIE and MY2P.

### Tasks

- [x] Incohorent TE times were imported from Phoenix.
- [x] Issues with PE reversed.
- [x] My2P flavors
- [x] Fix documentation with better link to Runtime
- [x] Fix documentation with better description of PE-Rev
- [x] Flavors tested

### Release notes

Bug fix with Phoenix protocol and Reversed PE M0.

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

Close #1921

### CODE REVIEW

File: Modules/Module_Import/NII2BIDS/xASL_bids_MergeNifti.m [hunk 1]
```diff
@@ -58,10 +58,10 @@
 end
 
 if nargin < 2 || isempty(seqType)
-	error('Files type need to be provided as M0 or ASL');
+	error('Files type need to be provided as M0, M0PERev or ASL');
```
Comment (HenkMutsaerts) [inline Modules/Module_Import/NII2BIDS/xASL_bids_MergeNifti.m:62]: Are you sure? In rawdata, it is called M0_dir***, in derivatives/ExploreASL, it is called M0_PERev.nii; you're sure that you're not forgetting the underscore?

Same throughout the other locations

**Review by HenkMutsaerts — CHANGES_REQUESTED** [review]
Underscore missing in M0_PERev (legacy name)?

**Review by HenkMutsaerts — APPROVED** [review]
I added the comments in my last commit
