### PR TITLE
#1418 xASL_quant_M0: Do not save BSup correction without JAVAVM

### LINKED ISSUE #1418: Bsup correction fails under -nojvm
### Description

When running the B-sup correction for M0 quantification in matlab with -nojvm option it crashes as it tries to display a figure.

`    'Error using figure
     This functionality is not supported under the -nojvm startup option.
     
     Error in xASL_quant_M0>xASL_quant_RevertBsupFxControl (line 333)
         FigureHandle = figure('visible','off');
     
     Error in xASL_quant_M0 (line 83)
         [M0IM, x] = xASL_quant_RevertBsupFxControl(M0IM, x);
`
### Release notes

Deactivate Bsup correction figure saving when JAVAVM is turned off.

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

Close #1418

### CODE REVIEW

File: Functions/Quantification/xASL_quant_M0.m [hunk 1]
```diff
@@ -364,31 +361,40 @@
...
+		xlabel('Slice (integer)');
+		% After correction
+		subplot(2, 2, 4);
+		plot(1:size(M0IM,3), SignalAfterCorrection,'r');
+		title('After correction');
+		ylabel('Pseudo-M0 (a.u.)');
+		xlabel('Slice (integer)');
+
+		% Save and close the figure
+		SavePath = fullfile(x.D.M0CheckDir, 'RevertBsupFxControl.jpg');
```
Comment (HenkMutsaerts) [inline Functions/Quantification/xASL_quant_M0.m]: Actually, this is probably a bug somebody introduced before (not me ;)

This saves a single jpg that will be overwritten for each ASL subject/session right?
So it should probably be [x.SUBJECT '_' x.SESSION 'RevertBsupFxControl.jpg' ?
Or don't you want to check this for each subject (then still this will only show for the last subject/session)?

**Review by HenkMutsaerts — CHANGES_REQUESTED** [review]
Minor comment and minor fix in my last comment

File: Functions/Quantification/xASL_quant_M0.m (hunk 1 above)
Comment (jan-petr) [reply Functions/Quantification/xASL_quant_M0.m]: Good point! Actually, this figure depends on the sequence parameters, so it won't really matter if this differs. But in the future it could, so I'm adding the session+name. 06496526

File: Functions/Quantification/xASL_quant_M0.m [hunk 2]
```diff
@@ -387,7 +387,7 @@
 		xlabel('Slice (integer)');
 
 		% Save and close the figure
-		SavePath = fullfile(x.D.M0CheckDir, 'RevertBsupFxControl.jpg');
+		SavePath = fullfile(x.D.M0CheckDir, [x.SUBJECT '_' x.SESSION '_RevertBsupFxControl.jpg']);
```
Comment (HenkMutsaerts) [inline Functions/Quantification/xASL_quant_M0.m:395]: Did you check that x.SUBJECT & x.SESSION are defined at this point in the code? That was just a guess from me, I haven't tested that.

**Review by HenkMutsaerts — APPROVED** [review]
Please check my question otherwise approved

File: Functions/Quantification/xASL_quant_M0.m (hunk 2 above)
Comment (jan-petr) [reply Functions/Quantification/xASL_quant_M0.m:395]: Aha ;) Will check and if this works, I will merge But I'm 99% sure it is define, why wouldn't it :)

Comment (jan-petr) [reply Functions/Quantification/xASL_quant_M0.m:395]: Fixed
