### PR TITLE
#1833 DEBBIE motion correction

### LINKED ISSUE #1833: Motion correction for multi-PLD and multi-TE goes wrong
### Description

Similarly to control vs label images, images acquired at different PLD or TE will differ because of different TR after saturation, different amount of labeling inside, or different contrast because of different TE.
So if we perform motion correction, we need to be sure that it correct for motion and doesn't try to overcompensate for expected signal differences.

In DEBBIE sequence, This is mostly a problem for different TEs: they produce very different contrast leading to artificial estimated motion. For Time-encoding -> this doesn't generate large false motion. See images below for HAD4 and HAD8

image
This image shows for control and 3 PLDs and 8 TEs (DEBBIE FME HAD4, here still Hadamard encoded) that the assumed position change based on intensity-based alignment incorrectly thinks of pseudo-motion due to echo time changes.

Below the same for DEBBIE FME HAD8: single TE 7 PLDs & 1 control, two repetitions
image

### Tasks

- [x] During motion correction, identify multi-TE acquisition, time-encoded acqusition, multi-PLD without time-encoded, or standard acquisition.
- [x] For multi-TE: Perform motion correction only on the shortest TE. Turn of Zig-zag. Register to first image. Apply estimated motion in shortest TE for the other TEs within the same block.
- [x] For Time-encoded: Turn off Zig-zag. Register to first image. Perform normal motion correction as the images have the same TR.
- [x] For simple multi-PLD (without multi-TE and without time-encoding): Use Zig-zag. Register to first. For each PLD - register the images to the first for that PLD. Do not register across different PLDs
- [x] For standard acquisition. Use Zig-zag, register to mean. The standard way.
- [x] For multi-TE and multi-PLD - make sure the estimated parameters are put together correctly and saved to TXT and NII files as if a normal  motion correction would be executed. That means -> we only change the motion estimation and don't have to change any of the other functions.
- [x] Functions for calculating mean motion and plotting motion are moved to a sub-function for readability.

### How to test
Corrected version - see how motion doesn't change across TEs, but only between blocks.
Image

### Release notes

Fix multi-TE motion correction.

### PR DESCRIPTION
**Pull request by MimiE447**
### Linked issue

Close #1833

### CODE REVIEW

File: External/SPMmodified/spm_realign.m [hunk 1]
```diff
@@ -112,18 +112,18 @@
...
 %--------------------------------------------------------------------------
-def_flags          = spm_get_defaults('realign.estimate');
+def_flags          = spm_get_defaults('realign.estimate'); % Loads SPM's default realignment settings.
 def_flags.PW       = '';
-if bZigzag
-	def_flags.graphics = 1;
-	def_flags.quality  = 1;
-	def_flags.rtm      = 0;
-else
+if bZigzag % Zig-zag modifies defaults — zig-zag regression assumes a fixed reference image, not a moving mean.
```
Comment (HenkMutsaerts) [inline External/SPMmodified/spm_realign.m]: To me, this is not a clear explanation of zig-zag. Consider replacing with something like:

bZigZag is called this way because of the consistent control-label intensity differences, which can create a zig-zag motion pattern. To avoid this, bZigZag regresses out consistent intensity differences that are not due to motion. Another example is intensity differences with different TEs; these should not be removed by motion correction.

File: External/SPMmodified/spm_realign.m [hunk 2]
```diff
@@ -144,26 +144,33 @@
...
         ref(2:2:end)=1;
         if(ctrfirst), ref=-ref; end
-        P{1}=cleanandsave_parameters(P{1},ref);
-	end
+        % Builds zig-zag reference vector
+        P{1}=cleanandsave_parameters(P{1},ref); % This is where zig-zag regression happens
+    end 
 elseif numel(P) > 1
+      %  Multiple sessions
+      %  This block:
```
Comment (HenkMutsaerts) [inline External/SPMmodified/spm_realign.m]: "block" means "block of code"? consider replacing by

% This code section:

File: External/SPMmodified/spm_realign.m [hunk 3]
```diff
@@ -144,26 +144,33 @@
...
+      %  Aligns the first volume of each session
+      %  Applies that transform to all volumes in each session
+      %  Runs realignment within each session
+      %  Applies zig-zag cleaning per session
```
Comment (HenkMutsaerts) [inline External/SPMmodified/spm_realign.m:174]: What does session mean here?

File: External/SPMmodified/spm_realign.m [hunk 4]
```diff
@@ -605,16 +627,17 @@ function save_parameters(V)
 Q = zeros(n,6);
 clQ=zeros(n,6);
 for j=1:n
-	qq     = spm_imatrix(V(j).mat/V(1).mat);
-	Q(j,:) = qq(1:6);
-    clQ(j,:)=qq(1:6);
+	qq     = spm_imatrix(V(j).mat/V(1).mat); % Extract motion parameters
+	Q(j,:) = qq(1:6); % original motion (6 columns)
+    clQ(j,:)=qq(1:6); % copy to be cleaned
```
Comment (HenkMutsaerts) [inline External/SPMmodified/spm_realign.m]: If all these comments are added, perhaps clarify which part adds the parameters (the rp*.txt file has both without and with zig-zag regression), and which part prints the with zig-zag regression parameters to the .mat sidecar

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m [hunk 5]
```diff
@@ -83,18 +80,31 @@ function xASL_wrp_RealignASL(x, bASL)
...
 end
 
 if isfield(x.Q,'LookLocker') && x.Q.LookLocker
 	bMoCoPossible = false;
 	fprintf('%s\n',['Skipping motion correction for ' x.P.SubjectID '_' x.P.SessionID ' as Look-Locker correction is not implemented.']);
 end
 
+% Set flags for multi-TE and multi-PLD datasets
+if x.Q.nUniqueInitial_PLD>1 && (~isfield(x.modules.asl, 'bTimeEncoded') || ~x.modules.asl.bTimeEncoded)
+	% Here, we consider only simple multiPLD for averaging across PLDs. TimeEncoded is treated as singlePLD - because there are usually not many repetitions
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: I don't get this. TimeEncoded could have many repetitions, but moreover the opposite: singlePLD can easily have many repetitions, so saying that TimeEncoded is treated as singlePLD because TimeEncoded has not many repetitions is confusing.

Furthermore, skipping outlier detection should done with Hadamard (this is checked based on bMultiPLD below; so this means that a single TE Hadamard will have bMultiPLD=0 and bMultiTE=0 and outlier detection/ENABLE will not be skipped)

Essentially/simply speaking; Hadamard is a subcategory under MultiPLD, so suggestion if bMultiPLD should include Hadamard (or change boolean definitions)?

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m [hunk 6]
```diff
@@ -83,18 +80,31 @@ function xASL_wrp_RealignASL(x, bASL)
...
+    bMultiPLD = 1;
+else
+    bMultiPLD = 0;
+end
+
+if x.Q.nUniqueEchoTime>1
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m:110]: What is the difference between bMultiTE and nFramesPerTE > 1?
Or can we use one of these parameters?

Perhaps defining bMultiPLD and bMultiTE earlier above, and use throughout

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m [hunk 7]
```diff
@@ -162,19 +172,19 @@ function xASL_wrp_RealignASL(x, bASL)
...
-if nFrames < 10 % Only execute ENABLE if we have at least 5 control-label pairs (==10 volumes)
+if nFramesPerTE < 10 % Only execute ENABLE if we have at least 5 control-label pairs (==10 volumes)
 	bENABLE = false;
 end
 
 
 %% Manage zig-zag in motion correction
-if x.Q.nUniqueInitial_PLD>1 || x.Q.nUniqueEchoTime>1
-    % ZigZag are temporarily disabled for multiPLD/TE
+if bMultiTE || x.modules.asl.bTimeEncoded
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m:188]: Why not for MultiPLD?

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m [hunk 8]
```diff
@@ -192,114 +202,158 @@ function xASL_wrp_RealignASL(x, bASL)
...
+	case 1 % normal quality
+		flags.quality = 1;
+		flags.sep = minVoxelSize;
+	case 0 % low quality for fast try-out
+		flags.quality = 0.01;
+		flags.sep = minVoxelSize*2;
+end
+
+if bMultiTE || bMultiPLD 
+	flags.rtm = 0; % disable realign to mean
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: Well theoretically you would still want this, but then within the PLD, or within the first TE only.

The idea is that realigning to the mean is always better than realigning to the first, as this equally spreads the interpolations, and there won't be any bias towards the awake or sleepy phase (head position/motion can be correlated with brain state). The realigning to the first (first-pass) is only needed to get the estimates to get the mean position.

So theoretically we should still enable realign to mean (the second-pass). In practice the difference may be small because of the low numbers of repeats; but then again the number of repeats (with equal acquisition duration) shouldn't matter; we can still have the situation in which all acquisitions were quite far from the first, because the pt got scared after the start of the sequence but then managed to stay still in the new position.

So I would always keep the realign to the mean (second pass)

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m [hunk 9]
```diff
@@ -192,114 +202,158 @@ function xASL_wrp_RealignASL(x, bASL)
...
+
+% Run motion correction for corresponding case
+% Note that this is the adapted spm_realign, including zig-zag
+% regression to account for ASL's potential control-label difference in
+% average head position
+
+V = spm_vol(InputPath); 
+
+if bMultiTE || bMultiPLD
+	% Prepare for updating the volumes - this is not necessary for the simple case where all is handeled by spm_realign
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: So why don't we always do this; this will create negligible extra computation time, but it makes the code easier (one if statement less), and potentially more reproducible?

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m [hunk 10]
```diff
@@ -192,114 +202,158 @@ function xASL_wrp_RealignASL(x, bASL)
...
+	Y = spm_read_vols(V); % Read the image
+	rp_all = zeros(nFrames, 6); % The final aggregate RP-file
+	mat_all = zeros(4, 4, size(Y,4)); % The final aggregate MAT-file
+end
+
+if bMultiTE
+    % Handles Multi-TE dataset regardless of PLD
+	% Registers all frames with the shortest PLDs and then applies the same transformation to all the longer PLDs
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: I assume this should be TEs in this sentences instead of PLDs?

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m [hunk 11]
```diff
@@ -192,114 +202,158 @@ function xASL_wrp_RealignASL(x, bASL)
...
+	% It assumes that the volume is sorted in the order of acquisition with blocks of increasing TEs
+    
+	% Indexes that flags the first/shortest TEs frames
+    idx_firstTE = find((x.Q.EchoTime == min(x.Q.EchoTime)));
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: Strictly speaking, it should be idx_minTE and idx_maxTE, e.g. with Thijs' TEprep sequence you could have larger TEs being earlier than smaller TEs?

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m [hunk 12]
```diff
@@ -192,114 +202,158 @@ function xASL_wrp_RealignASL(x, bASL)
...
+	idx_lastTE =  find((x.Q.EchoTime == max(x.Q.EchoTime)));
+    
+	if length(idx_firstTE) ~= length(idx_lastTE)
+		% TEs should form blocks and thus have the same lengths
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: Consider replacing by:

% TEs should all have the same number of blocks (e.g., control-label repetitions and/or PLDs)

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m [hunk 13]
```diff
@@ -192,114 +202,158 @@ function xASL_wrp_RealignASL(x, bASL)
...
+		error('Number of shortest TEs and longest TEs do not match');
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: Consider rephrasing:

Number of shortest TEs and longest TEs do not match, check if there are missing frames/volumes.

Also: is this an error that we can make more general, e.g., move above, where we check if all "dimensions" (control-label, repetitions, TEs, PLDs) are completely acquired?

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m [hunk 14]
```diff
@@ -192,114 +202,158 @@ function xASL_wrp_RealignASL(x, bASL)
...
-		if ii==2
-			NDV{2} = [0; NDV{2}]; % add leading zero difference
+
+	% Realigns only the flagged frames
+    spm_realign(V(idx_firstTE), flags, bZigZag); 
+	% This affects the ASL4D.mat file, rp_ASL4D.txt file and MAT within the ASL4D.nii volume
+    
+    rp_temp = load(rpfile); % Load the rp file written by spm_realign
+
+	V = spm_vol(InputPath); % Read the updated volumes
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m:276]: Move out of this if-statement -> you can also do this with a single TE, it will be negligible extra processing time but easier to read code and more reproducible.

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m [hunk 15]
```diff
@@ -192,114 +202,158 @@ function xASL_wrp_RealignASL(x, bASL)
...
-				title(['Motion plot of ' x.P.SubjectID '-' x.P.SessionID]);
-				ylabel('NDV/frame (mm//frame)');
-			end
-			
-			xlabel('frame#');
-			axis([1 length(NDV{ii}) 0 ceil(max(NDV{ii}))]); % fix X-axes to be same for subplots
+        
+    end
+    
+elseif bMultiPLD
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: So bMultiTE and bMultiPLD are mutually exclusive in this if-statement; they should not be right?

And the case of TimeEncoded is again different; then I would use bTimeEncoded for this

Or at least manage bZigZag separately, as we do for the simple case

(in the near future, you could do bMultiPLD for Time Encoded as well, because you can decode which images belong to which PLD)

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m [hunk 16]
```diff
@@ -192,114 +202,158 @@ function xASL_wrp_RealignASL(x, bASL)
...
+	% Realigns only the flagged frames
+    spm_realign(V(idx_firstTE), flags, bZigZag); 
+	% This affects the ASL4D.mat file, rp_ASL4D.txt file and MAT within the ASL4D.nii volume
+    
+    rp_temp = load(rpfile); % Load the rp file written by spm_realign
+
+	V = spm_vol(InputPath); % Read the updated volumes
+    % Loop through TE groups
+    for idxTE = 1:length(idx_firstTE)
+        % Repeats the motion estimates extracted from the rp file for the rest of the TEs and writes to the corresponding rows in rp_all
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m:279]: Consider adding

(rp_all is what ends up in the rp*.txt sidecar, rp=realign parameters)

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m [hunk 17]
```diff
@@ -192,114 +202,158 @@ function xASL_wrp_RealignASL(x, bASL)
...
+        rp_all(idx_firstTE(idxTE):idx_lastTE(idxTE), :) = repmat(rp_temp(idxTE,:), x.Q.nUniqueEchoTime, 1); 
+    
+		for idxAllTE = idx_firstTE(idxTE):idx_lastTE(idxTE)
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: Consider adding

(mat_all is what ends up in the ASL*.mat sidecar, containing the orientation matrices for each frame/volume)

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m [hunk 18]
```diff
@@ -192,114 +202,158 @@ function xASL_wrp_RealignASL(x, bASL)
...
-			axis([1 length(NDV{ii}) 0 ceil(max(NDV{ii}))]); % fix X-axes to be same for subplots
+        
+    end
+    
+elseif bMultiPLD
+    % Handles only Multi-PLD datasets - aligns only between the same PLDs
+	% Motion correction across all PLDs is not really necessary as that can be done with the simple motion correction
+	% Note that we handle normal mutli-PLD (not TimeEncoded), so there are still control and label images and we can thus do ZigZag
+
+    for pld = x.Q.uniqueInitial_PLD(:)'
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: do this for each case, also for singlePLD, and also for multi-TE multi-PLD

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m [hunk 19]
```diff
@@ -34,12 +34,10 @@ function xASL_wrp_RealignASL(x, bASL)
...
-% Licensed under Apache 2.0, see permissions and limitations at
-% https://github.com/ExploreASL/ExploreASL/blob/main/LICENSE
-% you may only use this file in compliance with the License.
-% __________________________________
-
-
+% Licensed under Apache 2.0, see permissions and limitations at
+% https://github.com/ExploreASL/ExploreASL/blob/main/LICENSE
+% you may only use this file in compliance with the License.
+% __________________________________
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m:42]: Add this to description (we can improve later):

+% Note that:^M
+% A. This submodule distinguishes ASL (control-label) pairs from non-ASL (e.g. fMRI/DTI), as with control-label pairs,^M
+% the zig-zag approach is used, in which the average control vs label intensity differences are disregarded (not erroneously seen as motion).^M
+% B. If multiple TEs are acquired, only the first TE (with the highest SNR) is used for motion estimation^M
+% C. Motion outlier detection is skipped for multiple PLDs and/or multiple TEs

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m [hunk 20]
```diff
@@ -69,12 +68,10 @@ function xASL_wrp_RealignASL(x, bASL)
 
 %% Read basic image information
 tempnii = xASL_io_ReadNifti(InputPath);
-nFrames = double(tempnii.hdr.dim(5));
-if length(x.Q.EchoTime)>1
-    nFrames=nFrames/numel(unique(x.Q.EchoTime));
-end
-minVoxelSize = double(min(tempnii.hdr.pixdim(2:4)));
+nFrames = double(tempnii.hdr.dim(5)); % Total number of frames
+nFramesPerTE=nFrames/numel(unique(x.Q.EchoTime)); % Number of frames per unique TE
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: Add comments:

% (note that for most cases, where we only have a single TE, nFramesPerTE==nFrames

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m [hunk 21]
```diff
@@ -83,18 +80,31 @@ function xASL_wrp_RealignASL(x, bASL)
...
-elseif nFrames > 1
+elseif nFramesPerTE > 1
 	bMoCoPossible = true;
 else
 	bMoCoPossible = false;
-	fprintf('%s\n',['Skipping motion correction for ' x.P.SubjectID '_' x.P.SessionID ' because it had only ' num2str(nFrames) ' 3D frames.']);
+	fprintf('%s\n',['Skipping motion correction for ' x.P.SubjectID '_' x.P.SessionID ' because it had only ' num2str(nFramesPerTE) ' 3D frames.']);
 end
 
 if isfield(x.Q,'LookLocker') && x.Q.LookLocker
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: Move this to the if-statement right before here, as first

(if bLookLocker, bContainsSubtracted, bMultiTE)

**Review by HenkMutsaerts — CHANGES_REQUESTED** [review]
1. xASL_wrp_RealignASL: main comment is that we should simplify the code such that singlePLD will be processed as a multiPLD, and singleTE will be processed as a multiTE. And to make these flavor categories independent, e.g. at the top we define bZigZag, instead of saying "Time Encoded cannot be bMultiPLD because we do zig-zag for multi PLD but not for time encoded"

2. I assume that 2. Calculate and plot and 3. outlier detection weren't changed significantly (except for skipping in certain cases), so didn't check this (the github diff doesn't work here unfortunately)

3. So `spm_realign` doesn't seem to change, only comments are added for readability?

**Comment by jan-petr** [comment]
> 1. xASL_wrp_RealignASL: main comment is that we should simplify the code such that singlePLD will be processed as a multiPLD, and singleTE will be processed as a multiTE. And to make these flavor categories independent, e.g. at the top we define bZigZag, instead of saying "Time Encoded cannot be bMultiPLD because we do zig-zag for multi PLD but not for time encoded"

Agree - will improve the comments

> 2. I assume that 2. Calculate and plot and 3. outlier detection weren't changed significantly (except for skipping in certain cases), so didn't check this (the github diff doesn't work here unfortunately)

Yes - this was only moved to a subfunction. No functionality edits.

> 3. So `spm_realign` doesn't seem to change, only comments are added for readability?
Yes - just comments added by Mimi to help her understand it.

File: External/SPMmodified/spm_realign.m (hunk 1 above)
Comment (jan-petr) [reply External/SPMmodified/spm_realign.m]: Done

File: External/SPMmodified/spm_realign.m (hunk 2 above)
Comment (jan-petr) [reply External/SPMmodified/spm_realign.m]: Done

File: External/SPMmodified/spm_realign.m (hunk 3 above)
Comment (jan-petr) [reply External/SPMmodified/spm_realign.m:174]: Session is internal name inside spm_realign which means that the registration is split into blocks. I improved the comment, but won't change the terminology as this is the terminology of SPM and it explains this in the header.

File: External/SPMmodified/spm_realign.m (hunk 4 above)
Comment (jan-petr) [reply External/SPMmodified/spm_realign.m]: Done

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m (hunk 10 above)
Comment (jan-petr) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: Yes. Good catch :)

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m (hunk 12 above)
Comment (jan-petr) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: Done

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m (hunk 13 above)
Comment (jan-petr) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: Done.


For PLDs and repetitions, this is already checked before. Here, we don't check consistency of data, we kind of check if it will crash or not with the current code. So we prevent crashing without an explanation.

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m (hunk 16 above)
Comment (jan-petr) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m:279]: Done on a line where rp_all is initialized

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m (hunk 17 above)
Comment (jan-petr) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: added also on the initialization line.

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m (hunk 20 above)
Comment (jan-petr) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: Done

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m (hunk 19 above)
Comment (jan-petr) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m:42]: Done

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m (hunk 6 above)
Comment (jan-petr) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m:110]: nFramesPerTE is effectively the number of repetitions irrespective of TE. 

bMultiTE does not necessarily have nFramesPerTE > 1. 

I'll improve the definitions and comments

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m (hunk 5 above)
Comment (jan-petr) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: Agree. For transparency, we treat all as multi-PLD - even multi-TE and Time-encoded.

Then we modify the exact choices based on this... Like switching ENABLE etc. Modified throughout the code.

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m (hunk 7 above)
Comment (jan-petr) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m:188]: This is correct. Standard multi-PLD has controls and labels, so we can run Zig-zag. I've added a comment about this.

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m (hunk 8 above)
Comment (jan-petr) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: Agree. I'm deleting this.

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m (hunk 9 above)
Comment (jan-petr) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: For single-PLD, we don't use these parameters at all. That's handeled within SPM. So it would make the code more convoluted.

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m (hunk 11 above)
Comment (jan-petr) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: Good point. Fixed.

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m (hunk 14 above)
Comment (jan-petr) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m:276]: It can't be moved out of the if-statement. It has to be run after spm_realign for multi_TE, but before we reassemble it for the other TEs. So it has to be within this loop.

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m (hunk 15 above)
Comment (jan-petr) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: They kind of are.
The options -> sorted by priority are
MultiTE-multiPLD
multiTE-singlePLD
singleTE-multiPLD
singleTE-singlePLD

We just skip certain options because we don't have them, so I can't really nicely test them. Shall I add these options and say that they are implemented?

Timenecoded option is now properly fixed. And Zigzag as well.

MultiPLD-timeencoded won't really have a specific option because we don't have sufficient repetitions. So for that, we will need the boundary based registration.

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m (hunk 18 above)
Comment (jan-petr) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: Not sure what should we do - see the other comments.

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m (hunk 21 above)
Comment (jan-petr) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: Done

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m (hunk 15 above)
Comment (HenkMutsaerts) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: The way I would like it, is that singleTE is processed as multiTE, and singlePLD is processed as multiPLD. This is how we changed the rest of the pipeline as well. Creates negligible processing overhead but makes the code easier and more reproducible (fewer if-statements).

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m [hunk 22]
```diff
@@ -162,19 +181,20 @@ function xASL_wrp_RealignASL(x, bASL)
...
 
 
 %% Manage zig-zag in motion correction
-if x.Q.nUniqueInitial_PLD>1 || x.Q.nUniqueEchoTime>1
-    % ZigZag are temporarily disabled for multiPLD/TE
+if bMultiTE || x.modules.asl.bTimeEncoded
+    % ZigZag are temporarily disabled for multiTE and TimeEncoded
     % as we are still developing this feature
+	% Note that for standard multi-PLD, Zig-zag can be applied because standard multi-PLD still has controls and labels
     fprintf('%s\n', 'multi-PLD or multi-TE detected, disabling zig-zag motion estimation, not yet implemented');
```
Comment (HenkMutsaerts) [inline Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: Change into:

fprintf('%s\n', 'Time-encoded or multi-TE detected, disabling zig-zag motion estimation, not yet implemented');

**Review by HenkMutsaerts — CHANGES_REQUESTED** [review]
Can you please change it such that:

1. Process singleTE similar as MultiTE (extra overhead, but programming-wise more consistent. I'm fine with keeping the if-statement for updating the transformation matrices, but would like to remove the if statement for the realignment estimation split of singleTE and multiTE
2. Process singlePLD similar as multiPLD (for same reason as above).

I'm also happy to implement this, but perhaps faster if you do this.
We do this as well with our other code; makes it also easier to expand later on.

File: Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m (hunk 22 above)
Comment (jan-petr) [reply Modules/Module_Processing/Module_ASL/xASL_wrp_RealignASL.m]: Done

**Review by jan-petr — APPROVED** [review]
OK

**Review by HenkMutsaerts — APPROVED** [review]
