### PR TITLE
#586 xASL_adm_GetPopulationSessions: avoid crashing if no sessions found

### LINKED ISSUE #586: xASL_adm_GetPopulationSessions
### Description

`xASL_adm_GetPopulationSessions` crashes when no sessions are found

### Requirements

Minor change, easy fix

### Release notes

Minor bugfix for `xASL_adm_GetPopulationSessions` to avoid crashing if no sessions are found

### PR DESCRIPTION
**Pull request by HenkMutsaerts**
### Linked issue

Closes #586

### CODE REVIEW

File: Functions/xASL_adm_GetPopulationSessions.m [hunk 1]
```diff
@@ -19,6 +20,12 @@
 %   5. Check and provide warning of number of sesssions differs per subject
 
 %% 1. Administration
+if ~isfield(x, 'SESSIONS')
+    SESSIONS = 'ASL_1';
```
Comment (MDijsselhof) [inline Functions/xASL_adm_GetPopulationSessions.m:24]: But what if some subjects don't have a first session?

**Review by MDijsselhof — COMMENTED** [review]
Hi Henk-Jan, 

I've left a single comment, curious what you think!

**Review by jan-petr — CHANGES_REQUESTED** [review]
We have to update certain fields similarly as done in #480 . Becausehere, we add new x.nSessions and x.nSubjectSessions - the whole difference file has to be checked and potentially updated... This won't show as a conflict as these are newly added lines. @MichaelStritt should check as he knows what to fix...

**Comment by MichaelStritt** [comment]
> 
> 
> We have to update certain fields similarly as done in #480 . Becausehere, we add new x.nSessions and x.nSubjectSessions - the whole difference file has to be checked and potentially updated... This won't show as a conflict as these are newly added lines. @MichaelStritt should check as he knows what to fix...

In  `Functions/xASL_stat_GetROIstatistics.m`:
- we moved x.WBmask to x.S.masks.WBmask

In `Functions/xASL_stat_PrintStats.m`:
- we moved x.nSessions to x.dataset.nSessions

**Comment by MichaelStritt** [comment]
@jan-petr: I only changed the code sections that were changed by #586. The should work with #480 now. There will still be some conflict resolving.

**Review by MichaelStritt — APPROVED** [review]
Should be fine with regard to #480

File: Functions/xASL_adm_GetPopulationSessions.m (hunk 1 above)
Comment (HenkMutsaerts) [reply Functions/xASL_adm_GetPopulationSessions.m:24]: Good point, should the default be an empty `SESSIONS` output then?

File: Functions/xASL_stat_GetROIstatistics.m [hunk 2]
```diff
@@ -177,7 +177,7 @@
 
 %% Define number of sessions to use
 
-[nSessions, bSessionsMissing] = xASL_adm_GetPopulationSessions(x); % obtain number of Sessions by determining amount of input files present in the Population folder
+[nSessions, bSessionsMissing, x.SESSIONS] = xASL_adm_GetPopulationSessions(x); % obtain number of Sessions by determining amount of input files present in the Population folder
```
Comment (HenkMutsaerts) [inline Functions/xASL_stat_GetROIstatistics.m:180]: Is this third new output parameter `x.SESSIONS` used? I'm not sure if we should avoid this, since `x.SESSIONS` is also used in the Structural and ASL modules.

**Review by HenkMutsaerts — COMMENTED** [review]
Am I actually reviewing my own work? :) I thought I found some parts that I wrote :)

File: Functions/xASL_adm_GetPopulationSessions.m (hunk 1 above)
Comment (MichaelStritt) [reply Functions/xASL_adm_GetPopulationSessions.m:24]: If you load a dataset that has at least one sessions, you will definitely get a SESSIONS field, even if you did not manually define SESSIONS (`[x] = ExploreASL_Master(my-bids-dataset,0,0);`).

**Comment by HenkMutsaerts** [comment]
@jan-petr @MDijsselhof Yes, I agree. We might soon revamp all this when we move to BIDS derivatives, but for now I believe it is safe to assume that there is an `ASL_1`. If there are no ASL sessions, this works as well.

**Comment by MichaelStritt** [comment]
Great, then only @jan-petr needs to re-approve

File: Functions/xASL_adm_GetPopulationSessions.m (hunk 1 above)
Comment (jan-petr) [reply Functions/xASL_adm_GetPopulationSessions.m:24]: @MichaelStritt but that would mean that this condition above never really happens. So we can define an empty session there?!

**Review by jan-petr — APPROVED** [review]
Fine to merge.

**Comment by jan-petr** [comment]
I am not able to remove Mathijs from the review - he either appears as not-approved-yet or as has-a-comment. So lets keep it as it is and merge. @BeatrizPadrela seems to be assigned for this ;)
