### PR TITLE
Closes #975 Fix GE eASL import

### LINKED ISSUE #975: Import of GE eASL
### Description

Add GE eASL to flavors and make sure that the import works

https://github.com/ExploreASL/FlavorDatabase/pull/13

### Requirements

- Import is reading LD and PLD from DICOM. But for multi-PLD eASL, this is broken and we have to supply these manually and override the incorrect DICOM values.

### Release notes

Fix import of GE eASL sequence.

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

#975

### CODE REVIEW

File: Functions/xASL_bids_BIDSifyASLJSON.m [hunk 1]
```diff
@@ -344,7 +362,7 @@
 		% Make sure the vector is a row vector
 		jsonOut.(listFieldsZero{iRepeat}) = jsonOut.(listFieldsZero{iRepeat})(:)';
 		% Check the all m0scans have zeros
-		if ~isequal(ASLContextM0Index,jsonOut.(listFieldsZero{iRepeat})==0)
+		if sum(ASLContextM0Index .* (jsonOut.(listFieldsZero{iRepeat})~=0))
```
Comment (MichaelStritt) [inline Functions/xASL_bids_BIDSifyASLJSON.m:365]: If you say this works then I'd trust you 😆 we'll re-test for the release anyway

**Review by MichaelStritt — APPROVED** [review]
👍

File: Functions/xASL_bids_BIDSifyASLJSON.m (hunk 1 above)
Comment (jan-petr) [reply Functions/xASL_bids_BIDSifyASLJSON.m:365]: Haha - yes, it works. Previously it didn't :D
