### PR TITLE
#1707 Fix mirrored Siemens MOSAIC import

### LINKED ISSUE #1707: Siemens MOSAIC incorrectly imported
### Description

dcm2niix is struggling with import of Siemens MOSAIC images. The worst issue is when the Phoenix field is missing. When at the same time is the ImageOrientationPatient expecting superior to inferior orientation, the output is incorrectly rendered, mirroring the brain above the top of the head.

This special case needs to be detected and mirrored back manually after dcm2niix.

Example is:
Siemens_PCASL_3DGRASE_VE11C_5

### Tasks

- [x] Identify the special case
- [x] Flip the orientation and matrix manually
- [x] Finalize and add the flavor
- [x] Run flavor testing

### Release notes

Deal with mirrored Siemens MOSAIC DICOMs.

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

Close #1707

### CODE REVIEW

File: External/SPMmodified/xASL/xASL_io_SaveNifti.m [hunk 1]
```diff
@@ -226,7 +226,8 @@ function xASL_io_SaveNifti(pathOrigNifti, pathNewNifti, imNew, nBits, bGZip, cha
 %% ====================================================================================
 %% 3. Create new NIfTI
 if ~isempty(changeMat)
-	newNifti.mat = changeMat;
+	newNifti.mat  = changeMat;
```
Comment (HenkMutsaerts) [inline External/SPMmodified/xASL/xASL_io_SaveNifti.m:239]: mat0 should be the original orientation, as it comes from the scanner. This is useful for provenance checks in the orientation changes, e.g. for checking if there is a left-right flip, so theoretically we should never change mat0.

mat is whatever we want it to be, so can be changed

File: Modules/Module_Import/Import/xASL_imp_DCM2NII_Subject_SortASLVolumes.m [hunk 2]
```diff
@@ -146,6 +146,21 @@
         elseif  ~isempty(strfind(scan_name,'M0'))
             [nii_files,ASLContext] = xASL_bids_MergeNifti(nii_files, 'M0', niiTable);
         end
+	else
+		% In case of a single file, we need to check issues with orientation
+		% Check for a special case of Siemens MOSAIC files without Phoenix field
+		if isfield(tmpJSON, 'Manufacturer') && strcmpi(tmpJSON.Manufacturer, 'Siemens') && isfield(tmpJSON, 'ImageType') && ~isempty(regexpi(tmpJSON.ImageType, 'MOSAIC')) && (~isfield(tmpJSON, 'PhoenixProtocol') || isempty(tmpJSON.PhoenixProtocol))
```
Comment (HenkMutsaerts) [inline Modules/Module_Import/Import/xASL_imp_DCM2NII_Subject_SortASLVolumes.m]: For readability, I would put the if cases on separate rows:

if isfield(tmpJSON, 'Manufacturer') && strcmpi(tmpJSON.Manufacturer, 'Siemens')
% this happens only for Siemens scans

if isfield(tmpJSON, 'ImageType') && ~isempty(regexpi(tmpJSON.ImageType, 'MOSAIC'))
% Siemens MOSAIC scans specifically

if ~isfield(tmpJSON, 'PhoenixProtocol') || isempty(tmpJSON.PhoenixProtocol)
% Siemens MOSAIC scans that have no Phoenix protocol stored in the DICOM header

File: Modules/Module_Import/Import/xASL_imp_DCM2NII_Subject_SortASLVolumes.m [hunk 3]
```diff
@@ -146,6 +146,21 @@
...
+			niftiData = xASL_io_ReadNifti(nii_files{1});
+			% We check for a special case of image center in the Z-direction not being crossing 0
+			if (sum(niftiData.mat(:,3)) > 0) && (niftiData.mat(3,4) > 0)
+				% The image is mirrored in the Z-direction, we need to fix the image matrix and the orientation matrix
+				im = xASL_io_Nifti2Im(nii_files{1});
+				im = im(:,:,end:-1:1,:,:,:);
+				mat = niftiData.mat;
```
Comment (HenkMutsaerts) [inline Modules/Module_Import/Import/xASL_imp_DCM2NII_Subject_SortASLVolumes.m]: You can move this line up so we have:

if (sum(mat(:,3)) > 0) && (mat(3,4) > 0)

File: Modules/Module_Import/Import/xASL_imp_DCM2NII_Subject_SortASLVolumes.m [hunk 4]
```diff
@@ -146,6 +146,21 @@
         elseif  ~isempty(strfind(scan_name,'M0'))
             [nii_files,ASLContext] = xASL_bids_MergeNifti(nii_files, 'M0', niiTable);
         end
+	else
+		% In case of a single file, we need to check issues with orientation
+		% Check for a special case of Siemens MOSAIC files without Phoenix field
+		if isfield(tmpJSON, 'Manufacturer') && strcmpi(tmpJSON.Manufacturer, 'Siemens') && isfield(tmpJSON, 'ImageType') && ~isempty(regexpi(tmpJSON.ImageType, 'MOSAIC')) && (~isfield(tmpJSON, 'PhoenixProtocol') || isempty(tmpJSON.PhoenixProtocol))
+			niftiData = xASL_io_ReadNifti(nii_files{1});
```
Comment (HenkMutsaerts) [inline Modules/Module_Import/Import/xASL_imp_DCM2NII_Subject_SortASLVolumes.m:156]: Should we have a warning if there are more than 1 nii_files?

File: Modules/Module_Import/Import/xASL_imp_DCM2NII_Subject_SortASLVolumes.m [hunk 5]
```diff
@@ -146,6 +146,21 @@
...
+			% We check for a special case of image center in the Z-direction not being crossing 0
+			if (sum(niftiData.mat(:,3)) > 0) && (niftiData.mat(3,4) > 0)
+				% The image is mirrored in the Z-direction, we need to fix the image matrix and the orientation matrix
+				im = xASL_io_Nifti2Im(nii_files{1});
+				im = im(:,:,end:-1:1,:,:,:);
```
Comment (HenkMutsaerts) [inline Modules/Module_Import/Import/xASL_imp_DCM2NII_Subject_SortASLVolumes.m]: For some reason I remember that we should have 7 dimensions (not that we ever have this but this is SPM default I thought). And it's a lucky Christianity number ;)

**Review by HenkMutsaerts — CHANGES_REQUESTED** [review]
Minor^2 comments

File: Modules/Module_Import/Import/xASL_imp_DCM2NII_Subject_SortASLVolumes.m (hunk 5 above)
Comment (jan-petr) [reply Modules/Module_Import/Import/xASL_imp_DCM2NII_Subject_SortASLVolumes.m]: Now we have religion also in coding?! :) 

Sure - adding 7 :)

File: External/SPMmodified/xASL/xASL_io_SaveNifti.m (hunk 1 above)
Comment (jan-petr) [reply External/SPMmodified/xASL/xASL_io_SaveNifti.m:239]: Good point. We keep mat0 as it is... Except in this case. dcm2niix really messes up import and creates a completely incorrect mat and mat0 that have nothing to do with the scanner orientation. So we need to change both in this case. So I'm adding mat0 as an extra parameter to xASL_io_SaveNifti and comment that this is exceptional.

File: Modules/Module_Import/Import/xASL_imp_DCM2NII_Subject_SortASLVolumes.m (hunk 3 above)
Comment (jan-petr) [reply Modules/Module_Import/Import/xASL_imp_DCM2NII_Subject_SortASLVolumes.m]: Done

File: Modules/Module_Import/Import/xASL_imp_DCM2NII_Subject_SortASLVolumes.m (hunk 2 above)
Comment (jan-petr) [reply Modules/Module_Import/Import/xASL_imp_DCM2NII_Subject_SortASLVolumes.m]: I've separated it to four lines. But I avoided doing several IFs cause this creates too much ifs, ends, and too many line indents...

File: Modules/Module_Import/Import/xASL_imp_DCM2NII_Subject_SortASLVolumes.m (hunk 4 above)
Comment (jan-petr) [reply Modules/Module_Import/Import/xASL_imp_DCM2NII_Subject_SortASLVolumes.m:156]: Not needed - we're in an IF branch that only has 1 nii_files. So we only need {1} to move from cell to character array, but it cannot happen here that we have more than 1 nii_files at this line.

File: External/SPMmodified/xASL/xASL_io_SaveNifti.m (hunk 1 above)
Comment (HenkMutsaerts) [reply External/SPMmodified/xASL/xASL_io_SaveNifti.m:239]: Annoying... I would be in favor not clouding our code for a very special occasion that will be soon fixed by dcm2nii (at least it should). Nobody else will change the mat0

File: External/SPMmodified/xASL/xASL_io_SaveNifti.m [hunk 6]
```diff
@@ -226,7 +236,11 @@ function xASL_io_SaveNifti(pathOrigNifti, pathNewNifti, imNew, nBits, bGZip, cha
 %% ====================================================================================
 %% 3. Create new NIfTI
 if ~isempty(changeMat)
-	newNifti.mat = changeMat;
+	newNifti.mat  = changeMat;
+end
+
+if ~isempty(changeMat0)
+	newNifti.mat0 = changeMat0;
```
Comment (HenkMutsaerts) [inline External/SPMmodified/xASL/xASL_io_SaveNifti.m:244]: Please add a warning here that you change mat0

warning('Note that mat0 (the original NIfTI orientation) is changed upon request, this can jeopardize re-re-running ExploreASL!');

Because when we rerun ExploreASL, several orientations are defaulted back to mat0. So in this case, you need this warning. If you don't need it for import, then we need a bVerbose boolean to suppress such warnings.

But if this is a very exceptional case, then we can just always issue the warning.

**Review by HenkMutsaerts — CHANGES_REQUESTED** [review]
Nice, small comment

File: External/SPMmodified/xASL/xASL_io_SaveNifti.m (hunk 1 above)
Comment (jan-petr) [reply External/SPMmodified/xASL/xASL_io_SaveNifti.m:239]: Yes. Annoying, but dcm2niix has a lot of bugs and shortcomings that are not going to be fixed in the near future... So we have to accept that fact.

File: External/SPMmodified/xASL/xASL_io_SaveNifti.m (hunk 6 above)
Comment (jan-petr) [reply External/SPMmodified/xASL/xASL_io_SaveNifti.m:244]: It's a very exceptional case and the user can be aware of that. So I'd indeed always issue this warning without a possibility to suppress. 

Warning added.

File: External/SPMmodified/xASL/xASL_io_SaveNifti.m [hunk 7]
```diff
@@ -26,6 +26,8 @@ function xASL_io_SaveNifti(pathOrigNifti, pathNewNifti, imNew, nBits, bGZip, cha
 %   bOverwrite     Vector with 3 Booleans for overwriting the following pre-existing destination files:
 %                  1) NIfTI file, 2) JSON file, 3) mat-orientation motion file (for 4D NIfTIs) (OPTIONAL, DEFAULT = [1 1 1]; 
 %                  1 -> [1 1 1] and 0 -> [0 0 0] and creates a warning; [1 0] - error
+%   changeMat0     New orientation matrix mat0 4x4. Note that mat0 should always stay as it was originally from the scanner, 
+%                  but we can exceptionally change it if mat0 was completely wrong (OPTIONAL, DEFAULT same as previous)
```
Comment (HenkMutsaerts) [inline External/SPMmodified/xASL/xASL_io_SaveNifti.m]: instead of "exceptionally change it" (which is not grammatically correct I believe :) I would write:

"but in rare cases we change it if the orientation matrix was not correctly converted from the DICOM header."

**Review by HenkMutsaerts — APPROVED** [review]
minor comment left

File: External/SPMmodified/xASL/xASL_io_SaveNifti.m (hunk 7 above)
Comment (jan-petr) [reply External/SPMmodified/xASL/xASL_io_SaveNifti.m]: Fixing
